### PR TITLE
Add Mouse Resize

### LINKED ISSUE #222: Mouse Resizing
Currently dashitems can only be resized by changing the values through the property panel. We want to be able to resize them by dragging at the corner with your mouse as well. This should only be implemented after #205.

### PR DESCRIPTION
**Pull request by zangjiucheng**
## Description

This is the implementation of the mouse resize function for dashboard items.

https://github.com/waterloo-rocketry/omnibus/assets/56462380/3fa6ee57-5aea-4b26-87de-8da472769c51

I changed `dashboard_item.py` with the following:
- add two properties, `bool: corner_grabbed` and `int: corner_size`
- add some function to detect if the mouse is at the corner.

This PR closes #222.

## Developer Testing

Here's what I did to test my changes:

- Test graphs, dashboards, and process bars ...... to check if it work with mouse resizing

## Reviewer Testing

- Test any part of the dashboard item to see if you can use the mouse resize feature.

## Note: 
Since this is a high-priority issue, I first updated this functional working version for review... 

**FUTURE IMPROVEMENTS**: Get scaling from the dashboard class and use scaling for mouse zoom.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240)

### CODE REVIEW

**Comment by zangjiucheng** [comment]
I messy up my branch control, I will fix this and reupload it again.

**Comment by zangjiucheng** [comment]
Fixed :)

**Review by patrick-gu — CHANGES_REQUESTED** [review]
This is amazing! Definitely having the rescaling correct would make it a bit more intuitive, but I think this is good for now. Maybe we could use this and then leave that as an open issue.

One bug I noticed is if you double click on the square it makes everything glitch out.

A few misc things to note, but don't really need to be fixed:
- I think this makes it easier to find rendering bugs lol. I noticed that the progress bar will sometimes get font size 0 and that would display a warning in the console. You don't need to fix it but things like that which we notice we can keep in mind
- I think the corner renders underneath the content, and this is mainly apparent with the image component in there. But it would still be grabbable. I do believe this should be the correct behaviour of this feature - allowing for easy usage and avoiding blocking off content.
- Also added 2 minor comments

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-:-O00bKej5Hhsog38In5s:b4twnca)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/dashboard_item.py` line 105 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O00bT8k5rGd3DHj5O8S:-O00bT8k5rGd3DHj5O8T:b-l7ioq4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7b6d1053032e56a86fa6c41b7c089784dde0c71d/sinks/dashboard/items/dashboard_item.py#L105)):*
> ```Python
>     """
>     The following functions are used to make the widget resizable by dragging the bottom right corner.
>     """
> ```

I think this should be just a normal # comment
___
*[`sinks/dashboard/items/dashboard_item.py` line 140 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O00bcS50FfwYM0LUyz4:-O00bcS50FfwYM0LUyz5:b-flzu59) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7b6d1053032e56a86fa6c41b7c089784dde0c71d/sinks/dashboard/items/dashboard_item.py#L140)):*
> ```Python
>         self.corner_grabbed = False
> 
>     def isInCorner(self, pos):
> ```

personally I would make this a snake_case name but I think it doesn't matter since it's already really inconsistent due to the libraries used. I'm not sure if we have any specific guideline on this

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Like Patrick said, amazing work! Couple things:
- As mentioned above, can you render the square underneath the widget content?
- When the user brings their mouse over the square, can you make it so that the mouse pointer changes to an arrow (like if you hover over your browser window's corner)?
- Can you add the grabbable corners to all 4 corners of the widgets so it can be resized in any way?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-:-O028CK62cPK--DOFYLg:b-letczm)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/dashboard_item.py` line 5 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O027Uvj1ZCn2hX9r7ak:-O027Uvj1ZCn2hX9r7al:b-s2445y) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7b6d1053032e56a86fa6c41b7c089784dde0c71d/sinks/dashboard/items/dashboard_item.py#L5)):*
> ```Python
> from collections import OrderedDict
> from PySide6.QtGui import QPainter, QColor
> from PySide6.QtCore import QRect
> ```

Can you import these from `pyqtgraph` instead of `PySide6`?
___
*[`sinks/dashboard/items/dashboard_item.py` line 105 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O00bT8k5rGd3DHj5O8S:-O027amd67SZ7ZMhYWi4:b2nhtan) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7b6d1053032e56a86fa6c41b7c089784dde0c71d/sinks/dashboard/items/dashboard_item.py#L105)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I think this should be just a normal # comment
</blockquote></details>

Yup
___
*[`sinks/dashboard/items/dashboard_item.py` line 140 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O00bcS50FfwYM0LUyz4:-O0282201eSCNi6oWF1W:b8wtbl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7b6d1053032e56a86fa6c41b7c089784dde0c71d/sinks/dashboard/items/dashboard_item.py#L140)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

personally I would make this a snake_case name but I think it doesn't matter since it's already really inconsistent due to the libraries used. I'm not sure if we have any specific guideline on this
</blockquote></details>

Yeah... we don't really have a strict guideline on cases, this is fine

**Comment by patrick-gu** [comment]
Sorry I was unclear, I believe the square is indeed currently rendering under the content which I agree is the correct behavior

**Review by Darth-Raazi — COMMENTED** [review]
I was also unclear lol, I would like to not to see the square; it shouldn't show up visibly, only functionally

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-:-O02HmhtEb_rkwKaLbR1:bkv7hik)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, @saads312, and @zangjiucheng)

**Comment by zangjiucheng** [comment]
Thank you for your comments! I'll keep working on it and see what I can do. I agree with Ozayr's solution of hiding the squares. As for the scaling, I don't have a solution yet. Since we currently use the register as the decorators, I can't pass the scaling parameter from the dashboard class to dashboard_item. maybe configuring the JSON file will solve this problem, but I'll leave it for future improvements.

**Comment by patrick-gu** [comment]
if it's just that you need to pass some object from the dashboard to the items then you can see what I did here, basically adding a new argument to DashboardItem: https://github.com/waterloo-rocketry/omnibus/pull/239/commits/9c618aa69d912aef7c7977fa72c056c0def70618# might be more complicated than that though

**Comment by zangjiucheng** [comment]
Thank you @patrick-gu ! I will follow that, in the next post I will update that!  🙃

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @Lucifersan, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/dashboard_item.py` line 21 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O0_gxFKCQaB1QZ5u42F:-O0_gxFKCQaB1QZ5u42G:biulhay) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f8b7f24185b5886fa55c4133a80400672a6106e7/sinks/dashboard/items/dashboard_item.py#L21)):*
> ```Python
>     """
> 
>     """Whether the dashboard item is locked, which disables selection"""
> ```

What is this comment for?
___
*[`sinks/dashboard/items/dashboard_item.py` line 129 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O0_h3TU3zDzZ0W-4jAh:-O0_h3TU3zDzZ0W-4jAi:b-v5rupg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f8b7f24185b5886fa55c4133a80400672a6106e7/sinks/dashboard/items/dashboard_item.py#L129)):*
> ```Python
>         Resizes the widget while the mouse is being moved.
>         """
>         # self.corner_in = self.is_in_corner(event.pos())
> ```

Stale comment?
___
*[`sinks/dashboard/items/dashboard_item.py` line 134 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O0_iQoG3hziooDn5baY:-O0_iQoG3hziooDn5baZ:by82nj5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f8b7f24185b5886fa55c4133a80400672a6106e7/sinks/dashboard/items/dashboard_item.py#L134)):*
> ```Python
>             self.setCursor(Qt.SizeFDiagCursor)
>             self.corner_in = True
>             self.corner_index = self.index_corner(event.pos())
> ```

What does this function do and why are we calling it on every move event?

**Comment by patrick-gu** [comment]
I can also re-review if you're ready for that

**Comment by zangjiucheng** [comment]
Thanks! I think I should still improve on this. I did an update last week but unfortunately I need to fix some renderer bugs 🥲 . Sorry, I'm a bit busy with school this week, I'll finish it next week 👍. But I haven't figured out the parameter passing yet @patrick-gu, can you help me out please 😭. Thanks!

**Comment by patrick-gu** [comment]
@zangjiucheng I figured out how to use the coordinates correctly but I think there are some bugs still

**Comment by zangjiucheng** [comment]
Thank you so much @patrick-gu I confirmed your edit, it's amazing! I can use the correct scaling now! I will fix the rendering errors this week. I think I need to improve the MVC design, and there are some rendering errors that I'm still unsure of if they're coming from the base library or something wrong with my code! Thank you though!

**Comment by zangjiucheng** [comment]
@Darth-Raazi I double-checked my code, but I think mouseMoveEvent is the function I can't avoid. It's the only function I need to check if the mouse is moving to a corner. I could do the check every 10 frames and it would be smoother.

**Comment by zangjiucheng** [comment]
I fixed a bug that was causing the mouse to not render the correct shape because .index(True) was being called incorrectly by my logic. I apologize for this!

**Comment by zangjiucheng** [comment]
At the moment, the only problem is the plot drawing function for all the fakeni sources, which can cause the system to crash, and the high latency of the dashboard, which I will try to do some research to fix.

**Comment by zangjiucheng** [comment]
- fix the render bug 
- add comment to the code
- merge master branch to the update branch

**Review by patrick-gu — APPROVED** [review]
Amazing, works great for me!

This has come up in a lot of PRs I think, and there is nothing I think needs to be changed here, but @Darth-Raazi it is probably worth considering if we want to strictly follow docstring conventions: https://peps.python.org/pep-0257/

> Reviewed 1 of 3 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-:-O1-WpKL5NKGhlmOzFbf:bmdbwek)* status: all files reviewed, 4 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/dashboard_item.py` line 21 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O0_gxFKCQaB1QZ5u42F:-O1-W0NZBk0RwCWWfsKU:b-qv4ruy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f8b7f24185b5886fa55c4133a80400672a6106e7/sinks/dashboard/items/dashboard_item.py#L21)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

What is this comment for?
</blockquote></details>

removed I think
___
*[`sinks/dashboard/items/dashboard_item.py` line 129 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O0_h3TU3zDzZ0W-4jAh:-O1-WAP2ARFzfwFJWIi_:bbneorn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f8b7f24185b5886fa55c4133a80400672a6106e7/sinks/dashboard/items/dashboard_item.py#L129)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Stale comment?
</blockquote></details>

looks fixed
___
*[`sinks/dashboard/items/dashboard_item.py` line 152 at r6](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-O1-WK4rASmslnDJdpJf:-O1-WK4rASmslnDJdpJg:bfao4a0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/359f32421510073955bef94dc14ab3e42cf37cf8/sinks/dashboard/items/dashboard_item.py#L152)):*
> ```Python
>         Checks if the mouse is in the corner and updates the corner_index.
>         """
>         left_up_corner = pos.x() < self.corner_size and pos.y() < self.corner_size
> ```

Minor but I think these corners should be inclusive everywhere. so if you click exactly on the edge of the square it should be included

Also when you click

**Comment by zangjiucheng** [comment]
I'll fix that little problem with = as well, 
Also, I think we can open another PR for the pep-0257 format. if needed, I can modify all the work ..., but I think it's not a priority for now. (but later I agree that this is important)

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Really good work, just one problem: resizing should be disabled when the dashboard/item is locked

> Reviewed 1 of 3 files at r4, 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-:-O1547Ib-usH2t8MIyIv:b-abn9m9)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Lucifersan, @saads312, and @zangjiucheng)

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240#-:-O15CfhLCQGH9bsnLMBd:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Lucifersan, @saads312, and @zangjiucheng)

**Review by patrick-gu — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/240)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Lucifersan, @saads312, and @zangjiucheng)

**Pull request merged**
