### PR TITLE
Implements text console

### PR DESCRIPTION
**Pull request by jli35**
Takes inputs from console to determine which messages from which channels to print

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Overall looks great, just a bunch of small fixes.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-:-Mc0nXEHENNZOqarwjcV:btb0e47)* status: all files reviewed, 8 unresolved discussions (waiting on @Huan-YiShen, @jacobdeery, @jli35, @PCModeActivate, and @wendi-yu)

___
*[sinks/txtconsole/txtconsole.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0nsrTBQCdp0i89BVn:-Mc0nsrTBQCdp0i89BVo:bl2lus9) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L1)):*
> ```Python
> from omnibus import Receiver
> ```

By convention the file to run for a source/sink is always called `main.py`
___
*[sinks/txtconsole/txtconsole.py, line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0lxmn52ilp_b08EPN:-Mc0lxmn52ilp_b08EPO:b-iceigx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L3)):*
> ```Python
> from omnibus import Receiver
> 
> def print_console():
> ```

When splitting logic out into functions it's often better to use arguments rather than global variables, it makes unit testing and understanding/debugging easier. In this case `txt_filter` should be an argument.
___
*[sinks/txtconsole/txtconsole.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0mHUN35xpt2xPavhd:-Mc0mHUN35xpt2xPavhe:b-75fmv8) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L8)):*
> ```Python
>     while True:
>         msg = receiver.recv_message()
>         if msg.channel.lower() in txt_filter:
> ```

In general channels are case sensitive so we should probably maintain that sensitivity for consistency.
___
*[sinks/txtconsole/txtconsole.py, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0mOrn-gqyDB6XoAPr:-Mc0mOrn-gqyDB6XoAPs:b-o9f9fo) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L9)):*
> ```Python
>         msg = receiver.recv_message()
>         if msg.channel.lower() in txt_filter:
>             print(f"{msg.payload}\n")
> ```

In python you can `print(msg.payload)`
___
*[sinks/txtconsole/txtconsole.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0jl7JCtcqb-vtF8SW:-Mc0jl7K9l7SL_qKuTKr:bq3crw6) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L13)):*
> ```Python
> if __name__ == '__main__':
>     CHANNEL = ""  # all channels
>     SERVER = "tcp://localhost:5076"  # server
> ```

Please rebase off of master to use the new automatic server IP detection.
___
*[sinks/txtconsole/txtconsole.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0mge74mO0GKUViabj:-Mc0mge74mO0GKUViabk:bo5e7rt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L14)):*
> ```Python
>     CHANNEL = ""  # all channels
>     SERVER = "tcp://localhost:5076"  # server
>     txt_filter = list()
> ```

When I read `txt_filter` I think of a string, not a list. Perhaps `channels`?
___
*[sinks/txtconsole/txtconsole.py, line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0jwbFEsAzVnKUVbQJ:-Mc0jwbFEsAzVnKUVbQK:bon07wl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L18)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     num_types = int(input("Enter number of message types: "))
>     print("Enter the message types separated with new lines. ")
>     for i in range(num_types):
>         new = input("Enter: ")
> ```
</details>

I think that reading from command line arguments will have better ergonomics here, for example you could then use up arrow to recall the last command with all of its channels rather than relying on scrolling back and copy/paste.
___
*[sinks/txtconsole/txtconsole.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0mzqb3oWnX6hLrHcx:-Mc0mzqb3oWnX6hLrHcy:blk0wqe) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L19)):*
> ```Python
>     for i in range(num_types):
>         new = input("Enter: ")
>         txt_filter.append(new.lower())
> ```

See above comment about case sensitivity.

**Review by jli35 — COMMENTED** [review]
> Reviewed 13 of 13 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7)* status: all files reviewed, 6 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[sinks/txtconsole/txtconsole.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0nsrTBQCdp0i89BVn:-Mc6F6wlAEr-7nzFV-og:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L1)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

By convention the file to run for a source/sink is always called `main.py`
</blockquote></details>

Done.
___
*[sinks/txtconsole/txtconsole.py, line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0lxmn52ilp_b08EPN:-Mc6Eqef9UdjHEngnWA8:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L3)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

When splitting logic out into functions it's often better to use arguments rather than global variables, it makes unit testing and understanding/debugging easier. In this case `txt_filter` should be an argument.
</blockquote></details>

Done.
___
*[sinks/txtconsole/txtconsole.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0mHUN35xpt2xPavhd:-Mc6EzTH5MplJE8NZ1kv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L8)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

In general channels are case sensitive so we should probably maintain that sensitivity for consistency.
</blockquote></details>

Done.
___
*[sinks/txtconsole/txtconsole.py, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0mOrn-gqyDB6XoAPr:-Mc6F2eb9RJlqenUfk58:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L9)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

In python you can `print(msg.payload)`
</blockquote></details>

Done.
___
*[sinks/txtconsole/txtconsole.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0jl7JCtcqb-vtF8SW:-Mc6EpCy-NWkRGlan_7V:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L13)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Please rebase off of master to use the new automatic server IP detection.
</blockquote></details>

Done.
___
*[sinks/txtconsole/txtconsole.py, line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-Mc0jwbFEsAzVnKUVbQJ:-Mc6EpvnB2or439lm-ri:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/dc7630e56d02afd08dc152dfa26fc1a9944c6a17/sinks/txtconsole/txtconsole.py#L18)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

> ```
>     num_types = int(input("Enter number of message types: "))
>     print("Enter the message types separated with new lines. ")
>     for i in range(num_types):
>         new = input("Enter: ")
> ```
I think that reading from command line arguments will have better ergonomics here, for example you could then use up arrow to recall the last command with all of its channels rather than relying on scrolling back and copy/paste.
</blockquote></details>

Done.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking good!

> Reviewed 1 of 13 files at r2, 1 of 1 files at r3, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-:-McCJoXH1WYegSDndgt3:br2sbr6)* status: all files reviewed, 1 unresolved discussion (waiting on @Huan-YiShen, @jacobdeery, @jli35, @PCModeActivate, and @wendi-yu)

___
*[sinks/txtconsole/main.py, line 8 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-McCJ3hY9ovngwlpbYuD:-McCJ3hY9ovngwlpbYuE:b6m6meq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a0ff5736e95ec2ca08a9fa8e8add537c9596356b/sinks/txtconsole/main.py#L8)):*
> ```Python
>     receiver = Receiver(CHANNEL)
>     print('Cmd line arguments entered: ')
>     print(sys.argv)
> ```

`sys.argv[0]` is the file being run, you're interested in `sys.argv[1:]`.

**Review by jli35 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7)* status: all files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[sinks/txtconsole/main.py, line 8 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7#-McCJ3hY9ovngwlpbYuD:-McHLAuf9IJjdvv0jEfA:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a0ff5736e95ec2ca08a9fa8e8add537c9596356b/sinks/txtconsole/main.py#L8)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`sys.argv[0]` is the file being run, you're interested in `sys.argv[1:]`.
</blockquote></details>

Done.

**Review by BluCodeGH — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jacobdeery, @PCModeActivate, and @wendi-yu)

**Pull request merged**
