### PR TITLE
Add NI driver with backup logging

### PR DESCRIPTION
**Pull request by BluCodeGH**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12)

### CODE REVIEW

**Review by wendi-yu — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-:-MeYYPjhAnfsyKKcPfpg:bg7igkv)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[sources/ni/calibration.py, line 111 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-MeYXnf358qKtJ1hL0Po:-MeYXnf358qKtJ1hL0Pp:b7d1959) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/75a6b8e513d2ccb5fb014746d0bd83e4a51510bd/sources/ni/calibration.py#L111)):*
> ```Python
>         Apply each sensor's calibration to voltages from the NI box.
>         """
>         res = {}
> ```

You _can_ do dict comprehension if you want to, but understandable if you wanna keep it from getting too complicated

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[sources/ni/calibration.py, line 111 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-MeYXnf358qKtJ1hL0Po:-MeYYhMg70owsNfbZQ8e:b-buuv95) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/75a6b8e513d2ccb5fb014746d0bd83e4a51510bd/sources/ni/calibration.py#L111)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

You _can_ do dict comprehension if you want to, but understandable if you wanna keep it from getting too complicated
</blockquote></details>

Yeah I'd rather not do nested comprehensions lol.

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[sources/ni/calibration.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-Me_iqTEAGg7dMooGU0l:-Me_iqTEAGg7dMooGU0m:b-cyitqz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/75a6b8e513d2ccb5fb014746d0bd83e4a51510bd/sources/ni/calibration.py#L14)):*
> ```Python
>     DIFFERENTIAL = nidaqmx.constants.TerminalConfiguration.DIFFERENTIAL
> 
> class Calibration:
> ```

Please add at least some simple unit tests for the calibration classes
___
*[sources/ni/calibration.py, line 83 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-Me_ixMO7GyG7L4rltBj:-Me_ixMO7GyG7L4rltBk:b-1qaj3q) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/75a6b8e513d2ccb5fb014746d0bd83e4a51510bd/sources/ni/calibration.py#L83)):*
> ```
>                 print(f"Error: Duplicate sensors named {self.name}.")
>                 sys.exit(1)
> ```
Inside library code, prefer raising exceptions instead of calling `sys.exit` - allows the calling code to handle the error rather than forcing a process crash

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[sources/ni/calibration.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-Me_iqTEAGg7dMooGU0l:-MecT1QF6XUZwOLzhV0D:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/75a6b8e513d2ccb5fb014746d0bd83e4a51510bd/sources/ni/calibration.py#L14)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Please add at least some simple unit tests for the calibration classes
</blockquote></details>

Done
___
*[sources/ni/calibration.py, line 83 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-Me_ixMO7GyG7L4rltBj:-MecT35n3GRZe6ztGJUL:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/75a6b8e513d2ccb5fb014746d0bd83e4a51510bd/sources/ni/calibration.py#L83)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>                 print(f"Error: Duplicate sensors named {self.name}.")
>                 sys.exit(1)
> ```
Inside library code, prefer raising exceptions instead of calling `sys.exit` - allows the calling code to handle the error rather than forcing a process crash
</blockquote></details>

Done

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[sources/ni/main.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-Meey4815ZUSSmw36gpi:-Meey4815ZUSSmw36gpj:b-ax97tj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/15b321fd6fe7f731a8b213284a95ffca7c318a50/sources/ni/main.py#L15)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> try:
>     config.setup() # initialize the sensors
> except KeyError as e:
>     print(f"Error: {''.join(e.args)}.")
>     sys.exit(1)
> ```
</details>

You don't _really_ need to wrap this in a `try`, you could just let the `KeyError` go unhandled, which will have the same effect, but up to you
___
*[sources/ni/main.py, line 20 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-MeeyapD8MZMK7kD2Tux:-MeeyapD8MZMK7kD2Tuy:b-w7ise8) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/15b321fd6fe7f731a8b213284a95ffca7c318a50/sources/ni/main.py#L20)):*
> ```
> if len(system.devices) == 0:
> ```
Is it always the case that if a device is connected, it will be detected instantly?

**Review by BluCodeGH — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 4 of 4 files at r2.
> Dismissed @jacobdeery from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[sources/ni/main.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-Meey4815ZUSSmw36gpi:-MemnA-VCLDIJTYn2NP2:bs1528f) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/15b321fd6fe7f731a8b213284a95ffca7c318a50/sources/ni/main.py#L15)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> try:
>     config.setup() # initialize the sensors
> except KeyError as e:
>     print(f"Error: {''.join(e.args)}.")
>     sys.exit(1)
> ```
You don't _really_ need to wrap this in a `try`, you could just let the `KeyError` go unhandled, which will have the same effect, but up to you
</blockquote></details>

Yeah this is a just bit prettier.
___
*[sources/ni/main.py, line 20 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/12#-MeeyapD8MZMK7kD2Tux:-MemnLWW9wwcE59LPIaz:b-8562cz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/15b321fd6fe7f731a8b213284a95ffca7c318a50/sources/ni/main.py#L20)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> if len(system.devices) == 0:
> ```
Is it always the case that if a device is connected, it will be detected instantly?
</blockquote></details>

I'm not sure if it will be instantly detected but also even if it's detected it still takes some time to get set up, and if we try to start reading data before then everything crashes. Even better there's no way to tell when it's set up within the driver that I could find, so proper support for the edge case of starting this just as the NI device gets plugged in is nontrivial. Something to come back to in a future PR perhaps.

**Pull request merged**
