### PR TITLE
WDR fixes

### PR DESCRIPTION
**Pull request by BluCodeGH**
Sorry for the mishmash of changes, here is a summary of everything that's changed:

- Removed the old CAN message table
- Moved the ParameterTree into the dashitem to fix weird deletion stuffs (gets rid of "internal C++ object deleted")
- Refactored how we handle dashitem resizes. I'm not supper happy with hardcoding a callback into every item but it works well.
- Added dynamic text widget that shows a single data point as a number / string
- Added offset fields to plot and dynamic text to account for zero points
- Added periodic sender item that sends actuator commands repeatedly so the rocket doesn't go to safe state
- Redid dashboard CAN parsing to pull out individual fields
- Updated fake_parsley to be more representative
- Added new rocket load cell to NI config
- Improved parsley source performance and made it send messages spaced apart to fix dropping messages
- Added print statement with timestamp to replay log

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110)

### CODE REVIEW

**Review by itslinotlie — COMMENTED** [review]
I can go and fix most of these changes, @AvKat would you mind looking into the QParameterTree/QSplitter width 'issue'?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-:-NVkvD-F8Y7ksYZfl-fJ:b70gdsc)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @AvKat, @BluCodeGH, and @KavinSatheeskumar)

___
*[`sinks/dashboard/dashboard.py` line 18 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkVGrvDCXIXBMwm0F5:-NVkVGrvDCXIXBMwm0F6:bjllkdz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/dashboard.py#L18)):*
> ```Python
>     QGraphicsRectItem,
>     QFileDialog,
>     QHeaderView,
> ```

```QHeaderView```

unused import
___
*[`sinks/dashboard/dashboard.py` line 222 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkqwKS9GVuSh8Latus:-NVkqwKS9GVuSh8Latut:b4q39t0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/dashboard.py#L222)):*
> ```Python
>         # subtract 100 for some padding, these sizes are relative
>         total_width = self.splitter.size().width() - 100
>         tree_width = item.parameter_tree.sizeHint().width()
> ```

An 'issue' with our current QSplitter/Parameter Tree approach is that we never store the actual width of the dashboard item's parameter tree. This can easily be seen with the image dash item if we were to increase the width of the ParameterTree and then focus out and back in (the relative column widths are saved though). I think the fix would be something along the lines of adding an event handler on our QSplitter for whenever the width is changed and updating that dashboard item's parameter tree width.



___
*[`sinks/dashboard/dashboard.py` line 326 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVku5gJ5pGgxZl6TnBR:-NVku5gKCdGYO1uZKOeW:b-wvabf2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/dashboard.py#L326)):*
> ```Python
>             for item_type in registry.get_items():
>                 if widget["class"] == item_type.get_name():
>                     #try:
> ```

undeleted commented code / i don't understand this part of the codebase but somethings not right xd
___
*[`sinks/dashboard/items/dashboard_item.py` line 40 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkTuPD9Vj6Z8JkovL-:-NVkTuPD9Vj6Z8JkovL0:b-j11s19) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/items/dashboard_item.py#L40)):*
> ```Python
> 
>         self.parameter_tree = ParameterTree(showHeader=True)
>         self.parameter_tree.setParameters(self.parameters, showTop=False)
> ```

```self.parameter_tree.header().setSectionResizeMode(QHeaderView.Interactive)```
``self.parameter_tree.header().setMinimumSectionSize(100)```

We need to ensure that the header width can be manually adjusted, and it would be nice if the default header width was a big larger so that most text can be seen without having to manually edit the columns.
___
*[`sinks/dashboard/items/dynamic_text.py` line 71 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkhax97ZoydYk8lUe_:-NVkhaxA1nDHXw8TgXkC:bsiwgxy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/items/dynamic_text.py#L71)):*
> ```Python
> 
>     def on_font_change(self, _, fsize):
>         self.widget.setStyleSheet("font-size: {}px".format(fsize))
> ```

```self.widget.setStyleSheet(f"font-size: {fsize}px")```

f-string
___
*[`sinks/dashboard/items/image_dash_item.py` line 41 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkcknW3pyq9Cj15JQp:-NVkcknW3pyq9Cj15JQq:bwt6oqm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c776024b65bde9a6d784d5eadeb3e9fe0031f846/sinks/dashboard/items/image_dash_item.py#L41)):*
> ```Python
>             ) - self.offset  # subtracting here to account
>             height = self.parameters.child("height").value() - self.offset  # for the new "border"
>             self.widget.setPixmap(QPixmap(self.image_path).scaled(width, height))
> ```

We can replace the contents of this if statement with a ```self.on_file_change()``` call. I definitely think moving the 'explanation' over to the function would make a lot more sense too.
___
*[`sinks/dashboard/items/image_dash_item.py` line 48 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkXViQ40zX6cnxBNF6:-NVkXViR1E8E6RGt6DFI:b-ff4unf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/items/image_dash_item.py#L48)):*
> ```Python
> 
>     def add_parameters(self):
>         file_param = FileParameter(name="file", value="")
> ```

```file_param = FileParameter(name="file", value="", nameFilter='*.jpg;*.png;*.svg')```

We should consider filtering the files that can be selected (full list of supported image formats can be found here: https://doc.qt.io/qtforpython-5/PySide2/QtGui/QImageReader.html#PySide2.QtGui.PySide2.QtGui.QImageReader.supportedImageFormats)
___
*[`sinks/dashboard/items/text_dash_item.py` line 36 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkgv6EDCMOEXK0yRNa:-NVkgv6EDCMOEXK0yRNb:b-4gvp42) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/items/text_dash_item.py#L36)):*
> ```Python
>     def setFontSize(self, fsize):
>         self.fsize = fsize
>         self.widget.setStyleSheet("font-size: {}px".format(self.fsize))
> ```

```self.widget.setStyleSheet(f"font-size: {self.fsize}px")```

f-string
___
*[`sources/parsley/main.py` line 72 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkupoX0F_2Mf2k4qQ_:-NVkupoX0F_2Mf2k4qQa:b-m05umg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sources/parsley/main.py#L72)):*
> ```Python
>                 sender.send(CHANNEL, parsed_data)  # send the CAN message over the channel
>         except Exception:
>             #print(line)
> ```

I need to go figure out why we're printing an empty line (its not the empty string, i think it might be the null character), but we should definitely keep the print statement (ie for when there's a information mismatch between canlib and parsley)

**Review by itslinotlie — APPROVED** [review]
If it worked in wdr last time, it'll work again for this wdr (:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-:-NVog1vQ-WKEKCdmlM76:bftewfv)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @AvKat, @BluCodeGH, and @KavinSatheeskumar)

___
*[`sinks/dashboard/dashboard.py` line 222 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVkqwKS9GVuSh8Latus:-NVofr4d3-Q7iRH4b9Yb:b-hcceqa) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/dashboard.py#L222)):*
<details><summary><i>Previously, itslinotlie (Michael Li) wrote…</i></summary><blockquote>

An 'issue' with our current QSplitter/Parameter Tree approach is that we never store the actual width of the dashboard item's parameter tree. This can easily be seen with the image dash item if we were to increase the width of the ParameterTree and then focus out and back in (the relative column widths are saved though). I think the fix would be something along the lines of adding an event handler on our QSplitter for whenever the width is changed and updating that dashboard item's parameter tree width.





</blockquote></details>

This isn't important to wdr, i'll just add this to the bucket list of software wishes

**Review by AvKat — APPROVED** [review]
I'm still not fully familiar with the parsers so I just lightly read those over but everything else seems fine to me.
I will work on the QParameterTree thing and I can also take any other tasks if you want. 
Thanks for making me a reviewer.

> Reviewed 3 of 14 files at r2, 4 of 8 files at r5, 1 of 4 files at r7, 1 of 5 files at r8, 9 of 12 files at r9, 3 of 3 files at r10, 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-:-NVw5htm7zrqyw7jIHGC:b6v4i7u)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/dashboard/dashboard.py` line 358 at r11](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVw1gWG9OH7ezOgC_CS:-NVw1gWG9OH7ezOgC_CT:b-hf8ykk) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a007381f2ef56c328f657702c08171645e4b5aad/sinks/dashboard/dashboard.py#L358)):*
> ```Python
>                     self.add(item_type(self.on_item_resize, widget["params"]), widget["pos"])
>                     # except Exception as e:
>                     #    print(e)
> ```

i don't see why the change was made



_Code quote:_
```Python
                    # try:
                    self.add(item_type(self.on_item_resize, widget["params"]), widget["pos"])
                    # except Exception as e:
                    #    print(e)
```
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 20 at r11](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVw3dn6-i0DIselD0SS:-NVw3dn6-i0DIselD0ST:b-15u3x2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a007381f2ef56c328f657702c08171645e4b5aad/sinks/dashboard/items/periodic_can_sender.py#L20)):*
> ```Python
>         super().__init__(*args)
> 
>         self.parameters.param('period').setValue(0)
> ```

this seems redundant as the default value is already being set in `add_parameters`

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110)* status: all files reviewed, 3 unresolved discussions (waiting on @AvKat and @KavinSatheeskumar)

___
*[`sinks/dashboard/dashboard.py` line 326 at r7](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVku5gJ5pGgxZl6TnBR:-NW0aBhUDd8tJK9-mMEM:b-1vidyc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e9d454cd63dd350c64a57db40201c0cfc78b5085/sinks/dashboard/dashboard.py#L326)):*
<details><summary><i>Previously, itslinotlie (Michael Li) wrote…</i></summary><blockquote>

undeleted commented code / i don't understand this part of the codebase but somethings not right xd
</blockquote></details>

Yeah this should get deleted
___
*[`sinks/dashboard/dashboard.py` line 358 at r11](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVw1gWG9OH7ezOgC_CS:-NW0aFI5Ck_GCQiHiW9E:bq91w1e) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a007381f2ef56c328f657702c08171645e4b5aad/sinks/dashboard/dashboard.py#L358)):*
<details><summary><i>Previously, AvKat (Avish Kathpal) wrote…</i></summary><blockquote>

i don't see why the change was made
</blockquote></details>

The commented out stuff should be removed.
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 20 at r11](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110#-NVw3dn6-i0DIselD0SS:-NW0aL5_2pcv1-e7v8Oa:bmmyztv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a007381f2ef56c328f657702c08171645e4b5aad/sinks/dashboard/items/periodic_can_sender.py#L20)):*
<details><summary><i>Previously, AvKat (Avish Kathpal) wrote…</i></summary><blockquote>

this seems redundant as the default value is already being set in `add_parameters`
</blockquote></details>

This re-sets the value to 0 on dashboard startup so we don't immediately start sending CAN messages.

**Review by Darth-Raazi — APPROVED** [review]
> Reviewed 2 of 14 files at r2, 1 of 8 files at r5, 1 of 4 files at r7, 1 of 5 files at r8, 6 of 12 files at r9, 1 of 5 files at r11, 1 of 1 files at r14, 22 of 23 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/110)* status: all files reviewed, 3 unresolved discussions (waiting on @AvKat, @BluCodeGH, and @KavinSatheeskumar)

**Pull request merged**
