### PR TITLE
Update new post processing pandas

### PR DESCRIPTION
**Pull request by SuperZooper3**
A quick update to new post-processing script to use pandas data frames like Kavin suggested. Tested exporting and previewing data, and want a sanity check for the use of the dataframe being correct, and working on your machines.

Just merging back up to my own "master" data processing branch.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214)

### CODE REVIEW

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @SuperZooper3)

___
*[`tools/data_processing/data_saving.py` line 12 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-NsZ3n-E626G2r4Y-na-:-NsZ3n-E626G2r4Y-na0:b9rvea8) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8679987441ed33f258d30986888bc7eafa13272f/tools/data_processing/data_saving.py#L12)):*
> ```Python
>     formatted_can_size = "N/A"
>     with open(file_path, "w") as outfile:
>         data_df.to_csv(outfile, index=False)
> ```

You don't need to open th efile, you can just do `data_df.to_csv(file_path)`
___
*[`tools/data_processing/helpers.py` line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-NsZ44Bg7FXR3tkCqU-W:-NsZ44Bg7FXR3tkCqU-X:b45h) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8679987441ed33f258d30986888bc7eafa13272f/tools/data_processing/helpers.py#L8)):*
> ```Python
>     
>     # we need logic to handle the case where one of the data sources is empty, becuase a recording might only have CAN data
>     if data1 is not None and data2 is not None:
> ```





_Code snippet:_
```Python
time_offset = min(data1["timestamp"].min() if data1 else np.inf, data2["timestamp"].min() if data2 else np.inf)

if time_offset == np.inf:
    raise ValueError("...")
```
___
*[`tools/data_processing/interractions.py` line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-NsZ5iHq-y4E6Tm0L7I_:-NsZ5iHq-y4E6Tm0L7Ia:boglg44) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8679987441ed33f258d30986888bc7eafa13272f/tools/data_processing/interractions.py#L17)):*
> ```Python
>     
>     print("Parsing file...")
> ```

This is a vague comment that I will make better later, but it dosen't feel like you are actually using any of the utilities that pandas provides to make the code shorter/easier to read. Alot of what you are doing below are very simple operations with pandas (IE filtering columns based on the mode, etc.) I will come back at a later point and try and re-write a bunch of it into short, 2/3 line functions so you get the idea of what I am talking about and can restructure the code accordingly.

But yeah, right now, it just feels like dataframes were added to make me happy lol

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
See above

> Reviewed 6 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-:-NtCXozSCaDcSt18gcPM:b-34vmyd)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @SuperZooper3)

___
*[`tools/data_processing/interractions.py` line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-NsZ5iHq-y4E6Tm0L7I_:-NtCXClu8epGOQ0FHWOY:b-cpq6sq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8679987441ed33f258d30986888bc7eafa13272f/tools/data_processing/interractions.py#L17)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

This is a vague comment that I will make better later, but it dosen't feel like you are actually using any of the utilities that pandas provides to make the code shorter/easier to read. Alot of what you are doing below are very simple operations with pandas (IE filtering columns based on the mode, etc.) I will come back at a later point and try and re-write a bunch of it into short, 2/3 line functions so you get the idea of what I am talking about and can restructure the code accordingly.

But yeah, right now, it just feels like dataframes were added to make me happy lol
</blockquote></details>

Seems like Kavin has a vision for this code that hasn't been fulfilled yet, so I won't approve this yet. I agree that if we can use more pandas features to shorten the code, that would be great.

**Review by KavinSatheeskumar — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214)* status: all files reviewed, 4 unresolved discussions (waiting on @BluCodeGH and @SuperZooper3)

___
*[`tools/data_processing/helpers.py` line 17 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-NtHxpnp96DLJfsHYWXB:-NtHxpnp96DLJfsHYWXC:b1m5k6e) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cb1054dd6878d89ee3464a9c28c20352bff18b00/tools/data_processing/helpers.py#L17)):*
> ```Python
>         raise ValueError("Both data sources are empty, can't offset timestamps.")
> 
>     if data1 is not None:
> ```

is not None isn't necessary, you can just do



_Code snippet:_
```Python
if data1:
    ...
```
___
*[`tools/data_processing/helpers.py` line 25 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-NtHy1DE9SjLNlaFmXXx:-NtHy1DE9SjLNlaFmXXy:b-q5fr8x) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cb1054dd6878d89ee3464a9c28c20352bff18b00/tools/data_processing/helpers.py#L25)):*
> ```Python
> 
> 
> def filter_timestamps(data: Union[pd.DataFrame, None], start: float, stop: float):
> ```

Totally your call, but I am personally a fan of the "Optional" type hint

On that



_Code snippet:_
```Python
def filter_timestamp(data: Optional[pd.DataFrame]):
```

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/214#-:-NyCirbI0uxqcpdKHNsv:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @SuperZooper3)

**Pull request merged**
