### PR TITLE
made label to the left of numerical readout, allowed font resizing

### PR DESCRIPTION
**Pull request by xinhuey**
## Description
Redesigning Standard Display Item 

Changes made:
1. Label is not positioned to the left of the numerical readout. 
2. Label and Numerical Readout are in the same font size.
3. Text size is made customizable, range: (10, 30)

N/A

## Developer Testing

Here's what I did to test my changes:

1. Run python launcher.py
2. Select "Add Item" > "Standard Display Item"

## Reviewer Testing

Here's what you should do to quickly validate my changes:

1. You will see that the label is positioned to the left of the numerical readout.
2. You can change the font size in the parameters section 
3. The sparkline plot is togglable.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/258)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work! Font size changing works well. 2 things:
- Can you make it so that when the sparkling is hidden, the widget shrinks vertically to just the size occupied by the label and readout? Then when the sparkling is re-shown, it expands vertically back to the original size
- There seems to be a minimum size for the sparkline so that when it's shown, you can't make the widgets as small as you want. See screenshot below



> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/258#-:-O1Ub22T8kPFtBHipRHj:bcgrcks)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

**Comment by Darth-Raazi** [comment]
@BluCodeGH @Lucifersan is the default font size of 25 good, or should it be 10?

**Review by patrick-gu — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/258)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Comment by xinhuey** [comment]
Hey, I made the change- the widget now resizes vertically whenever the sparkline plot is hidden/shown. As for the minimum size of the sparkline plot, I think it's to ensure that the plot can be plotted.

**Review by Darth-Raazi — APPROVED** [review]
Great work! I pushed one small resizing change
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/258#-:-O1e0CuRBT0Uv7QOHka9:b-e7uzzw)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Comment by BluCodeGH** [comment]
When the sparkline is turned off the number appears below the label? Also why are there still 6 significant digits?
image

**Review by Darth-Raazi — COMMENTED** [review]
@BluCodeGH please git pull, I fixed the value below label issue last night. Also just added custom decimal value selection with default set to 2. I tried removing the plot minimum size and it still won't let me make the sparkline smaller, I'm not sure what the issue is. Let's merge this and investigate that later

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/258#-:-O1h_tZE5fiZPrcCOGl_:bdy0raa)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Review by BluCodeGH — APPROVED** [review]

**Pull request merged**
