### PR TITLE
Omnibus Launcher GUI and CLI

### PR DESCRIPTION
**Pull request by wxp02**
## Description
Implemented a simple PyQT GUI and CLI for the launcher.

This PR closes issue #139 

## Developer Testing

- Ran `python launcher.py`, GUI popped up in new window and all launcher functionalities worked as expected
- Ran `python launcher.py -- text`, CLI showed up in terminal and all launcher functionalities worked as expected

## Reviewer Testing

- Run `python launcher.py` to see GUI
- Run `python launcher.py --text` to see CLI

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work with this PR Wenxu, couple changes and you should be good to go!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-:-NjroP4y6mSYfx4UXqMx:bz0semq)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @QuantumManiac, @shirleyfyx, @wxp02, and @xinhuey)

___
*[`launcher.py` line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njrkk-E8r87ZVIlCvgk:-Njrkk-E8r87ZVIlCvgl:b3zsnau) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L43)):*
> ```Python
>             print(f"{module.capitalize()}:")
>             for i, item in enumerate(modules[module]):
>                 print(f"\t{i+1}. {item.capitalize()}")
> ```

The "remove dot files" section should be its own method that both launchers call. Currently dot files are present in the selection list of GUILauncher
___
*[`launcher.py` line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njrl4Xb-UXWILDSKUhD:-Njrl4Xb-UXWILDSKUhE:buiygta) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L47)):*
> ```Python
>         # Construct CLI commands to start Omnibus
>         self.source_selection = input(f"\nPlease enter your Source choice [1-{len(modules['sources'])}]: ")
>         self.sink_selection = input(f"Please enter your Sink choice [1-{len(modules['sinks'])}]: ")
> ```

See related comments below, you should subtract 1 from both of these here
___
*[`launcher.py` line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NjrlGKvEXg4yGueAXtV:-NjrlGKvEXg4yGueAXtW:b-pvstir) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L50)):*
> ```Python
>         self.omnibus = [python_executable, "-m", "omnibus"]
>         self.source = [python_executable, f"sources/{modules['sources'][int(self.source_selection) - 1]}/main.py"]
>         self.sink = [python_executable, f"sinks/{modules['sinks'][int(self.sink_selection) - 1]}/main.py"]
> ```

This is bad design because we are adding and subtracting 1 in a lot of different places. Subtractions should happen at the time of variable assignment (see related comment above) and not while using them
___
*[`launcher.py` line 74 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njrlft20Pb9N27IuFyp:-Njrlft20Pb9N27IuFyq:bd4f9a7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L74)):*
> ```Python
>         self.logger = Logger()
>         self.logger.add_logger(f"sources/{modules['sources'][int(self.source_selection) - 1]}")
>         self.logger.add_logger(f"sinks/{modules['sinks'][int(self.sink_selection) - 1]}")
> ```

See related comments above, no subtraction should be happening here
___
*[`launcher.py` line 99 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njrm6zl7jp9B5sr28u0:-Njrm6zl7jp9B5sr28u1:bds110s) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L99)):*
> ```Python
>                 # Log outputs
>                 self.logger.log_output(process, output)
>                 print(output)
> ```

Output should not be printed because we are logging
___
*[`launcher.py` line 104 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njrm9oMCuOiGi5_ry-O:-Njrm9oMCuOiGi5_ry-P:bcbo1ah) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L104)):*
> ```Python
>                 if err and "KeyboardInterrupt" not in err:
>                     self.logger.log_error(process, err)
>                     print(err)
> ```

See above, same with error
___
*[`launcher.py` line 118 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NjroGe05SCECAKiohEK:-NjroGe05SCECAKiohEL:b-wfur25) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L118)):*
> ```Python
>     def __init__(self):
>         super().__init__()
>         self.commands = []
> ```

This should be in the `__init__()` of Launcher not GUILauncher
___
*[`launcher.py` line 171 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NjrmUSjDgH_UA4bszGR:-NjrmUSjDgH_UA4bszGS:b1vs8fl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L171)):*
> ```Python
>         # Add one to indexes as they will be subtracted by 1 each at Launcher methods
>         self.source_selection = modules['sources'].index(self.source_dropdown.currentText()) + 1
>         self.sink_selection = modules['sinks'].index(self.sink_dropdown.currentText()) + 1
> ```

See related comments above, no addition should be happening here
___
*[`launcher.py` line 175 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NjrmdCbAC6L7Abr5i2J:-NjrmdCbAC6L7Abr5i2K:b-oy81yt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L175)):*
> ```Python
>         self.omnibus = ["python", "-m", "omnibus"]
>         self.source = ["python", f"sources/{self.source_dropdown.currentText()}/main.py"]
>         self.sink = ["python", f"sinks/{self.sink_dropdown.currentText()}/main.py"]
> ```

Please add failure case handling, what if the user closes the pop-up without pressing ok?

**Review by SuperZooper3 — APPROVED** [review]
Great PR, a very nice GUI launcher and modularization of the launcher. Still a few minor changes to do, but overall good job!

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-:-NjulpPxB6QOVWSGTmQg:bfzp0ka)* status: all files reviewed, 11 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, @QuantumManiac, @shirleyfyx, @wxp02, and @xinhuey)

___
*[`launcher.py` line 118 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NjroGe05SCECAKiohEK:-NjukEO75kSVcYHKByl-:b-6h9m7e) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L118)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

This should be in the `__init__()` of Launcher not GUILauncher
</blockquote></details>

If this is referring to the below code about the geometry and the setup of the window, then I disagree because this code is directly relevant to the GUI so it's a good idea to break it off from the main functioning of the Launcher. 

If not, this comment is unclear, should the `super().__init__()` be in the Launcher? I'm pretty sure here this is used to call the Launcher from the GUILauncher, and then the Launcher itself also calls up.
___
*[`launcher.py` line 86 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njuk3mf8otSS7Hke_Fw:-Njuk3mf8otSS7Hke_Fx:bt3tpzc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5c6a11e47a1931c9a943f2e1ea2562b8ba3dfb1c/launcher.py#L86)):*
> ```Python
>                 for process in self.processes:
>                     if process.poll() != None:
>                         raise Finished
> ```

BTW If I understand correctly, this code means that if one sub-process closes, it forces all the other ones opened by the launcher to also close. Is this intended behavior, or are there maybe scenarios where we would want to close one element but not both? 

This could maybe be addressed (in a future PR) by keeping the launcher window alive with status indicators for the different sub-processes and the ability to kill them off 1-by-1?



_Code quote:_
```Python
                for process in self.processes:
                    if process.poll() != None:
                        raise Finished
```
___
*[`launcher.py` line 157 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njujccs8BqGUHhPU8Uy:-Njujccs8BqGUHhPU8Uz:bbdxjfu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5c6a11e47a1931c9a943f2e1ea2562b8ba3dfb1c/launcher.py#L157)):*
> ```Python
> 
>         # Enter selections button
>         self.button_box = QDialogButtonBox(QDialogButtonBox.StandardButton.Cancel | QDialogButtonBox.StandardButton.Ok)
> ```

BTW The cancel button currently doesn't do anything. Maybe change it to a close button and have it gracefully close the GUI?

**Review by Darth-Raazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173)* status: all files reviewed, 11 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @QuantumManiac, @shirleyfyx, @SuperZooper3, @wxp02, and @xinhuey)

___
*[`launcher.py` line 118 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NjroGe05SCECAKiohEK:-NjyP09m1slmyYvaxinR:b-wowep1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/715fbb434d5b4a2bf2c9f34dc1e9720413e1176e/launcher.py#L118)):*
<details><summary><i>Previously, SuperZooper3 (SuperZooper3) wrote…</i></summary><blockquote>

If this is referring to the below code about the geometry and the setup of the window, then I disagree because this code is directly relevant to the GUI so it's a good idea to break it off from the main functioning of the Launcher. 

If not, this comment is unclear, should the `super().__init__()` be in the Launcher? I'm pretty sure here this is used to call the Launcher from the GUILauncher, and then the Launcher itself also calls up.
</blockquote></details>

This was referring to another line that Wenxu already moved but forgot to resolve the comment lol
___
*[`launcher.py` line 86 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njuk3mf8otSS7Hke_Fw:-NjyOr0l7TRWCDmApmco:b-bn3d44) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5c6a11e47a1931c9a943f2e1ea2562b8ba3dfb1c/launcher.py#L86)):*
<details><summary><i>Previously, SuperZooper3 (SuperZooper3) wrote…</i></summary><blockquote>

BTW If I understand correctly, this code means that if one sub-process closes, it forces all the other ones opened by the launcher to also close. Is this intended behavior, or are there maybe scenarios where we would want to close one element but not both? 

This could maybe be addressed (in a future PR) by keeping the launcher window alive with status indicators for the different sub-processes and the ability to kill them off 1-by-1?
</blockquote></details>

This is intended behaviour, we don't want selective killing for now
___
*[`launcher.py` line 157 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-Njujccs8BqGUHhPU8Uy:-NjyPDYk5DKsFk5etdTF:b-195ao4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5c6a11e47a1931c9a943f2e1ea2562b8ba3dfb1c/launcher.py#L157)):*
<details><summary><i>Previously, SuperZooper3 (SuperZooper3) wrote…</i></summary><blockquote>

BTW The cancel button currently doesn't do anything. Maybe change it to a close button and have it gracefully close the GUI?
</blockquote></details>

Yes this is being worked on

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work Wenxu, I think after addressing these we should be ready to merge!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-:-NkC8wNBDvRYUGDW7mYc:b8qd5kr)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @QuantumManiac, @shirleyfyx, @SuperZooper3, @wxp02, and @xinhuey)

___
*[`launcher.py` line 21 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NkC6nJS8AHVBQmjsfa7:-NkC6nJS8AHVBQmjsfa8:b6rxba) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c682c11d2bf1f5fc0912a5cba7e18013ba968e20/launcher.py#L21)):*
> ```Python
> 
> # Parse folders for sources and sinks
> modules = {"sources" : os.listdir('sources'), "sinks" : os.listdir('sinks')}
> ```

This should be `self.modules` inside `Launcher`'s `init` function and every reference to it needs to be changed to `self.modules`
___
*[`launcher.py` line 43 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NkC7k8BDXWk5PgkcKf4:-NkC7k8BDXWk5PgkcKf5:b-49oo3i) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c682c11d2bf1f5fc0912a5cba7e18013ba968e20/launcher.py#L43)):*
> ```Python
>             print(f"{module.capitalize()}:")
>             for i, item in enumerate(modules[module]):
>                 print(f"\t{i}. {item.capitalize()}")
> ```

Sorry, I think it would actually be better to not have it be it's own method, but rather the code here should be in `Launcher`'s `init` after initializing `self.modules`. This way it'll still get called by both launchers
___
*[`launcher.py` line 49 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NkC7XIl8jaCCw8puXHt:-NkC7XIl8jaCCw8puXHu:bb10jxp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c682c11d2bf1f5fc0912a5cba7e18013ba968e20/launcher.py#L49)):*
> ```Python
>         # Construct CLI commands to start Omnibus
>         self.source_selection = input(f"\nPlease enter your Source choice [0-{len(modules['sources']) - 1}]: ")
>         self.sink_selection = input(f"Please enter your Sink choice [0-{len(modules['sinks']) - 1}]: ")
> ```

Subtraction needs to happen outside of `input` (we are taking the user's choice and subtracting 1, not subtracting 1 from the number the user sees)
___
*[`launcher.py` line 151 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NkC8gBQ6q1hnvT78evt:-NkC8gBQ6q1hnvT78evu:b-b8u8cf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c682c11d2bf1f5fc0912a5cba7e18013ba968e20/launcher.py#L151)):*
> ```Python
>         # Create a dropdown for sink
>         self.sink_dropdown = QComboBox(self)
>         self.sink_dropdown.setGeometry(90, 92, 150, 20)
> ```

I think some geometry is a bit too small because the select dropdowns are cut off from the top. See example:

___
*[`launcher.py` line 160 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NkC80gvB9buz_P9epTd:-NkC80gvB9buz_P9epTe:b-o29uku) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c682c11d2bf1f5fc0912a5cba7e18013ba968e20/launcher.py#L160)):*
> ```Python
>         self.button_box = QDialogButtonBox(QDialogButtonBox.StandardButton.Cancel | QDialogButtonBox.StandardButton.Ok)
>         self.button_box.accepted.connect(self.construct_commands)
>         self.button_box.rejected.connect(self.cancel)
> ```

No need for a new `cancel` method, you can just call `self.close`
___
*[`launcher.py` line 184 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NkC87qU99r0KBIk2cW4:-NkC87qU99r0KBIk2cW5:b9hovb7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c682c11d2bf1f5fc0912a5cba7e18013ba968e20/launcher.py#L184)):*
> ```Python
> 
>     def cancel(self):
>         self.close()
> ```

See above comment about cancel
___
*[`launcher.py` line 203 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-NkC8JF_-IdJX2Lz1yjR:-NkC8JF_-IdJX2Lz1yjS:btl62ie) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/c682c11d2bf1f5fc0912a5cba7e18013ba968e20/launcher.py#L203)):*
> ```Python
>         print("Running in text mode")
>         launcher = Launcher()
>         launcher.remove_dot_files()
> ```

Once this method gets removed, you can delete this line as well

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/173#-:-NkCQHCh7ksYHtXdQxM_:bnfp4nl)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @QuantumManiac, @shirleyfyx, @SuperZooper3, @wxp02, and @xinhuey)

**Pull request merged**
