### PR TITLE
Add `sources/rlcs` type hints

### LINKED ISSUE #151: Type Hint RLCS
See #145 

This issue is for `sources/rlcs`

### PR DESCRIPTION
**Pull request by patrick-gu**
## Description
Added type hints to `sources/rlcs`.

I used the `dict` type, which is not the most precise type possible, but it is what parsley returns. If there is a more accurate way to do this, let me know.

This PR closes #151.

## Developer Testing

Here's what I did to test my changes:

- N/A, no semantic changes

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Check that the type hints make sense

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Good work, couple small things

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-:-NnHOFInDxMPHMQtX384:b6f9m4b)* status: all files reviewed, 4 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sources/rlcs/commander.py` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHMTKp0v_wdiclx0Jx:-NnHMTKp0v_wdiclx0Jy:bxoxkcd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/commander.py#L22)):*
> ```Python
> 
> 
> def command(state: dict):
> ```

Please add what types the `dict` is made of (i.e. `str` to `int` or whatever it is). I'm not sure what the proper syntax is for that so you'll have to look it up
___
*[`sources/rlcs/rlcs.py` line 34 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHNW-k0VRcpFvjtcXU:-NnHNW-k0VRcpFvjtcXV:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/rlcs.py#L34)):*
> ```Python
> 
> 
> def print_data(parsed: dict):
> ```

See above
___
*[`sources/rlcs/rlcs.py` line 39 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHNWdLENwsihU_3U1t:-NnHNWdLENwsihU_3U1u:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/rlcs.py#L39)):*
> ```Python
> 
> 
> def parse_rlcs(line: str | bytes) -> dict | None:
> ```

See above
___
*[`sources/rlcs/rlcs.py` line 54 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHO18rD2tDM9lyEAFz:-NnHO18s9XV3_Y6Brh3u:b-u5qxnf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/rlcs.py#L54)):*
> ```Python
> 
> 
> def check_data_is_valid(line: str | bytes) -> bool:
> ```

I don't think the input here is `str | bytes`, from the docstring and function body it seems to be just `bytes`

**Comment by JasonBrave** [comment]
Lmao you saw the assignee of #151 right?

**Comment by patrick-gu** [comment]
> Lmao you saw the assignee of #151 right?

My bad, if you already have a fix I can close this lol

**Review by patrick-gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sources/rlcs/commander.py` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHMTKp0v_wdiclx0Jx:-NnKrymOCkfuGEQ6EFk0:b-t2vj72) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/commander.py#L22)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Please add what types the `dict` is made of (i.e. `str` to `int` or whatever it is). I'm not sure what the proper syntax is for that so you'll have to look it up
</blockquote></details>

Done. Technically, we could be more precise of what exact strings can be passed in, but I think that would be overkill.
___
*[`sources/rlcs/rlcs.py` line 34 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHNW-k0VRcpFvjtcXU:-NnKs3Sk7cgIoruSsonj:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/rlcs.py#L34)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`sources/rlcs/rlcs.py` line 39 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHNWdLENwsihU_3U1t:-NnKs4-I0dR0GAp_bTp6:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/rlcs.py#L39)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`sources/rlcs/rlcs.py` line 54 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHO18rD2tDM9lyEAFz:-NnKs4Yg1tZd9uPF-Rq0:bjuoybl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/rlcs.py#L54)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

I don't think the input here is `str | bytes`, from the docstring and function body, it seems to be just `bytes`
</blockquote></details>

This comes from the argument of `parse_rlcs`, which itself comes from `reader` in `main.py` which can return a reader that returns either `str` (if it uses `input`) or `bytes` (if it uses `_reader`)

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-:-NnUvID564Okij3Bl8MH:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sources/rlcs/commander.py` line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHMTKp0v_wdiclx0Jx:-NnUv0iB51YEo_c4Fwq8:b-49f585) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/commander.py#L22)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Done. Technically, we could be more precise of what exact strings can be passed in, but I think that would be overkill.
</blockquote></details>

This is good!
___
*[`sources/rlcs/rlcs.py` line 54 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/192#-NnHO18rD2tDM9lyEAFz:-NnUvEnO4EuQsyz1cZBq:btn5jp1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369eb3f7ea6514284bd13fc8883d5aed4019d1b7/sources/rlcs/rlcs.py#L54)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

This comes from the argument of `parse_rlcs`, which itself comes from `reader` in `main.py` which can return a reader that returns either `str` (if it uses `input`) or `bytes` (if it uses `_reader`)
</blockquote></details>

Gotcha

**Pull request merged**
