### PR TITLE
Added logging feature to launcher

### LINKED ISSUE #140: Add Log Files
Dependent on #131 
---
With the new omnibus launcher, `stdout` from each process is printed when you exit along with `stderr` if there is any. It would be better to have these be written to log files for each source/sink instead (ex. `dashboard.log`, `fakeni.log`).

### PR DESCRIPTION
**Pull request by Andre-The-Greek**
Automatically generates new log files for new sinks or sources as they are used. Logs output/err from core_library in core_library.log.

The code works of a dictionary of loggers.
It parses the name of the source/sink/other program from its attributes which normally looks like sinks/dashboard/main.py, and creates a logger for it. Also creates a logger for the core library "omnibus".

Closes #140 

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work with the loggers overall, just a couple small things

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-:-Nig5vS-2gC8_ocqFpTq:bdytmrh)* status: all files reviewed, 11 unresolved discussions (waiting on @Andre-The-Greek, @BluCodeGH, and @KavinSatheeskumar)

___
*[`launcher.py` line 41 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nifl9UwE6dMF6g80BeI:-Nifl9UwE6dMF6g80BeJ:b-40ajtc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/launcher.py#L41)):*
> ```Python
> logger.add_logger(f"sources/{modules['sources'][int(source_selection) - 1]}")
> logger.add_logger(f"sinks/{modules['sinks'][int(sink_selection) - 1]}")
> print("\nLoggers Initiated")
> ```

Don't need a newline here
___
*[`launcher.py` line 64 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Niflydv3nWKoIp5HjM4:-Niflydv3nWKoIp5HjM5:b-dnd7m3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/launcher.py#L64)):*
> ```Python
> 
> 
> class Finished(Exception):
> ```

Two blank lines above can be deleted
___
*[`logtool.py` line 4 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-NifmJ1d4S-RbVmwcXpQ:-NifmJ1d4S-RbVmwcXpR:b42r3p) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L4)):*
> ```Python
> import os
> 
> # dynamically generates logger objects and log files based on the number of sources and sinks and stores all loggers in a dictionary accessed with the filename without .py
> ```

Nitpick: Start comments with uppercase letters please, like you would a regular sentence
___
*[`logtool.py` line 24 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-NifnNUd6rz0StIB1TL1:-NifnNUd6rz0StIB1TL2:b-walpy2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L24)):*
> ```Python
> 
>             handler = logging.FileHandler(f"logs/{file_dir}/{file_name}.log", mode='w')
>             formatter = logging.Formatter('%(levelname)s:%(name)s:%(message)s')
> ```

Can you make the message be on a separate line like so: `%(levelname)s:%(name)s:\n%(message)s`? Because we only collect output once at the end and not continuously, this will serve as a header of sorts and the entire output will be below
___
*[`logtool.py` line 29 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig4kRW1MvQIXoKAKi5:-Nig4kRW1MvQIXoKAKi6:b-39slzu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L29)):*
> ```Python
>             logger.addHandler(handler)
>             self.loggers.update({file_name: logger})
>         else:
> ```

This section seems redundant, you can just pass in `core-library` as the filename instead
___
*[`logtool.py` line 45 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6Ct23tElGPSmF_3m:-Nig6Ct23tElGPSmF_3n:b70yg0i) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L45)):*
> ```Python
>         try:
>             self.loggers[process.args[-1].split("/")[1]].info(f"From {process.args}:{output}")
>             print(f"\nOutput from {process.args} logged")
> ```

Don't need the `\n`
___
*[`logtool.py` line 46 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig5MoC4lYLv6TPnNW2:-Nig5MoC4lYLv6TPnNW3:b-vj7rji) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L46)):*
> ```Python
>             self.loggers[process.args[-1].split("/")[1]].info(f"From {process.args}:{output}")
>             print(f"\nOutput from {process.args} logged")
>         except (IndexError, KeyError):
> ```

Instead of trying to catch errors, it might be easier to check if this process is for the core-library:
```
if process.args[-1] == "omnibus":
    ...
```
___
*[`logtool.py` line 47 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6QtKBUAL2AR1ZVDD:-Nig6H3p9Kxzk7kslDMq:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L47)):*
> ```Python
>             print(f"\nOutput from {process.args} logged")
>         except (IndexError, KeyError):
>             print(f"\nOutput from {process.args} logged in core-library.log")
> ```

See above
___
*[`logtool.py` line 54 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6_gRCSb3WaQBODX9:-Nig6_gRCSb3WaQBODXA:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L54)):*
> ```Python
>         try:
>             self.loggers[process.args[-1].split("/")[1]].error(f"From {process.args}:{err}")
>             print(f"\nError from {process.args} logged")
> ```

See above
___
*[`logtool.py` line 55 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig5j9vDe0XBmx_ZARj:-Nig5j9vDe0XBmx_ZARk:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L55)):*
> ```Python
>             self.loggers[process.args[-1].split("/")[1]].error(f"From {process.args}:{err}")
>             print(f"\nError from {process.args} logged")
>         except (IndexError, KeyError):
> ```

See above
___
*[`logtool.py` line 56 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6KR0AwUcGb0dIusj:-Nig6KR0AwUcGb0dIusk:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L56)):*
> ```Python
>             print(f"\nError from {process.args} logged")
>         except (IndexError, KeyError):
>             print(f"\nError from {process.args} logged in core-library.log")
> ```

See above

**Review by Andre-The-Greek — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-:-NigcQPx7livxPalV4Vg:b-896fix)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

**Review by Andre-The-Greek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`launcher.py` line 41 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nifl9UwE6dMF6g80BeI:-NigclED4Yk8_NzZnJIz:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/launcher.py#L41)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Don't need a newline here
</blockquote></details>

Done.
___
*[`launcher.py` line 64 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Niflydv3nWKoIp5HjM4:-Nigcm5-E5G-Mw6bbVuO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/launcher.py#L64)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Two blank lines above can be deleted
</blockquote></details>

Done.
___
*[`logtool.py` line 4 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-NifmJ1d4S-RbVmwcXpQ:-NigcmhY5IzUnvNaVZCO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L4)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Nitpick: Start comments with uppercase letters please, like you would a regular sentence
</blockquote></details>

Done.
___
*[`logtool.py` line 24 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-NifnNUd6rz0StIB1TL1:-Nigcn9r3KP-HluOyJOv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L24)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Can you make the message be on a separate line like so: `%(levelname)s:%(name)s:\n%(message)s`? Because we only collect output once at the end and not continuously, this will serve as a header of sorts and the entire output will be below
</blockquote></details>

Done.
___
*[`logtool.py` line 29 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig4kRW1MvQIXoKAKi5:-NigcndD702r0qfLgH7e:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L29)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

This section seems redundant, you can just pass in `core-library` as the filename instead
</blockquote></details>

Done.
___
*[`logtool.py` line 45 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6Ct23tElGPSmF_3m:-Nigcoj92JqYTMYPANuo:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L45)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Don't need the `\n`
</blockquote></details>

Done.
___
*[`logtool.py` line 46 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig5MoC4lYLv6TPnNW2:-Nigco845i_QntwSFVy5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L46)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Instead of trying to catch errors, it might be easier to check if this process is for the core-library:
```
if process.args[-1] == "omnibus":
    ...
```
</blockquote></details>

Done.
___
*[`logtool.py` line 47 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6QtKBUAL2AR1ZVDD:-NigcoUf6bqokhDk7nhH:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L47)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`logtool.py` line 54 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6_gRCSb3WaQBODX9:-Nigcpqt1YBCilNPhDR7:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L54)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`logtool.py` line 55 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig5j9vDe0XBmx_ZARj:-NigcpDg6AjN2mTeFW9Q:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L55)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`logtool.py` line 56 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nig6KR0AwUcGb0dIusj:-NigcpWVAeThytzCmqNB:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8027f909351f3321e1126c34deeeefd32d367288/logtool.py#L56)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

**Review by Darth-Raazi — APPROVED** [review]
:lgtm: pending the one minor comment

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-:-Nim5Xw96jtVOrLWJ1U7:b-aqz0nh)* status: all files reviewed, 2 unresolved discussions (waiting on @Andre-The-Greek, @BluCodeGH, and @KavinSatheeskumar)

___
*[`logtool.py` line 35 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nim4c6W3LZICk1tMSxv:-Nim4c6W3LZICk1tMSxw:bie9dev) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/420a28a6b3b7c4c4c3812dfd3604414de4d222f4/logtool.py#L35)):*
> ```Python
>     def log_output(self, process, output):
>         if process.args[-1] == "omnibus":
>             print(f"Output from {process.args} logged in core_library.log")
> ```

No need to specify the `in core_library.log`. Also since the print statement is going to be the same, you can take it out of the if-else statement and only have it once instead of twice
___
*[`logtool.py` line 44 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/162#-Nim4zJ1D0ViAnbhLX17:-Nim4zJ1D0ViAnbhLX18:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/420a28a6b3b7c4c4c3812dfd3604414de4d222f4/logtool.py#L44)):*
> ```Python
>     def log_error(self, process, err):
>         if process.args[-1] == "omnibus":
>             print(f"Error from {process.args} logged in core_library.log")
> ```

See above

**Pull request merged**
