### PR TITLE
Global logging

### PR DESCRIPTION
**Pull request by jli35**
adds global logging sink

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Apart from some small comments this looks like it does the job. That being said, I'm not sure the logging library is the best tool for the job here. It's designed for big programs where there will be lots of different parts writing log messages, whereas for our use case (just one place where we write to the file) direct file access will be simpler and more maintainable.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-:-Mauo-qf3bQvId9oeRZ2:b-ded1uo)* status: all files reviewed, 5 unresolved discussions (waiting on @jli35)

___
*[sinks/globallog/main.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mauk2yw7UvAzMX9lwGQ:-Mauk2yw7UvAzMX9lwGR:b1rtjm1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f2824df7fc658f62c6af70b5e5a0f31bb0c8c222/sinks/globallog/main.py#L8)):*
> ```Python
> 
> # Set to listen to all channels -> ""
> channel = ""
> ```

Constants should be ALL_CAPS.
___
*[sinks/globallog/main.py, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mauk6vfArU5AFCFCNc0:-Mauk6vfArU5AFCFCNc1:b-l3u8bf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f2824df7fc658f62c6af70b5e5a0f31bb0c8c222/sinks/globallog/main.py#L9)):*
> ```Python
> # Set to listen to all channels -> ""
> channel = ""
> receiver = Receiver("tcp://localhost:5076", channel)
> ```

See recent commits to bus branch, pull the server url out into a constant.
___
*[sinks/globallog/main.py, line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-MaukPUMBsP2KfpY7Jwd:-MaukPUMBsP2KfpY7Jwe:b4ppvt3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f2824df7fc658f62c6af70b5e5a0f31bb0c8c222/sinks/globallog/main.py#L11)):*
> ```Python
> receiver = Receiver("tcp://localhost:5076", channel)
> 
> msg = receiver.recv_message()
> ```

Why do you throw away the first message received?
___
*[sinks/globallog/main.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mauk_vdDWPHqy_4OzRC:-Mauk_vdDWPHqy_4OzRD:be9659b) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f2824df7fc658f62c6af70b5e5a0f31bb0c8c222/sinks/globallog/main.py#L14)):*
> ```Python
> 
> # name of the file the log is saved to
> fname = 'globalLog.log'
> ```

It would be great to use the current date+time as the filename.
___
*[sinks/globallog/main.py, line 25 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Maulp0BDScN7zmOdFSy:-Maulp0BDScN7zmOdFSz:boqyl0i) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f2824df7fc658f62c6af70b5e5a0f31bb0c8c222/sinks/globallog/main.py#L25)):*
> ```Python
> # generate formatting of logged messages
> # ex: "68464665.21550 : INFO : fake : [123123,123]"
> formatter = logging.Formatter('%(timestamp)s :: %(channel)s :: %(levelname)s :: %(message)s')
> ```

Given that you log everything as info it's probably unnecessary to put in the format.

**Review by jli35 — COMMENTED** [review]
Changed method to file writing. Could change formatting of saved message.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-:-MaybWC4DWXbxvkX3U_y:becyxfi)* status: all files reviewed, 5 unresolved discussions (waiting on @BluCodeGH)

___
*[sinks/globallog/main.py, line 8 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mauk2yw7UvAzMX9lwGQ:-MayavZaDcGhXixBYrOt:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2554b3fb6f9f4581d9d6c982025cd5f56ff19592/sinks/globallog/main.py#L8)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Constants should be ALL_CAPS.
</blockquote></details>

Done.
___
*[sinks/globallog/main.py, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mauk6vfArU5AFCFCNc0:-MayaxGu8aPhBYtHxgNW:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2554b3fb6f9f4581d9d6c982025cd5f56ff19592/sinks/globallog/main.py#L9)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

See recent commits to bus branch, pull the server url out into a constant.
</blockquote></details>

Done.
___
*[sinks/globallog/main.py, line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-MaukPUMBsP2KfpY7Jwd:-Mayb3wdA_W79W-zj4UV:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2554b3fb6f9f4581d9d6c982025cd5f56ff19592/sinks/globallog/main.py#L11)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Why do you throw away the first message received?
</blockquote></details>

Done.
___
*[sinks/globallog/main.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mauk_vdDWPHqy_4OzRC:-Mayb-oBC3xjAgQl5DDk:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2554b3fb6f9f4581d9d6c982025cd5f56ff19592/sinks/globallog/main.py#L14)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

It would be great to use the current date+time as the filename.
</blockquote></details>

Done
___
*[sinks/globallog/main.py, line 25 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Maulp0BDScN7zmOdFSy:-Mayb4FSDQpl2PhsyPvU:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2554b3fb6f9f4581d9d6c982025cd5f56ff19592/sinks/globallog/main.py#L25)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Given that you log everything as info it's probably unnecessary to put in the format.
</blockquote></details>

Done.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5)* status: all files reviewed, 2 unresolved discussions (waiting on @jli35)

___
*[sinks/globallog/main.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-MaycDuACUrC7DXtxxNw:-MaycDuACUrC7DXtxxNx:bpdoiwt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00b69929c4f92bc83b47583ec8bdbf07f14ccd54/sinks/globallog/main.py#L15)):*
> ```Python
> fname = CURTIME + ".log"
> 
> f = open(fname, "w")
> ```

Prefer to use `with open(fname, "w") as f:` syntax to handle automatically closing the file.
___
*[sinks/globallog/main.py, line 21 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-MaycbHa9tC5WTu_IFjN:-MaycbHa9tC5WTu_IFjO:bewndvr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00b69929c4f92bc83b47583ec8bdbf07f14ccd54/sinks/globallog/main.py#L21)):*
> ```Python
>     msg = receiver.recv_message()
>     line = [msg.timestamp, " :: ", msg.channel, " :: ", msg.payload]
>     f.writelines(str(line))
> ```

Prefer to use format strings `f"{msg.timestamp} :: {msg.channel} ..."`.

**Review by jli35 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5)* status: all files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[sinks/globallog/main.py, line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-MaycDuACUrC7DXtxxNw:-MazletpEQtlPB05xo0Q:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00b69929c4f92bc83b47583ec8bdbf07f14ccd54/sinks/globallog/main.py#L15)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Prefer to use `with open(fname, "w") as f:` syntax to handle automatically closing the file.
</blockquote></details>

Done.
___
*[sinks/globallog/main.py, line 21 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-MaycbHa9tC5WTu_IFjN:-MazlfD8D88JCVwaRobg:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00b69929c4f92bc83b47583ec8bdbf07f14ccd54/sinks/globallog/main.py#L21)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Prefer to use format strings `f"{msg.timestamp} :: {msg.channel} ..."`.
</blockquote></details>

Done.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-:-Mazm8GA0sFCOU_XeQZU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jacobdeery, @PCModeActivate, and @wendi-yu)

**Review by jacobdeery — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5)* status: all files reviewed, 1 unresolved discussion (waiting on @Huan-YiShen, @jli35, @PCModeActivate, and @wendi-yu)

___
*[sinks/globallog/main.py, line 9 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mazn5tF5Mq_qu3j7sC8:-Mazn5tF5Mq_qu3j7sC9:b8l6lvo) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/35a7392142f79c9ef8eba6e255b02c18dd38ff5a/sinks/globallog/main.py#L9)):*
> ```
> SERVER = "tcp://localhost:5076"
> ```
Instead of writing this in every bus process, can we make a variable called `omnibus.server_addr` or similar?

**Review by BluCodeGH — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5)* status: all files reviewed, 1 unresolved discussion (waiting on @Huan-YiShen, @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[sinks/globallog/main.py, line 9 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-Mazn5tF5Mq_qu3j7sC8:-Mb-31MM4aidmgsAfqD5:b-vrajne) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/35a7392142f79c9ef8eba6e255b02c18dd38ff5a/sinks/globallog/main.py#L9)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> SERVER = "tcp://localhost:5076"
> ```
Instead of writing this in every bus process, can we make a variable called `omnibus.server_addr` or similar?
</blockquote></details>

#6 takes care of this, once this gets merged I'll merge it into `auto-ip` and remove the string then.

**Review by wendi-yu — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5#-:-MbsH3wq2WOCBlVtG-IZ:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @Huan-YiShen, @jacobdeery, and @PCModeActivate)

**Review by jacobdeery — APPROVED** [review]

**Review by BluCodeGH — APPROVED** [review]
> Dismissed @jacobdeery from a discussion.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen and @PCModeActivate)

**Pull request merged**
