### PR TITLE
Add support for receiving from multiple channels

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
Make use of the built in feature of zmq to receive on multiple channels to make the the receiver class receive on multiple channels

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29)* status: all files reviewed, 8 unresolved discussions (waiting on @BenLevy7, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[omnibus/omnibus.py, line 86 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXbWa02W8NsgPO2Dpr:-MgXbWa10frHmXAfRtNO:b-puvvc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus.py#L86)):*
> ```Python
>     def send(self, channel: str, payload):
>         """
>         Wrap a payload in a message object and send it on a provided channel.
> ```

a provided -> the provided
___
*[omnibus/omnibus.py, line 94 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXbbLQ64X6oG75xz29:-MgXbbLQ64X6oG75xz2A:b406i45) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus.py#L94)):*
> ```Python
> class Receiver(OmnibusCommunicator):
>     """
>     Listens to a number of channels and receives all messages sent to it.
> ```

sent to it -> sent to them
___
*[omnibus/omnibus.py, line 106 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXbwOI6mAxYY7HZMRF:-MgXbwOJ3T6_peKD0cmc:bnd3fya) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus.py#L106)):*
> ```Python
> 
>         if len(channels) == 0:
>             raise Exception("At least one channel must be provided")
> ```

I wouldn't be so quick to raise an exception here, as an trivial example I could see a use case where the plotter creates a receiver based on what plots are open and we don't want it to crash when no plots are open.
___
*[omnibus/omnibus_test.py, line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXcY4C7lpQk0PtKTyO:-MgXcY4C7lpQk0PtKTyP:b2z1vn3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus_test.py#L40)):*
> ```Python
>     def receiver(self):
>         def _receiver(*channel):
>             r = Receiver(*channel)
> ```

Since there might be more than one channel better to use the plural `*channels`.
___
*[omnibus/omnibus_test.py, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXcl628RDSx8BQH7Yh:-MgXcl638w3Z-RP29NIb:becb6fj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus_test.py#L78)):*
> ```Python
>         s = sender()
>         r = receiver("A", "B", "C")
>         s.send("A", "message1")
> ```

For consistency with the other tests, call channels `CHAN{n}` and use letters as messages.
___
*[sources/fakeni/main.py, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXdBpu-P1S8dGZgkcb:-MgXdBpu-P1S8dGZgkcc:b7zz3lm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/sources/fakeni/main.py#L21)):*
> ```Python
>         "data": {f"Fake{i}": [random.random() for _ in range(READ_BULK)] for i in range(CHANNELS)}
>     }
>     sender.send("DAQ/Fake", data)
> ```

Probably best to break this out into a `CHANNEL` constant right after you instantiate the sender. I know it makes the change seem like it doesn't do anything but receiving on multiple channels easily is really nice, and when we need to send on multiple channels (eg log replay) the new API will be a lot nicer too.
___
*[sources/ni/main.py, line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXdmDs7pWMa3TQFDLX:-MgXdmDt7k7Xr7AStvCQ:bu0g8p2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/sources/ni/main.py#L53)):*
> ```Python
>             log.write(msgpack.packb(data))
> 
>             sender.send("DAQ", data)  # send data to omnibus
> ```

Break out.
___
*[sources/parsley/main.py, line 304 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXdoh54lmOcF-cqsQJ:-MgXdoh54lmOcF-cqsQK:bu0g8p2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/sources/parsley/main.py#L304)):*
> ```Python
>         output = output + '{:<20}'.format(data)
> 
>     sender.send("CAN/Parsley", output)
> ```

Break out.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @BenLevy7, @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @PCModeActivate, and @wendi-yu)

___
*[omnibus/omnibus.py, line 106 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXbwOI6mAxYY7HZMRF:-MgcPor91q4cDHN0saZR:b6d2f4z) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus.py#L106)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I wouldn't be so quick to raise an exception here, as an trivial example I could see a use case where the plotter creates a receiver based on what plots are open and we don't want it to crash when no plots are open.
</blockquote></details>

OK, I replaced it with a print line, but we had ought find a better way of handling this
___
*[omnibus/omnibus_test.py, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXcl628RDSx8BQH7Yh:-MgcQkcJCYubXjza-URx:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus_test.py#L78)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

For consistency with the other tests, call channels `CHAN{n}` and use letters as messages.
</blockquote></details>

Done.
___
*[sources/fakeni/main.py, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXdBpu-P1S8dGZgkcb:-MgcQlalBiB1AbGf8vMx:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/sources/fakeni/main.py#L21)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Probably best to break this out into a `CHANNEL` constant right after you instantiate the sender. I know it makes the change seem like it doesn't do anything but receiving on multiple channels easily is really nice, and when we need to send on multiple channels (eg log replay) the new API will be a lot nicer too.
</blockquote></details>

Done.
___
*[sources/ni/main.py, line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXdmDs7pWMa3TQFDLX:-MgcQm2XAXjqQIcgg17b:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/sources/ni/main.py#L53)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Break out.
</blockquote></details>

Done.
___
*[sources/parsley/main.py, line 304 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXdoh54lmOcF-cqsQJ:-MgcQmh0EbPNloAbSfUv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/sources/parsley/main.py#L304)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Break out.
</blockquote></details>

Done.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29)* status: all files reviewed, 2 unresolved discussions (waiting on @BenLevy7, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[omnibus/omnibus.py, line 106 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXbwOI6mAxYY7HZMRF:-MgsRXPQ75ZqRJNXp5tQ:b5o31t1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus.py#L106)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

OK, I replaced it with a print line, but we had ought find a better way of handling this
</blockquote></details>

Any ideas for better ways to handle it? I'm not really sure there's anything to handle here though, I'm of the opinion that if someone wants a receiver that doesn't listed to any channels we should let them without complaining.
___
*[sources/ni/main.py, line 11 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgsT2lD4LLZkbnJCD-o:-MgsT2lD4LLZkbnJCD-p:bdhvgm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/74bd3bcd92f666d35cf40e14cf270f5d2c6f4e00/sources/ni/main.py#L11)):*
> ```Python
> import calibration
> 
> CHANNEL = "DAQ"
> ```

I think its more readable to set this right after we instantiate the sender so it has some context (same with the other two sources).

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @BenLevy7, @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @PCModeActivate, and @wendi-yu)

___
*[omnibus/omnibus.py, line 106 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgXbwOI6mAxYY7HZMRF:-MjG_8pH2q0VayB1HtDv:b-90g7pm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e80b6792c9b4f35276028c87bcf1281d754ee651/omnibus/omnibus.py#L106)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Any ideas for better ways to handle it? I'm not really sure there's anything to handle here though, I'm of the opinion that if someone wants a receiver that doesn't listed to any channels we should let them without complaining.
</blockquote></details>

So I just removed those lines for now, if we ever want to change it we can later
___
*[sources/ni/main.py, line 11 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-MgsT2lD4LLZkbnJCD-o:-MjG_ENI96G7jqBWRx7g:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/74bd3bcd92f666d35cf40e14cf270f5d2c6f4e00/sources/ni/main.py#L11)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I think its more readable to set this right after we instantiate the sender so it has some context (same with the other two sources).
</blockquote></details>

Done.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-:-MjK40Pq7TkaVzUx-RKX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BenLevy7, @Huan-YiShen, @jacobdeery, @jli35, @PCModeActivate, and @wendi-yu)

**Review by wendi-yu — COMMENTED** [review]
Also :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/29#-:-MjzsBOF4Sgw2qv2IbOI:b-65ggps)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @BenLevy7, @Huan-YiShen, @jacobdeery, @jli35, and @PCModeActivate)

**Review by wendi-yu — APPROVED** [review]

**Pull request merged**
