### PR TITLE
Type hint replay log

### LINKED ISSUE #178: Type Hint Replay Log
See #145 

This issue is for `sources/replay_log`

### PR DESCRIPTION
**Pull request by patrick-gu**
## Description
Added type hints to `sources/replay_log`.

I did not add type hints to `get_percent_error` or `get_runtime`. Also was unsure how to type hint the test fixtures, or if those even need to be type hinted.

This PR closes #178.

## Developer Testing

Here's what I did to test my changes:

- N/A no semantic changes

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Verify that the type hints make sense
- Tell me what needs to be type hinted

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193)

### CODE REVIEW

**Comment by patrick-gu** [comment]
To be clear, should type hinting be only for the public API functions? Or for internal functions as well?

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
All functions, including internal ones, except test fixtures need to be type hinted

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-:-NnHO_REEvngwcWPFKl4:b-62aszp)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sources/replay_log/replay_log.py` line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-NnHPGB_Ej2sQFDc3vWR:-NnHPGB_Ej2sQFDc3vWS:b4u906b) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e8ddec28d42bce4fc254f4be66159366cdde7eac/sources/replay_log/replay_log.py#L18)):*
> ```Python
> 
> 
> def replay(log_buffer: io.BufferedReader, replay_speed: float | int):
> ```

I'm not sure if this is the correct type for `log_buffer`, how did you determine it? Another option might be the `typing` module's `BinaryIO`. But if you run replay log with this and it doesn't complain then this is fine
___
*[`sources/replay_log/replay_log_test.py` line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-NnHTAvbAn_CLSE9HNVt:-NnHTAvbAn_CLSE9HNVu:bq8avia) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e8ddec28d42bce4fc254f4be66159366cdde7eac/sources/replay_log/replay_log_test.py#L18)):*
> ```Python
> 
> 
> def get_percent_error(expected, received):
> ```

This should be pretty simple the type hint, they have to be either `int` or `float`, a `print(type(...))` should help 
___
*[`sources/replay_log/replay_log_test.py` line 29 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-NnHSxAn8y7GMFblcbne:-NnHSxAn8y7GMFblcbnf:b5uomy0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e8ddec28d42bce4fc254f4be66159366cdde7eac/sources/replay_log/replay_log_test.py#L29)):*
> ```Python
> 
> 
> def get_runtime(func, *args, **kwargs):
> ```

Yeah I wouldn't type hint this, just leave it

**Review by patrick-gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sources/replay_log/replay_log.py` line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-NnHPGB_Ej2sQFDc3vWR:-NnKoouLEVpVvs-BQmqw:bt5choq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e8ddec28d42bce4fc254f4be66159366cdde7eac/sources/replay_log/replay_log.py#L18)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

I'm not sure if this is the correct type for `log_buffer`, how did you determine it? Another option might be the `typing` module's `BinaryIO`. But if you run replay log with this and it doesn't complain then this is fine
</blockquote></details>

The usage in `main.py` passes in a file opened with `open`, which returns `io.BufferedReader`.
___
*[`sources/replay_log/replay_log_test.py` line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-NnHTAvbAn_CLSE9HNVt:-NnKoe8t-Ddw9GAGXYmK:b2vjl8o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e8ddec28d42bce4fc254f4be66159366cdde7eac/sources/replay_log/replay_log_test.py#L18)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

This should be pretty simple the type hint, they have to be either `int` or `float`, a `print(type(...))` should help
</blockquote></details>

Sorry I forgot to say this, but I don't think this function is actually used, which is why I didn't type hint it

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-:-NnUuLqb15a-rT4NL2Rr:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sources/replay_log/replay_log.py` line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-NnHPGB_Ej2sQFDc3vWR:-NnUtqvECP03ZL8DdtzV:btn461w) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e8ddec28d42bce4fc254f4be66159366cdde7eac/sources/replay_log/replay_log.py#L18)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

The usage in `main.py` passes in a file opened with `open`, which returns `io.BufferedReader`.
</blockquote></details>

Got it
___
*[`sources/replay_log/replay_log_test.py` line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/193#-NnHTAvbAn_CLSE9HNVt:-NnUtsNZ0y04Lmxjp-fb:b-9mte0p) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e8ddec28d42bce4fc254f4be66159366cdde7eac/sources/replay_log/replay_log_test.py#L18)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Sorry I forgot to say this, but I don't think this function is actually used, which is why I didn't type hint it
</blockquote></details>

In that case, you can remove this function. I think `get_runtime` also isn't used, so you can remove that as well

**Pull request merged**
