### PR TITLE
Set up repo, implement Omnibus and a sample source and sink

### PR DESCRIPTION
**Pull request by BluCodeGH**
This includes the (very heavily inspired from topside) basic repo setup, an implementation of the Omnibus library, and a sample source and sink.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Ya generally looks pretty good to me, mostly typo fixes from me lol.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-:-MatV_De00MdeEhzDlEn:b-x72v2q)* status: 0 of 15 files reviewed, 8 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @KavinSatheeskumar, and @PCModeActivate)

___
*[CONTRIBUTING.md, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatOsqt4LSwknvuD-RN:-MatOsquBIwFDJumr-fC:b-btxufh) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/CONTRIBUTING.md#L9)):*
> ```Markdown
> 2. Enter the newly-cloned repo with `cd omnibus`
> 3. Run `pip install wheel`, which will help install the rest of the packages more quickly.
> 4. Install Python dependencies with `pip install -r requirements.txt`. If you get a permissions error, try `pip install -U -r requirements.txt` instead.
> ```

I know this is from the topside contributing.MD, but do we want `pip install -U` or `--user`? I googled it and it looks like `-U` upgrades the packages to the latest version (not necessarily what we want? we've had upstream errors in the past) and `--user` puts it in the home directory instead of the system directory.
___
*[requirements.txt, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatPpihAPMI2r7mmTIv:-MatPpiiAnt9Cvk3zxnQ:b7cqli1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/requirements.txt#L1)):*
> ```vimhelp
> attrs==21.2.0                                                                                                  
> ```

Lol lots of spaces after this line?
___
*[omnibus/omnibus.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatQOoW5XKwfU5ZxsnD:-MatQOoW5XKwfU5ZxsnE:bh2h5fw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L35)):*
> ```Python
>     def send_message(self, message: Message):
>         """
>         Sends a built message object to all recievers. Note that channel used is
> ```

Just a nitpick but docstrings are also supposed to be imperative in Python
___
*[omnibus/omnibus.py, line 54 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatQePb3id8EX3ayTjo:-MatQePb3id8EX3ayTjp:b-sqeepw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L54)):*
> ```Python
> class Receiver:
>     """
>     A reciever listens to a channel and recieves all messages sent to that channel.
> ```

reciever -> receiver through the description ;) something something i before e except after c lol
___
*[omnibus/server.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatRKB787R6yMw22vj_:-MatRKB787R6yMw22vja:bwn8l72) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L13)):*
> ```Python
> def get_ip():
>     """
>     Returns our best guess for this machines IP on the LAN.
> ```

machine's
___
*[omnibus/server.py, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatRl3_1yV1PzUYABQ5:-MatRl3_1yV1PzUYABQ6:bfqvlbt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L21)):*
> ```Python
>         return s.getsockname()[0]
>     except Exception:
>         return "127.0.0.1"
> ```

dumb question but since it's a string, does this work with IPV6 lol
___
*[omnibus/server.py, line 42 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatRQre6qZfUZ15qfF-:-MatRQre6qZfUZ15qfF0:bgn8nph) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L42)):*
> ```Python
>     proxy.start()
> 
>     local_ip = get_ip()
> ```

Since `get_ip()` is a best guess, should we add in a way of specifying the ip address? I'm assuming it'll generally work but in case it doesn't
___
*[sinks/printer/main.py, line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatTJ7sBz8wDdWeHVEw:-MatTJ7sBz8wDdWeHVEx:b-ancwza) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/sinks/printer/main.py#L11)):*
> ```Python
> if len(sys.argv) > 1:
>     channel = sys.argv[1]
> receiver = Receiver("tcp://localhost:5076", channel)
> ```

do we want the port pulled out into a variable here too?

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3)* status: 0 of 15 files reviewed, 14 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @KavinSatheeskumar, and @PCModeActivate)

___
*[requirements.txt, line 12 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatcRUC5f7N25a7fMTP:-MatcRUC5f7N25a7fMTQ:b-qpd1dr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/requirements.txt#L12)):*
> ```vimhelp
> pytest==6.2.4
> pyzmq==22.1.0
> toml==0.10.2
> ```

Up to you, but I usually prefer to just specify the requirements that I use directly (msgpack, zmq, pytest, etc.) and not all of the transitive dependencies like `py`. I find that it makes the requirements much easier to read.
___
*[omnibus/omnibus.py, line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd4Jw7nsdCPYTQaqe:-Matd4Jw7nsdCPYTQaqf:b-7zukx5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L22)):*
> ```
> recievers
> ```
receivers
___
*[omnibus/omnibus.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd2nbD0B1bgNFMbT9:-Matd2nbD0B1bgNFMbTA:b-7zukx5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L35)):*
> ```
> recievers
> ```
receivers
___
*[omnibus/omnibus.py, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd87V2Ur6CpWSyzSv:-Matd87V2Ur6CpWSyzSw:bgqxlh7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L68)):*
> ```
> Recieves
> ```
Receives
___
*[omnibus/omnibus.py, line 70 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd9EnE6Az8je-9p6R:-Matd9EnE6Az8je-9p6S:bjqt5uj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L70)):*
> ```
> recieved
> ```
received
___
*[omnibus/server.py, line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MateV308LPX8lJwnRib:-MateV313jmfrSd9eBbX:bz5nhff) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L47)):*
> ```
> recieves
> ```
receives

**Review by BluCodeGH — COMMENTED** [review]
> Reviewed 8 of 15 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3)* status: all files reviewed, 5 unresolved discussions (waiting on @Huan-YiShen, @jacobdeery, @KavinSatheeskumar, and @PCModeActivate)

___
*[CONTRIBUTING.md, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatOsqt4LSwknvuD-RN:-MatsO2P9IIisyTT0z5I:bnwdxy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/CONTRIBUTING.md#L9)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I know this is from the topside contributing.MD, but do we want `pip install -U` or `--user`? I googled it and it looks like `-U` upgrades the packages to the latest version (not necessarily what we want? we've had upstream errors in the past) and `--user` puts it in the home directory instead of the system directory.
</blockquote></details>

Oh whoops I assumed -U was short for --user, nice catch.
___
*[requirements.txt, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatPpihAPMI2r7mmTIv:-MatsXkQ3AflDv6jXIWR:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/requirements.txt#L1)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Lol lots of spaces after this line?
</blockquote></details>

Done.
___
*[requirements.txt, line 12 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatcRUC5f7N25a7fMTP:-MatsdAeDbfJy7U9E3kw:b-wn7o9g) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/requirements.txt#L12)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Up to you, but I usually prefer to just specify the requirements that I use directly (msgpack, zmq, pytest, etc.) and not all of the transitive dependencies like `py`. I find that it makes the requirements much easier to read.
</blockquote></details>

Yeah I agree, somewhere I read that pip didn't resolve dependencies when reading from a file but did a quick test and it worked fine. Reverted.
___
*[omnibus/omnibus.py, line 22 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd4Jw7nsdCPYTQaqe:-Matt1ys7YaXF32eWXeT:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L22)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recievers
> ```
receivers
</blockquote></details>

Done.
___
*[omnibus/omnibus.py, line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd2nbD0B1bgNFMbT9:-MatuQvG14YOhicrvfjl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L35)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recievers
> ```
receivers
</blockquote></details>

Done.
___
*[omnibus/omnibus.py, line 68 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd87V2Ur6CpWSyzSv:-Matu_mD6L8k-xACWeRv:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L68)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> Recieves
> ```
Receives
</blockquote></details>

Done.
___
*[omnibus/omnibus.py, line 70 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-Matd9EnE6Az8je-9p6R:-MatuaOK5nxefl6bmdOf:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/omnibus.py#L70)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recieved
> ```
received
</blockquote></details>

Done.
___
*[omnibus/server.py, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatRl3_1yV1PzUYABQ5:-MatvevuELS4Q-D0B-kG:b-hqem4c) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L21)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

dumb question but since it's a string, does this work with IPV6 lol
</blockquote></details>

No clue, do you have an IPV6-only LAN to test it on? As I mention below the IP is only used for printing so not a big deal if it doesn't (and I have secret plans to make specifying IPs unnecessary through the magic of UDP).
___
*[omnibus/server.py, line 42 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatRQre6qZfUZ15qfF-:-MatvpYwBpRZ4c72pkns:b6t1jiw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L42)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Since `get_ip()` is a best guess, should we add in a way of specifying the ip address? I'm assuming it'll generally work but in case it doesn't
</blockquote></details>

The IP is only used for printing, to save the user the trouble of looking it up when they want to connect sources/sinks.
___
*[omnibus/server.py, line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MateV308LPX8lJwnRib:-Matw43lB_newqfvnmm2:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L47)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> recieves
> ```
receives
</blockquote></details>

Done.

**Review by wendi-yu — APPROVED** [review]
:lgtm: I also went through and resolved the spelling comments from Jacob btw since they're pretty trivial

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-:-MbIfAEs9kQcNele7idq:bmzrd9h)* status: all files reviewed, 5 unresolved discussions (waiting on @Huan-YiShen, @jacobdeery, @KavinSatheeskumar, and @PCModeActivate)

___
*[omnibus/server.py, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-MatRl3_1yV1PzUYABQ5:-MbIeiBk6agAlOD5V1o6:b-buvir1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5e4e1146a52af3ea5db8bced759cea4c1b8d0020/omnibus/server.py#L21)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

No clue, do you have an IPV6-only LAN to test it on? As I mention below the IP is only used for printing so not a big deal if it doesn't (and I have secret plans to make specifying IPs unnecessary through the magic of UDP).
</blockquote></details>

hot diggity that's pretty hot, yeah if it's only for printing then nbd for me either, especially if IPV6 isn't super prevalent in Waterloo (?).

**Review by BluCodeGH — COMMENTED** [review]
Looks like your dismissal didn't go through.

> Dismissed @jacobdeery from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/3#-:-MbIhJk-3OpCPwP_vloq:b-2wj5xf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @KavinSatheeskumar, and @PCModeActivate)

**Pull request merged**
