### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Why is `sinks/globallog/wdr.log` checked in to git?

Also do you mind running autopep8? I think the tools/format.sh _should_ automatically work now.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Please fix the failing unit tests

**Review by Panizghi — COMMENTED** [review]
for the requirement.txt shouldn't the photograph be pyqtgraph==0.13.1?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-:-NIihzu96XoZNWFZ134R:b1dz2qy)* status: 0 of 25 files reviewed, all discussions resolved

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 22 files at r1, 14 of 15 files at r2, 1 of 1 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82)* status: all files reviewed, 4 unresolved discussions (waiting on @KavinSatheeskumar)

___
*[`sinks/dashboard/dashboard.py` line 193 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-NIjg6beELlqGjDEzVpQ:-NIjg6beELlqGjDEzVpR:b-99v8qi) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cb798c4750ddedcc7a4fa7c2f056981bc8bf1589/sinks/dashboard/dashboard.py#L193)):*
> ```Python
>         # Bit of a sussy baka, but this is the only way we can really get control over
>         # how the thing closes. In future, I might make a class method that returns
>         # this. Right now, not a priority.
> ```

What is this comment referring to? There's no code directly below it. Is it the whole add method?
___
*[`sinks/dashboard/parsers.py` line 75 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-NIjghdy3LURc6enu3e6:-NIjghdy3LURc6enu3e7:b-2h3itv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cb798c4750ddedcc7a4fa7c2f056981bc8bf1589/sinks/dashboard/parsers.py#L75)):*
> ```Python
> 
>     for sensor, data in msg_data["data"].items():
>         parsed_messages.append(("DAQ|" + sensor, timestamp, sum(data)/len(data)))
> ```

I thought that we had previously decided to have just the sensor name instead of "DAQ|Sensor Name" to clean up the dashboard a little bit. Seems pretty obvious to me which sensors are coming from DAQ and which ones from CAN.
___
*[`sinks/dashboard/streams_test.py` line 1 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-NIjiGz02PeSjK7Lr73y:-NIjhgxqBBWekwHjdfUc:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cb798c4750ddedcc7a4fa7c2f056981bc8bf1589/sinks/dashboard/streams_test.py#L1)):*
> ```Python
> import pytest
> ```

See above
___
*[`sinks/dashboard/parsers_test.py` line 1 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-NIjiDlx-R89TBCihHag:-NIjiDlx-R89TBCihHah:bwqganv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cb798c4750ddedcc7a4fa7c2f056981bc8bf1589/sinks/dashboard/parsers_test.py#L1)):*
> ```Python
> import pytest
> ```

I don't see a ```pytest``` call anywhere, should there be one?

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-:-NInz7yGCQfERfdTOX-G:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @KavinSatheeskumar)

___
*[`sinks/dashboard/parsers_test.py` line 1 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-NIjiDlx-R89TBCihHag:-NInz1bj4aUExuXiiwrR:b-89q77x) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cb798c4750ddedcc7a4fa7c2f056981bc8bf1589/sinks/dashboard/parsers_test.py#L1)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Actually, no! Pytest does things like actually upon import. It sets up things that you use via the CLI. I am not going to explain all of pytest in this comment, but you can read here for more info.

https://www.guru99.com/pytest-tutorial.html
</blockquote></details>

Cool!

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/82#-:-NIpijmY5EgxmF585nt_:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @Darth-Raazi and @KavinSatheeskumar)

**Pull request merged**
