### PR TITLE
Sn3syed/128 make periodic can sender more obvious

### LINKED ISSUE #128: Make Periodic CAN Sender More Obvious
Right now, Periodic CAN Sender is literally just a checkbox, so for someone who hasn't used it before, it's not obvious what its purpose is. First, a text label or something needs to be added to make it clearer. For something more advanced, a switch graphic (or similar) with a clear on and off state to replace the checkbox would be nice

### PR DESCRIPTION
**Pull request by saads312**
## Description
Changed periodic CAN sender from a single checkbox to dedicated ON and OFF checkboxes which can be toggled, and made it more obvious that it's on.

I changed the number of checkboxes to better distinguish between ON and OFF. I added a label which says "Periodic CAN Sender", and changed the pulse widget to pulse red when ON is toggled, to make it more obvious which state it's in. 

This PR closes #128

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work Saad! Couple requests:
- The period should by default be a non-zero value (1 seems good?), meaning as soon as you add Periodic CAN Sender, it starts sending messages. Otherwise it's a bit unclear whether it's working or not. OR
- When the period is 0, add an "INACTIVE" label below the title. This way you can add Periodic CAN Sender to the dashboard and not have it send any message, but it's clear that it's not sending messages. Thoughts?
- Neither the title nor the checkboxes are centred, this makes it look weird if you resize the widget. Just add a bit of centering so resizing doesn't break the look
- This is a nitpick but generally checkboxes imply multi-select. A radio button usually implies single-select exclusivity to the user, maybe we can use that

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-:-NyYEWSl1m5gf99v9zkl:bj3y75k)* status: all files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @KavinSatheeskumar, and @saads312)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NyYGRwnBnfVwQ1GWDfN:-NyYGRwnBnfVwQ1GWDfO:bzhho0z) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ca5ae61a11f040e921ce6fbb4459272a3bd5eac0/sinks/dashboard/items/periodic_can_sender.py#L3)):*
> ```Python
> from pyqtgraph.Qt.QtWidgets import QHBoxLayout, QCheckBox, QLabel
> from pyqtgraph.Qt.QtCore import Qt, QTimer
> from PySide6.QtWidgets import QButtonGroup, QVBoxLayout
> ```

Are these not available in `pyqtgraph.Qt.QtWidgets`?

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Looks amazing, just left a few small comments

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-:-NycO8y21BksK5gP5ReD:b-mag0cn)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @saads312)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NyYGRwnBnfVwQ1GWDfN:-NycN0F2ET3oFHTOHumn:b13g8ad) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ca5ae61a11f040e921ce6fbb4459272a3bd5eac0/sinks/dashboard/items/periodic_can_sender.py#L3)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Are these not available in `pyqtgraph.Qt.QtWidgets`?
</blockquote></details>

Following up on this, we generally wanna import all our Qt stuff from the same place. If both these classes aren't available in `pyqtgraph.Qt.QtWidgets` then we'll keep this, but otherwise it would be best to import them from there
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 59 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NycNIXZ7xzCt3sujcs7:-NycNIXZ7xzCt3sujcs8:buqs6jx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/73a489c282e12dfffc70057ced3b62dfb44e4c3c/sinks/dashboard/items/periodic_can_sender.py#L59)):*
> ```Python
>         self.pulse_count = 0
>         self.pulse_period = 300  # ms
> ```

Extra blank line not needed
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 100 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NycNjOE-_Bq1qiIegrh:-NycNjOE-_Bq1qiIegri:b-ar6ijb) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/73a489c282e12dfffc70057ced3b62dfb44e4c3c/sinks/dashboard/items/periodic_can_sender.py#L100)):*
> ```Python
>         if self.pulse_count > 0:
>             if self.period != 0 and self.pulse_count % 2 == 0:
>                 self.setStyleSheet("background-color: red;")
> ```

The flashing red should only happen if it's active and on (the idea is to quickly catch your eye if it's on because that means something is gonna get actuated. Helpful if you accidentally turn it on). If it's off we can have the `ACTIVE` label, but the flashing isn't needed

**Review by patrick-gu — CHANGES_REQUESTED** [review]
Excellent improvements. The layout makes it much more clear. Just some small things to consider. Overall, to make it clear what is happening:
- The user needs to know, from the radio boxes and the text, whether the sender is configured to send messages, and whether they are to open or close
- From the red pulses, the user needs to be able to tell that we are sending messages to open

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-:-NypgvPCEARMIFr5ku10:b-39xxwe)* status: all files reviewed, 8 unresolved discussions (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 34 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NypY55mEH7WMuCzxH3i:-NypY55mEH7WMuCzxH3j:bu4v5o9) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L34)):*
> ```Python
>         self.layout.addWidget(self.label)
> 
>         self.check_on = QRadioButton("ON")
> ```

Consider changing the terminology in the code to also refer to radio boxes
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 35 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NypiHaoAjUDDOhi0p5z:-NypiHaoAjUDDOhi0p6-:b-bev8ux) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L35)):*
> ```Python
> 
>         self.check_on = QRadioButton("ON")
>         self.check_off = QRadioButton("OFF")
> ```

I think this should probably be open/closed and not on/off, since we're still sending messages even if the valve should be closed
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 106 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NypdYFJEImDPXWDxIZ3:-NypdYFJEImDPXWDxIZ4:b-btwm64) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L106)):*
> ```Python
>                     self.status_label.setText("ACTIVE")
>                 elif self.period == 0:
>                     self.status_label.setText("INACTIVE")
> ```

I feel like it's not right to set ACTIVE/INACTIVE text in here because it should reflect the state of the sender based on the settings, and not be associated with the pulses
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 109 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-Nype7bG1p8hQkHgVXnv:-Nype7bG1p8hQkHgVXnw:b-qg7l7x) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L109)):*
> ```Python
>             self.pulse_count -= 1
>         else:
>             self.pulse_timer.stop()
> ```

Setting the period to 0 doesn't cause the text to say INACTIVE for me, which I assume is not the intended behaviour
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 112 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NypczB68-S3fvQATnN7:-NypczB7AclGo_CUeWLT:b-f2hi5q) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L112)):*
> ```Python
> 
>     def on_period_change(self, _, value):
>         self.period = value
> ```

This isn't a new problem, but could we do a check that the period is not negative? The dashboard seems to freeze up if I accidentally do that.

**Review by Darth-Raazi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224)* status: all files reviewed, 6 unresolved discussions (waiting on @BigLiban, @BluCodeGH, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 35 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NypiHaoAjUDDOhi0p5z:-NyppibQ0ruRKc2eW4dL:b-t6czud) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L35)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I think this should probably be open/closed and not on/off, since we're still sending messages even if the valve should be closed
</blockquote></details>

Not all of Period CAN Sender's targets are valves though. I think On/Off is fine for now
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 106 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NypdYFJEImDPXWDxIZ3:-NypvR0Y7zVbcXTUT6ZL:b-urcxut) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L106)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I feel like it's not right to set ACTIVE/INACTIVE text in here because it should reflect the state of the sender based on the settings, and not be associated with the pulses
</blockquote></details>

Good point, maybe we can make a `set_status()` method?
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 109 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-Nype7bG1p8hQkHgVXnv:-Nypv_V_4HFhMzcayOuo:b-tce5bw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L109)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Setting the period to 0 doesn't cause the text to say INACTIVE for me, which I assume is not the intended behaviour
</blockquote></details>

Hmm yeah I'm seeing this as well. I set period 0 --> 3 --> 0 and it doesn't go back to INACTIVE
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 112 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NypczB68-S3fvQATnN7:-Nypw-CU-kpvCblpYQk5:b1vej29) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b73070e1bde305a1f7f3952a31669599bf49cd92/sinks/dashboard/items/periodic_can_sender.py#L112)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

This isn't a new problem, but could we do a check that the period is not negative? The dashboard seems to freeze up if I accidentally do that.
</blockquote></details>

Good catch, need to add bad input handling

**Review by patrick-gu — APPROVED** [review]
One small change for brevity, but otherwise seems good to me!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-:-Nz9enEUEg8-N4xNtXjv:b3ghbkz)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 114 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-Nz9ePex5RaowZHyi_bG:-Nz9ePex5RaowZHyi_bH:b-5yfmmv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/804fe0e60aec53264ca5fda907e87f97ce5d2636/sinks/dashboard/items/periodic_can_sender.py#L114)):*
> ```Python
>             self.status_label.setText("ACTIVE")
>         elif self.radio_off.isChecked() and self.period != 0:
>             self.status_label.setText("ACTIVE")
> ```

I think this should just be active if period != 0, inactive if period == 0

**Review by saads312 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @patrick-gu)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NyYGRwnBnfVwQ1GWDfN:-Nz9pawy-c4FlEQNB-yq:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ca5ae61a11f040e921ce6fbb4459272a3bd5eac0/sinks/dashboard/items/periodic_can_sender.py#L3)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Following up on this, we generally wanna import all our Qt stuff from the same place. If both these classes aren't available in `pyqtgraph.Qt.QtWidgets` then we'll keep this, but otherwise it would be best to import them from there
</blockquote></details>

Done.
___
*[`sinks/dashboard/items/periodic_can_sender.py` line 114 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-Nz9ePex5RaowZHyi_bG:-Nz9pZ0D-KhNsjNbmtcO:b-u9sid2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/804fe0e60aec53264ca5fda907e87f97ce5d2636/sinks/dashboard/items/periodic_can_sender.py#L114)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I think this should just be active if period != 0, inactive if period == 0
</blockquote></details>

True, changing now

**Review by patrick-gu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> Dismissed @Darth-Raazi from a discussion.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-:-Nz9qyft4FGytmPZXkg9:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, and @Lucifersan)

___
*[`sinks/dashboard/items/periodic_can_sender.py` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NyYGRwnBnfVwQ1GWDfN:-Nz9qsmj2km4lTJxaFgg:b192hea) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ca5ae61a11f040e921ce6fbb4459272a3bd5eac0/sinks/dashboard/items/periodic_can_sender.py#L3)):*
<details><summary><i>Previously, saads312 (Saad Syed) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yeah I don't think they're available in there, just checked

**Comment by saads312** [comment]
*[`sinks/dashboard/items/periodic_can_sender.py` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-NyYGRwnBnfVwQ1GWDfN:-Nz9p1CFCmzD9JO30p-e:b943yjy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ca5ae61a11f040e921ce6fbb4459272a3bd5eac0/sinks/dashboard/items/periodic_can_sender.py#L3)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Yeah I don't think they're available in there, just checked
</blockquote></details>

Everything that I could move to the same import, I did, it should be fine now.

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Nice fixes. Did you change anything about the sizing? Looks smaller and the radio buttons are cutoff at the bottom...


> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-:-NzBDNd2Cy_yn25fm8De:b-85z479)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @BluCodeGH, @KavinSatheeskumar, and @Lucifersan)

**Comment by saads312** [comment]
Doesn't show that way to me. I also didn't touch anything to do with the sizing so not sure what's causing that

**Review by Darth-Raazi — APPROVED** [review]
Huh weird, must be a local thing. 
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/224#-:-NzKS_aV7o-yk5MfYm6y:b-vlp4a9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @BluCodeGH, @KavinSatheeskumar, and @Lucifersan)

**Pull request merged**
