### PR TITLE
Implement #209, add progress bar item for Dashboard

### LINKED ISSUE #209: Progress Bar Item
For readings such as tank fill level, we want a progress bar item that fills up linearly as the value increases (and empties as it decreases). We should be able to set the bounds (what value is 0%/empty and 100%/full) and there should also be a numerical readout of the value in the middle of the progress bar or below it

### PR DESCRIPTION
**Pull request by zangjiucheng**
## Description
Implement Progress Bar for Dashboard. (Example use: For fuel injection progress visual view) 
Code learned style from Gauge Design, Thanks! 

Demo view:
Pasted Graphic

New feature: 
- Adjustable Max/Min 
- Adjustable labels
- Convenient content for data entry sources

Changed:
- Nothing Delete
- add the new file for the progress bar class `./sinks/dashboard/items/progress_bar.py`

This PR closes #209.

## Developer Testing

Here's what I did to test my changes:

- Test Change Label 
- Test Manual Input Value for check process bar changing

## Reviewer Testing

Here's what you should do to validate my changes quickly:
- The commit code is located under `./sinks/dashboard/items/progress_bar.py` is used to manually change the percentage value displayed by the progress bar rendering.
```py
 # Initialize with 70% progress
 # self.data = (self.max_value+self.min_value)*0.7
 # self.update_data()
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
Looks amazing, and I really like the aesthetic. It conveys the data well.

Just a few small suggestions.

Also, I think we should ask @Darth-Raazi about the default size of the bar? I'm not really sure what's a reasonable number, but it seems pretty big to me right now.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-:-NzpVgTnDYX9iXmsrg9O:b-caghqk)* status: all files reviewed, 4 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/progress_bar.py` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpVAAZ9IkwXS0L2z15:-NzpVAAZ9IkwXS0L2z16:b-o67sxq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ac05077e0fc733cecdc2e6b1dba38e54d90d6476/sinks/dashboard/items/progress_bar.py#L44)):*
> ```Python
>         # Initialize with 70% progress
>         # self.data = (self.max_value+self.min_value)*0.7
>         # self.update_data()
> ```

I tested it with fakeni data
___
*[`sinks/dashboard/items/progress_bar.py` line 108 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpV1YbBrrZtwg5c4ll:-NzpV1YbBrrZtwg5c4lm:b-k71oix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ac05077e0fc733cecdc2e6b1dba38e54d90d6476/sinks/dashboard/items/progress_bar.py#L108)):*
> ```Python
>         self.data = 0
>         self.min_value = 0
>         self.max_value = 100
> ```

I think for consistency, these should be floats, and the max value should be 10.0
___
*[`sinks/dashboard/items/progress_bar.py` line 147 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpVyyn3QzgEXUwBv6P:-NzpVyyn3QzgEXUwBv6Q:btwccfw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ac05077e0fc733cecdc2e6b1dba38e54d90d6476/sinks/dashboard/items/progress_bar.py#L147)):*
> ```Python
>         if self.label:
>             painter.setPen(QColor(0, 0, 0))
>             painter.setFont(QFont("Arial", 12))
> ```

I don't think this should necessarily be Arial because it might not be available on all computers
___
*[`sinks/dashboard/items/progress_bar.py` line 147 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpWoA48LQt253_uIS_:-NzpWoA48LQt253_uISa:bisqu1h) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ac05077e0fc733cecdc2e6b1dba38e54d90d6476/sinks/dashboard/items/progress_bar.py#L147)):*
> ```Python
>         if self.label:
>             painter.setPen(QColor(0, 0, 0))
>             painter.setFont(QFont("Arial", 12))
> ```

Also consider making the text scale with the widget

**Comment by zangjiucheng** [comment]
OK, thanks for your detail review and suggestion, I will try to fix all these later a bit today! :))

**Review by patrick-gu — CHANGES_REQUESTED** [review]
A few more comments

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-:-NzpiGkC0U6R-JRng1PG:b-lsf88d)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/progress_bar.py` line 147 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpVyyn3QzgEXUwBv6P:-NzpgZs-2M2Bt-wO0uq2:bcoi3zl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ac05077e0fc733cecdc2e6b1dba38e54d90d6476/sinks/dashboard/items/progress_bar.py#L147)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I don't think this should necessarily be Arial because it might not be available on all computers
</blockquote></details>

I will change it to do this
```py
font = QFont()
font.setPointSize(...)
painter.setFont(font)
```
Because right now I get this error
```
DirectWrite: CreateFontFaceFromHDC() failed (Indicates an error in an input file such as a font file.) for QFontDef(Family="MS Sans Serif", pointsize=19, pixelsize=25, styleHint=5, weight=400, stretch=100, hintingPreference=0) LOGFONT("MS Sans Serif", lfWidth=0, lfHeight=-25) dpi=96
```
___
*[`sinks/dashboard/items/progress_bar.py` line 147 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpWoA48LQt253_uIS_:-NzphwaEDmJ-JC1vikNI:b-cgcb8e) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ac05077e0fc733cecdc2e6b1dba38e54d90d6476/sinks/dashboard/items/progress_bar.py#L147)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Also consider making the text scale with the widget
</blockquote></details>

The text gets cut off if the box is really tall. Not a big deal because nobody would ever use it like that but would be nice to fix
___
*[`sinks/dashboard/items/progress_bar.py` line 122 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpgMMTCahmKkyVS5tU:-NzpgMMTCahmKkyVS5tV:b7wwivt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a31cb74f9cb1acbdfc545568340dac38ec017db0/sinks/dashboard/items/progress_bar.py#L122)):*
> ```Python
> 
>         width: float = self.width()
>         height: float = self.height()
> ```

These are actually `int`s

**Comment by zangjiucheng** [comment]
OK, I see, I will just change formula to compute it. Thanks!

**Review by patrick-gu — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @zangjiucheng)

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Really impressed by your work on this, it looks amazing! Three thoughts:
- Your gradient fill-up colour looks really cool, but our launch is outside and in less-than-ideal viewing conditions, so it might be hard to see sometimes. Can you add an option for the fill colour to just be solid and the user can pick the colour? How you have it now can stay as the default, but that option should be there just in case
- Can you move the text label below the progress bar and make the numerical readout in the center bigger? Also be mindful on font colour, in dark mode it can be kinda hard to read the number when it's not filled up
- How much work would it be to add a "vertical" option? This isn't necessary for the functionality, but it would be nice to let the user choose whether they want a vertical or a horizontal progress bar

> Reviewed 1 of 1 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-:-O-4r2FV44Ou4rrtzF26:bv12kfk)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/items/progress_bar.py` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-NzpVAAZ9IkwXS0L2z15:-O-4qaso7nzDlG3KbRW6:b-v1d3vm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ac05077e0fc733cecdc2e6b1dba38e54d90d6476/sinks/dashboard/items/progress_bar.py#L44)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I tested it with fakeni data
</blockquote></details>

No commented out code please, as Patrick mentioned we can test with Fakeni

**Comment by zangjiucheng** [comment]
@Darth-Raazi I followed your suggestion and update process bar. 
New Feature with: 
- With Multi-Colors can be choose to use in the process bar. (Let me know which not looks good I will change that)
- Implement Vertical Mode (It's functional working,but not suggetion, it's not enough for information)
- Move Label outside the progress bar, and zoom the percent number inside of that.

**Comment by patrick-gu** [comment]
I think you could make the label text a bit bigger, although probably not too big since we might need to put a lot of text sometimes

**Comment by zangjiucheng** [comment]
Thanks for the comment, it helped me a lot, lol !

I agree that you should make that larger a bit for us easy to check!

I'm just having some trouble setting the progress bar to be larger than the label text in vertical mode. If I set it manually, .... some error will occur. I don't think I have a solution for that yet :(

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
- I think default sizes should be 200x100 for horizontal and 100x200 for vertical
- In horizontal mode, the label is a bit too big
- In vertical mode, the label is way too big and the bar is too wide. Also, there's no numerical value for me. The horizontal and vertical modes should be rotations of each other, the bar and text sizes shouldn't change, just swap (i.e. horizontal mode bar width becomes vertical bar height and vice versa)
- Small thing, but can the colour picker in the parameters be collapsed by default?

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-:-O-K8aVlAR-2mdobCtKO:bkzbc23)* status: all files reviewed, 9 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/progress_bar.py` line 24 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-K9ZCT6pXwkACXUKQx:-O-K9ZCT6pXwkACXUKQy:b-v5rupg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L24)):*
> ```Python
>         
>         self.widget = ProgressBarWidget(self)
>         # self.widget.setMinimumSize(180, 30)  # Set the minimum size of the ProgressBarWidget
> ```

Stale comment?
___
*[`sinks/dashboard/items/progress_bar.py` line 90 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-K9sw8-fPZw_4KcIr8:-O-K9sw8-fPZw_4KcIr9:b-d58btl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L90)):*
> ```Python
>             for i in reversed(range(self.layout.count())):
>                 self.layout.itemAt(i).widget().setParent(None)
>             self.resize(120, 260)
> ```

Resize shouldn't be to a hard-coded value, rather it should read the current width/height and make those values the new height/width
___
*[`sinks/dashboard/items/progress_bar.py` line 93 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-KA7oMBXXBE9mgmIPf:-O-KA7oMBXXBE9mgmIPg:b-8inj34) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L93)):*
> ```Python
>             self.widget = VerticalProgressBarWidget(self)
>             self.label_widget = LabelWidget(self, vertical_mode=True)
>             self.layout.addWidget(self.widget)
> ```

Any identical functions calls can be pulled out of the if else statement so they're not duplicated
___
*[`sinks/dashboard/items/progress_bar.py` line 99 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-KA-GADj719y53JyGP:-O-KA-GADj719y53JyGQ:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L99)):*
> ```Python
>             for i in reversed(range(self.layout.count())):
>                 self.layout.itemAt(i).widget().setParent(None)
>             self.resize(200, 85)
> ```

See above
___
*[`sinks/dashboard/items/progress_bar.py` line 160 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-KALWLCgjSNZs1QPLf:-O-KALWLCgjSNZs1QPLg:bsta20x) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L160)):*
> ```Python
>         height: int = self.height()
>         if self.vertical_mode:
>             scale_factor: float | int = min(width, height/2.5) / 32
> ```

Can you please put a comment explaining how this formula was derived?
___
*[`sinks/dashboard/items/progress_bar.py` line 164 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-KAPtF2IYblGU_C-4U:-O-KAPtF2IYblGU_C-4V:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L164)):*
> ```Python
>             scale_factor: float | int = min(width/2.5, height) / 32 # size of the progress bar
>         
>         font_percent = 1.2 - ((min(len(self.label),50) / 50))
> ```

See above
___
*[`sinks/dashboard/items/progress_bar.py` line 166 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-KAQmg-WYjp1UVgFOn:-O-KAQmg-WYjp1UVgFOo:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L166)):*
> ```Python
>         font_percent = 1.2 - ((min(len(self.label),50) / 50))
>         
>         font_size = 6 + (23-6)*font_percent*scale_factor
> ```

See above
___
*[`sinks/dashboard/items/progress_bar.py` line 254 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-KAWyxBWgfzjOg0kWa:-O-KAWyxBWgfzjOg0kWb:b-c5rrsz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d1cd559c239f5bda6f16069a04a7089c9616fa1e/sinks/dashboard/items/progress_bar.py#L254)):*
> ```Python
>         self.update()
>         
> class VerticalProgressBarWidget(QWidget):
> ```

A lot of stuff in this class is the same as `ProgressBarWidget`, can you make it inherit that class and only overwrite the functions that need to be different?

**Comment by zangjiucheng** [comment]
@Darth-Raazi 
Implement the following features: 
- Set widgets 3x large as label size
- Default size (200,100)
- Dynamic change widget size based on width and height (instead of hard code).
- Compress code blocks at conditional runtime 
- Add commits to formulas for calculating font sizes
- VerticalProgressBarWidget Inherits from ProgressBarWidget (override paintEvent for later additions)
- Add vertical value reading (I wrote it as a fraction since the percentage style doesn't fit the vertical mode.
- The colour picker is collapsed by default.
- etc.

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Good work. In horizontal mode, the label is almost cutoff, can you make the bar a bit smaller so there's more room for the label? Also the fractions in vertical mode don't work, we want the percentage. You can make the font a bit smaller to fit it in the bar, remember the widest number you'll have is 100.0%


> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-:-O-Nzlqr16S3fkhnorZk:bsbfiwq)* status: all files reviewed, 11 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, @saads312, and @zangjiucheng)

___
*[`sinks/dashboard/items/progress_bar.py` line 65 at r10](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-O-KMoCzIl5wh8z1K0:-O-O-KMoCzIl5wh8z1K1:b-v5ruo0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9f8d5129b6751ecace1573862f67ef95d74f3c64/sinks/dashboard/items/progress_bar.py#L65)):*
> ```Python
>         # Test Code (Remove before merging)
>         # Initialize with 70% progress
>         # self.data = (self.max_value + self.min_value) * 0.7
> ```

Stale comments
___
*[`sinks/dashboard/items/progress_bar.py` line 182 at r10](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-O-RZP2oxJSWf2BYyp:-O-O-RZP2oxJSWf2BYyq:buqs6jx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9f8d5129b6751ecace1573862f67ef95d74f3c64/sinks/dashboard/items/progress_bar.py#L182)):*
> ```Python
> 
>         # Get minimum scale factor (sqrt(min(width, height)/30)) get scale around 1.0
>         
> ```

Extra blank line not needed
___
*[`sinks/dashboard/items/progress_bar.py` line 189 at r10](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-O-Thf6hQBOHvs1Hd9:-O-O-Thf6hQBOHvs1HdA:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9f8d5129b6751ecace1573862f67ef95d74f3c64/sinks/dashboard/items/progress_bar.py#L189)):*
> ```Python
>             
>         # Calculate font size based on label length between 0 and 60 characters (decrease as label length increases)
>         
> ```

See above
___
*[`sinks/dashboard/items/progress_bar.py` line 193 at r10](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-O-O-WRaD2krw9flHrHO:-O-O-WRaD2krw9flHrHP:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9f8d5129b6751ecace1573862f67ef95d74f3c64/sinks/dashboard/items/progress_bar.py#L193)):*
> ```Python
>         
>         # Set minimum font size to 6, maximum to 23 (based on scale factor)
>         
> ```

See above

**Comment by zangjiucheng** [comment]
@patrick-gu Thank you for your review! This should be the last submission for this implementation. Everything looks good now. I added margins to the bottom and changed the font calculation function. Let me know your thoughts! 
- Clean up code
- Vertical Mode with percentage
- Fix font size

**Review by Darth-Raazi — APPROVED** [review]
Awesome, I'm gonna approve this, just one last request: can you make the percentage white as well so it matches the label colour?

:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/229#-:-O-TY4_9EIb2R0Ls2ZsW:bndt19n)* status: all files reviewed, 11 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, @saads312, and @zangjiucheng)

**Comment by zangjiucheng** [comment]
Yep, I will do that small change before we merge it 🙃

**Pull request merged**
