### PR TITLE
Add CI with unit testing and code coverage

### LINKED ISSUE #24: Add CI
It would be nice to have CI that runs our unit tests on each PR so that we don't need to test them independently. Topside has this set up and the config can probably be directly copied.

### PR DESCRIPTION
**Pull request by BluCodeGH**
Fixes #24 

This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25)

### CODE REVIEW

**Comment by BluCodeGH** [comment]
I'm not a big fan of the noise from codecov, thoughts on if we need it?

**Comment by jacobdeery** [comment]
It's not essential, Wendi and I just found the stats useful for Topside. If you like the coverage stats but not the bot comments, you can just [disable](https://docs.codecov.com/docs/pull-request-comments#disable-comment) the bot. Otherwise you can remove it entirely.

**Review by wendi-yu — COMMENTED** [review]
CI seems to be working so it looks good to me, just wondering about the slack hook stuff

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25#-:-MjzuRRNB0yjx1bvx4uM:bxsizd4)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[.github/workflows/test.yml, line 24 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25#-MjztvDwBfdU83lw0wyJ:-MjztvDwBfdU83lw0wyK:b-lrc68v) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b63bf8bf6e8bce1c53da9f3749aa4136ab0c01a5/.github/workflows/test.yml#L24)):*
> ```YAML
>       id: cache
>       uses: actions/cache@v1
>       env: 
> ```

you've got a couple of trailing whitespaces sprinkled around
___
*[.github/workflows/test.yml, line 62 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25#-MjzudAhCXcmwEy2pXf3:-MjzudAhCXcmwEy2pXf4:b-rdfjap) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b63bf8bf6e8bce1c53da9f3749aa4136ab0c01a5/.github/workflows/test.yml#L62)):*
> ```YAML
>         autopep8 -d -r sources/ sinks/ omnibus/ --exit-code
> 
>     - uses: k0kubun/action-slack@v2.0.0
> ```

this stuff is for automatically sending a message to slack if CI fails on master, did you want that for omnibus? I didn't see the SLACK_WEBHOOK_URL set up in this repo's secrets so I wasn't sure if you want this or not

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jli35, @KavinSatheeskumar, @PCModeActivate, and @QuantumManiac)

___
*[.github/workflows/test.yml, line 24 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25#-MjztvDwBfdU83lw0wyJ:-MkImerkE54Oa-SEVjOz:b-886gsx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b63bf8bf6e8bce1c53da9f3749aa4136ab0c01a5/.github/workflows/test.yml#L24)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

you've got a couple of trailing whitespaces sprinkled around
</blockquote></details>

Fixed
___
*[.github/workflows/test.yml, line 62 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25#-MjzudAhCXcmwEy2pXf3:-MkImhLy3NGUBqGeRM7d:b-6bmiro) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b63bf8bf6e8bce1c53da9f3749aa4136ab0c01a5/.github/workflows/test.yml#L62)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

this stuff is for automatically sending a message to slack if CI fails on master, did you want that for omnibus? I didn't see the SLACK_WEBHOOK_URL set up in this repo's secrets so I wasn't sure if you want this or not
</blockquote></details>

It's a pain to set up a webhook (and they are supposedly going to be deprecated), I trust branch protection enough to do without.

**Review by QuantumManiac — APPROVED** [review]
Assuming all the formatting is proper (which it does look so but I don't know PEP 8 too well to know for sure), :lgtm:

> Reviewed 1 of 4 files at r1, 5 of 10 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/25#-:-MkSR9127RWeZsehVp8L:bz30m6w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jli35, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Pull request merged**
