### PR TITLE
PR Template

### PR DESCRIPTION
**Pull request by Darth-Raazi**
Added a basic PR template. I want this to provide some structure/guidance but not be a chore to fill out and annoy everyone. Note that only the template on the default branch (`master`) gets auto-filled in for PRs so there's no way to test this until it gets merged. Please provide feedback on the sections.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167)* status: all files reviewed, 3 unresolved discussions (waiting on @Darth-Raazi and @KavinSatheeskumar)

___
*[`.github/pull_request_template.md` line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVHw6P6u9rVfEhMonN:-NiVHw6P6u9rVfEhMonO:bqgh8f9) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L1)):*
> ```Markdown
> # Omnibus Pull Request
> ```

I don't think this is a useful title to have on every PR, I'd remove it.
___
*[`.github/pull_request_template.md` line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVI2v64YQPUN_U3PmN:-NiVI2v64YQPUN_U3PmO:bi55dkt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L7)):*
> ```Markdown
> 
> 
> This PR closes #XXX
> ```

I'd put this as the last line of the description.
___
*[`.github/pull_request_template.md` line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVIAJZ5G-AQVk9VYGm:-NiVIAJZ5G-AQVk9VYGn:b-ke4i7m) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L19)):*
> ```Markdown
> ## Testing Info
> 
> 
> ```

What info do you expect to see here that's not included in "Tests Run"?

**Review by QuantumManiac — CHANGES_REQUESTED** [review]
Generally agree with @BluCodeGH 's points. Left some additional comments.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-:-NiVr6u1174qSN3VlZ_m:bf0dxcc)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`.github/pull_request_template.md` line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVIAJZ5G-AQVk9VYGm:-NiVqL7dDTDjnS8g--gN:b-ybhm6o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L19)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

What info do you expect to see here that's not included in "Tests Run"?
</blockquote></details>

I would imagine that "Tests Run" would be comprehensive testing by the author to test functionality while "Testing Info" would be steps that reviewers can take to test functionality in a bit more of a "make sure that things generally work how you'd expect them to" way? I do think that the titles for these two sections could be changed though.

**Review by Darth-Raazi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @QuantumManiac)

___
*[`.github/pull_request_template.md` line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVHw6P6u9rVfEhMonN:-NiZRh1s8cCV9_Zg7Cr_:b-7p5vga) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L1)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I don't think this is a useful title to have on every PR, I'd remove it.
</blockquote></details>

Added a title section to be changed. I'm not sure if this fills in the title of the PR or if it's just a title in the body section. If it's the latter, we can get rid of it.
___
*[`.github/pull_request_template.md` line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVI2v64YQPUN_U3PmN:-NiZS8-o4b38Kt0CT-Q_:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L7)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I'd put this as the last line of the description.
</blockquote></details>

Done
___
*[`.github/pull_request_template.md` line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVIAJZ5G-AQVk9VYGm:-NiZSCx10OPcg9pIMXy5:b5ajiaq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L19)):*
<details><summary><i>Previously, QuantumManiac (Chamath Wijesekera) wrote…</i></summary><blockquote>

I would imagine that "Tests Run" would be comprehensive testing by the author to test functionality while "Testing Info" would be steps that reviewers can take to test functionality in a bit more of a "make sure that things generally work how you'd expect them to" way? I do think that the titles for these two sections could be changed though.
</blockquote></details>

Yes exactly. I changed the names to `Developer Testing` and `Reviewer Testing` and added some comments describing the sections in more detail.

**Review by BluCodeGH — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167)* status: all files reviewed, 1 unresolved discussion (waiting on @Darth-Raazi, @KavinSatheeskumar, and @QuantumManiac)

___
*[`.github/pull_request_template.md` line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVHw6P6u9rVfEhMonN:-Ni_HOkrBqaWo2OU3inX:b-4mc619) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L1)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Added a title section to be changed. I'm not sure if this fills in the title of the PR or if it's just a title in the body section. If it's the latter, we can get rid of it.
</blockquote></details>

Pretty sure this is just the description

**Review by QuantumManiac — APPROVED** [review]
LGTM! Just remove the "Title" section and you should be good to go.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-:-NietmUKAKG1WfKAKK1x:bhd2z70)* status: all files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`.github/pull_request_template.md` line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/167#-NiVHw6P6u9rVfEhMonN:-NietTVGDSq70UncPhcz:bhzlmwt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/b72ba95dafbe1c32e99789ad51c21893a3f5ac32/.github/pull_request_template.md#L1)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Pretty sure this is just the description
</blockquote></details>

Can confirm. Should probably remove.

**Pull request merged**
