### PR TITLE
Add SPI driver

### PR DESCRIPTION
**Pull request by BluCodeGH**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2)

### CODE REVIEW

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @PCModeActivate, and @wendi-yu)

___
*[prototype/spi.py, line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaPJmdX84nfv1i5zIE0:-MaPJmdX84nfv1i5zIE1:bk06l4a) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/05a4ebb0ac3eaaa21914e50902fc537a7318be09/prototype/spi.py#L110)):*
> ```Python
>     mosidata = []
>     for byte_out in bytes_out:
>         # Since these are analog channels, a binary 1 is represented by 5 (volts).
> ```

Might wanna create a const OUT_VOLTAGE = 5, just in case that ever needs to change

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @PCModeActivate, and @wendi-yu)

___
*[prototype/spi.py, line 13 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVtk275jntCOfkH3d4:-MaVtk275jntCOfkH3d5:b4dpiga) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L13)):*
> ```
> import numpy
> ```
conventionally, `import numpy as np` to be concise
___
*[prototype/spi.py, line 56 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVvB_H14UfsOpZ-Gf8:-MaVvB_IAPxrWR-eEAwb:b-lokcj6) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L56)):*
> ```
> aow.write_many_sample(numpy.zeros((2, diff), dtype=numpy.float64))
> ```
Is there any risk of a race condition between this thread and `send`, which also writes from `aow`?
___
*[prototype/spi.py, line 56 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVwzGqArObLv1DbasD:-MaVwzGqArObLv1DbasE:b-eqfalu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L56)):*
> ```
> dtype=numpy.float64
> ```
I believe this is the default
___
*[prototype/spi.py, line 57 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVxHbDEqvy8P6LgYrU:-MaVxHbDEqvy8P6LgYrV:bmt25qw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L57)):*
> ```
> t += 1 / 8
> ```
Why was this value chosen?
___
*[prototype/spi.py, line 62 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVzFFV887jOr0tGagq:-MaVzFFV887jOr0tGagr:bd3704s) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L62)):*
> ```
> read
> ```
It's a bit confusing that the `read` function is what sends the data over Omnibus, especially when we have another function called `send`
___
*[prototype/spi.py, line 63 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVxKn8BfyUyLhPbDap:-MaVxKn8BfyUyLhPbDaq:b-9qx56c) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L63)):*
> ```
> lastMiso
> ```
last_miso
___
*[prototype/spi.py, line 83 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW0-qH5-jQUuhZMh9u:-MaW0-qH5-jQUuhZMh9v:b-7wkdt4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L83)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>         for i in range(len(sclk)):
>             if sclk[i] > SPI_VOLTAGE / 2: # Clock high, read a bit and add it to our WIP byte
>                 byte |= round(miso[i] / SPI_VOLTAGE) << bit
>                 if bit == 0:
>                     bit = 7
>                     bytes_in.append(byte)
>                     byte = 0
>                 else:
>                     bit -= 1
> ```
</details>

This little snippet is a good candidate to extract into a function for unit testing
___
*[prototype/spi.py, line 86 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVxYFg5efml66ZaFHP:-MaVxYFg5efml66ZaFHQ:bghaagg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L86)):*
> ```
> (d - 0.000505) * 6550
> ```
is this just a placeholder?
___
*[prototype/spi.py, line 91 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW-Mta1nIXvqar00M0:-MaW-Mta1nIXvqar00M1:b-acifly) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L91)):*
> ```
>             if len(spi_avg) == 1:
>                 spi_avg = [time.time() - spi_time for _ in range(100)]
> ```
Why not just initialize `spi_avg` to `[time.time() - spi_time for _ in range(100)]` up on line 69? Same thing for `analog_avg` below.
___
*[prototype/spi.py, line 94 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW11X78HVRWwx4RWNR:-MaW11X89QD2OzuUvTaj:b-uiq8ly) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L94)):*
> ```
> (time.time(), "SPI", bytes_in[:TEST_SPI_BYTES])
> ```
What exactly are we sending here?
___
*[prototype/spi.py, line 103 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVtrPy0kOlpfNaQdsH:-MaVtrPy0kOlpfNaQdsI:b-ec0wbp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L103)):*
> ```
> sum(analog_avg)/len(analog_avg)
> ```
can this be `np.mean(analog_avg)`? same for `spi_avg`

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @Huan-YiShen, @jacobdeery, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[prototype/spi.py, line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaPJmdX84nfv1i5zIE0:-MafYvqk3adsnEpfNrSm:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/05a4ebb0ac3eaaa21914e50902fc537a7318be09/prototype/spi.py#L110)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Might wanna create a const OUT_VOLTAGE = 5, just in case that ever needs to change
</blockquote></details>

Done.
___
*[prototype/spi.py, line 13 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVtk275jntCOfkH3d4:-MafXSPp4v0qG4BwhS7z:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L13)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> import numpy
> ```
conventionally, `import numpy as np` to be concise
</blockquote></details>

Done.
___
*[prototype/spi.py, line 56 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVvB_H14UfsOpZ-Gf8:-MafXVKe7pHrxxpbjX8M:bi4qqhr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L56)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> aow.write_many_sample(numpy.zeros((2, diff), dtype=numpy.float64))
> ```
Is there any risk of a race condition between this thread and `send`, which also writes from `aow`?
</blockquote></details>

Good point, I've never run into an issue but more synchronization primitives never hurt anyone, right? ... Right?
___
*[prototype/spi.py, line 56 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVwzGqArObLv1DbasD:-MafXm0GDp2V5X__OnLd:b-l8i2bw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L56)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> dtype=numpy.float64
> ```
I believe this is the default
</blockquote></details>

It complains about the data type when I remove this so I guess not.
___
*[prototype/spi.py, line 57 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVxHbDEqvy8P6LgYrU:-MafXu7616wUwfL7YOY6:b-vlizlm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L57)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> t += 1 / 8
> ```
Why was this value chosen?
</blockquote></details>

Clarified. The 0.25s value itself was chosen as a decent mix between latency and having a bit of breathing room in the buffer.
___
*[prototype/spi.py, line 62 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVzFFV887jOr0tGagq:-MafY-Ma7mIFOyS5UIHD:b-ec6gr4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L62)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> read
> ```
It's a bit confusing that the `read` function is what sends the data over Omnibus, especially when we have another function called `send`
</blockquote></details>

Renamed for clarity.
___
*[prototype/spi.py, line 63 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVxKn8BfyUyLhPbDap:-MafY1ra1d-TE19CFtot:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L63)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> lastMiso
> ```
last_miso
</blockquote></details>

Done.
___
*[prototype/spi.py, line 83 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW0-qH5-jQUuhZMh9u:-MafY3MYCFu9cSPyBS0j:be2ast0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L83)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>         for i in range(len(sclk)):
>             if sclk[i] > SPI_VOLTAGE / 2: # Clock high, read a bit and add it to our WIP byte
>                 byte |= round(miso[i] / SPI_VOLTAGE) << bit
>                 if bit == 0:
>                     bit = 7
>                     bytes_in.append(byte)
>                     byte = 0
>                 else:
>                     bit -= 1
> ```
This little snippet is a good candidate to extract into a function for unit testing
</blockquote></details>

Good idea, I think that's a bit out of scope for this prototype but will definitely do in the actual driver.
___
*[prototype/spi.py, line 86 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVxYFg5efml66ZaFHP:-MafYDZK1h5Vv6YwmH3Z:b-i1klp3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L86)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> (d - 0.000505) * 6550
> ```
is this just a placeholder?
</blockquote></details>

Yes, it's just a very rough calibration for use during prototyping as noted in the comment above.
___
*[prototype/spi.py, line 91 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW-Mta1nIXvqar00M0:-MafYM3h7tHZpUHEdwkc:b-kkf2qc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L91)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
>             if len(spi_avg) == 1:
>                 spi_avg = [time.time() - spi_time for _ in range(100)]
> ```
Why not just initialize `spi_avg` to `[time.time() - spi_time for _ in range(100)]` up on line 69? Same thing for `analog_avg` below.
</blockquote></details>

The whole output isn't great, I definitely want to find a more clever solution for the actual driver, but for now initializing with the first value means the average doesn't need to 'warm up'.
___
*[prototype/spi.py, line 94 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW11X78HVRWwx4RWNR:-MafYgFF2lcwYMg4aVi2:bro8hxb) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L94)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> (time.time(), "SPI", bytes_in[:TEST_SPI_BYTES])
> ```
What exactly are we sending here?
</blockquote></details>

Clarified slightly in code. In general this is just a very temporary message format that will be replaced with proper channels.
___
*[prototype/spi.py, line 103 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVtrPy0kOlpfNaQdsH:-MafYpMD1z0zoVGwnBqR:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L103)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> sum(analog_avg)/len(analog_avg)
> ```
can this be `np.mean(analog_avg)`? same for `spi_avg`
</blockquote></details>

Done.

**Review by jacobdeery — COMMENTED** [review]
I'll let Wendi take a look at this before approving

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-:-MafgwtT4tW__04FRGb1:b-27lpi4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[prototype/spi.py, line 56 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVwzGqArObLv1DbasD:-Mafg0f71g1teWuUfUsp:bpoevid) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L56)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

It complains about the data type when I remove this so I guess not.
</blockquote></details>

What's the error? [Numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) says float64 is default
___
*[prototype/spi.py, line 83 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW0-qH5-jQUuhZMh9u:-MafgA1---_sp39Km9WN:b-8fx2u7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L83)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Good idea, I think that's a bit out of scope for this prototype but will definitely do in the actual driver.
</blockquote></details>

:+1: 
___
*[prototype/spi.py, line 91 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaW-Mta1nIXvqar00M0:-Mafg_5T1l1i1W7lhJtF:bs9fvv2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L91)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

The whole output isn't great, I definitely want to find a more clever solution for the actual driver, but for now initializing with the first value means the average doesn't need to 'warm up'.
</blockquote></details>

Ok. This is fine for now.

**Review by BluCodeGH — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> Dismissed @KavinSatheeskumar and @jacobdeery from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @PCModeActivate, and @wendi-yu)

___
*[prototype/spi.py, line 110 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaPJmdX84nfv1i5zIE0:-MafylKq2t0jW3WededI:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/05a4ebb0ac3eaaa21914e50902fc537a7318be09/prototype/spi.py#L110)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[prototype/spi.py, line 56 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaVwzGqArObLv1DbasD:-MafyYC02t_WYDgCTgpp:b-fweaky) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L56)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

What's the error? [Numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) says float64 is default
</blockquote></details>

It's a typeerror, the dtype is int32 if I print it.

**Review by wendi-yu — COMMENTED** [review]
Embedded Python is my worst nightmare ;) (mostly kidding) but yeah looks good! Just one quick q about some of the numbers

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-:-MatNxqk727OUHQ0PCjQ:bskkabd)* status: all files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Huan-YiShen, and @PCModeActivate)

___
*[prototype/spi.py, line 86 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaWKAnn6x63wyuoUVUo:-MaWKAnn6x63wyuoUVUp:b-aup1bi) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L86)):*
> ```Python
> 
>         # Sample analog data 'calibration'.
>         data = (time.time(), "ANALOG", [[(d - 0.000505) * 6550 for d in data[0]]] + data[1:])
> ```

Wanna pull the numbers out into named variables here? Are they just arbitrary?

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen and @PCModeActivate)

___
*[prototype/spi.py, line 86 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-MaWKAnn6x63wyuoUVUo:-Matq0LbD1XeB0-1NDVX:bwbllo) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/834fda2e25aff511ee23a91f4a9e7533b43d4f81/prototype/spi.py#L86)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Wanna pull the numbers out into named variables here? Are they just arbitrary?
</blockquote></details>

Those numbers (very roughly) calibrate one of the s-type load cells into pounds for use during testing. I wouldn't worry about it, one of the big changes that will be made for the actual driver is a proper calibration mechanism so this will be thrown out.

**Review by wendi-yu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/2#-:-MbIeRhJ4RokkFPTIsqC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen and @PCModeActivate)

**Pull request merged**
