### PR TITLE
Implement item locking

### LINKED ISSUE #236: Locking widgets + stacking order
Very related to #200:
- We should be able to send widgets forward/backwards
- We should be able to lock widgets from interaction, and unlock from a menu

### PR DESCRIPTION
**Pull request by patrick-gu**
## Description

- Keep a list of locked items
- Can lock items from their menu or from the top menu
- Can unlock items from the top menu

Includes some code restructuring

This PR closes #236.

## Developer Testing

Here's what I did to test my changes:

- Add a bunch of items
- Try locking them
- Try selected and locking groups of them
- Try unlocking them from the menu
- Try locking and unlocking the whole dashboard
- Saved and loaded the dashboard
- Ensure the locking order remained consistent throughout all operations

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Try locking and unlocking some items

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239)

### CODE REVIEW

**Comment by patrick-gu** [comment]
For some reason the "lock" button appears at the bottom of the settings for plots, and I don't know what to do about it. Functionally I don't think there's a problem but it's definitely a bit annoying

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Works perfectly. For me, the "lock" button appears at the top for plots but at the bottom for gauges. I honestly don't think we need locking the parameter trees, just from the main menu is fine. Also when you lock two of the same items, the unlock items menu just displays "Unlock <item>" multiple times. Can you make it so that it numbers items for more clarity?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-:-O029sBZ8o5JRARZc2EF:b-hojl1h)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 225 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-O02ARnO-ZoyGHv-1TvY:-O02ARnO-ZoyGHv-1TvZ:b-va1a8v) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4ca65f1b9220ca778d1a8051f3a296076644e34c/sinks/dashboard/dashboard.py#L225)):*
> ```Python
>         self.lockableActions.append(lock_selected)
>         self.unlock_items_menu = add_lock_menu.addMenu("Unlock Items")
>         """Menu containing actions to unlock items that are locked, in the order
> ```

Comments for variables should go above and I would prefer using `#` even for multi-line comments. `"""` are generally used for function docstrings
___
*[`sinks/dashboard/items/dashboard_item.py` line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-O02Axwf6dOrCYH6kN5U:-O02Axwf6dOrCYH6kN5V:buqhy61) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4ca65f1b9220ca778d1a8051f3a296076644e34c/sinks/dashboard/items/dashboard_item.py#L7)):*
> ```Python
> import json
> from typing import Callable
> ```

Extra line not needed

**Review by patrick-gu — COMMENTED** [review]
I removed the lock button.

Numbering them would be pointless in my opinion because if you want to unlock the second widget you can just go to the second one and unlock it. Perhaps a better solution is being able to actually give widgets a name that is saved, but I think that is beyond the scope of this PR. I could maybe make it based off position? But I don't think that would be really useful because the coordinates are ridiculous large numbers.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-:-O02HzXtDO-sn2g6HdcA:bcp3hkh)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 225 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-O02ARnO-ZoyGHv-1TvY:-O02G7bd9H2BVwVJWfQV:b-o1mj6x) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4ca65f1b9220ca778d1a8051f3a296076644e34c/sinks/dashboard/dashboard.py#L225)):*
This method of documentation is correct according to PEP 257: https://peps.python.org/pep-0257/
> 1.  String literals occurring immediately after a simple assignment at the top level of a module, class, or `__init__` method are called “attribute docstrings”.
___
*[`sinks/dashboard/items/dashboard_item.py` line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-O02Axwf6dOrCYH6kN5U:-O02FwMVBGCNISCbRy7W:bdzq2vo) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4ca65f1b9220ca778d1a8051f3a296076644e34c/sinks/dashboard/items/dashboard_item.py#L7)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Extra line not needed
</blockquote></details>

I grouped the imports. The blank lines should be present according to PEP 8: https://peps.python.org/pep-0008/#imports

**Review by Darth-Raazi — APPROVED** [review]
Fair enough, this can be addressed later
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-:-O02LENg5JkBGkPKIEc2:bc7oxq1)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 225 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/239#-O02ARnO-ZoyGHv-1TvY:-O02LQUt5pZBw-31ilQl:b11d0pl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4ca65f1b9220ca778d1a8051f3a296076644e34c/sinks/dashboard/dashboard.py#L225)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

This method of documentation is correct according to PEP 257: https://peps.python.org/pep-0257/
> 1.  String literals occurring immediately after a simple assignment at the top level of a module, class, or `__init__` method are called “attribute docstrings”.
</blockquote></details>

Huh I didn't know that. Nice!

**Pull request merged**
