### PR TITLE
Plotter reformat

### PR DESCRIPTION
**Pull request by PCModeActivate**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56)

### CODE REVIEW

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/plot/config.py` line 16 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3Au3lBDAukX4BedMo-:-N3Au3lBDAukX4BedMo0:bwpa7r1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/config.py#L16)):*
> ```Python
> # This assumes the names of series are correct!
> # The order is implicit - Left to Right and then Up to Down
> INIT_SERIES_NAMES = [
> ```

This file stores some constants that we have yet to migrate; the INIT_SERIES_NAMES is deprecated
___
*[`sinks/plot/dock_widget.py` line 2 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AuF1aC8V0R88xbfyL:-N3AuF1b9PSFT-coFZch:b-v72rxf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/dock_widget.py#L2)):*
> ```Python
> """
> This example demonstrates the use of pyqtgraph's dock widget system.
> ```

Pyqt example code (with some adaptation for our dockarea)
___
*[`sinks/plot/parsers.py` line 42 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3Aud7H75i-swQG5hif:-N3Aud7H75i-swQG5hig:b2votcm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/parsers.py#L42)):*
> ```Python
> 
>     @staticmethod
>     def get_all_series():
> ```

This method listens in on all series it can find; it used to be called at callback every time in the dashboard, but it should only be called during add button of plotitem now
___
*[`sinks/plot/parsers.py` line 49 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AvGuI5jLRElkX9nG-:-N3AvGuI5jLRElkX9nG0:b-7mpvuw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/parsers.py#L49)):*
> ```Python
> 
>     @staticmethod
>     def get_series(channel, name):
> ```

This method should return the serie with the correct channel/name, the return object should be the series 
___
*[`sinks/plot/items/dashboard.py` line 1 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AzfHH6v1QfYOhDcgG:-N3AzfHH6v1QfYOhDcgH:b-5c89mf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L1)):*
> ```Python
> import signal
> ```

Ill annotate this file at a later publish

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56)* status: 0 of 7 files reviewed, 16 unresolved discussions (waiting on @BluCodeGH and @PCModeActivate)

___
*[`sinks/plot/config.py` line 12 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AzD__4rJnx3sAwPrj:-N3AzD_a78n1_k3lafQ-:bzcib9y) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/config.py#L12)):*
> ```Python
> ITEMS_PER_ROW = WINDOW_SIZE_X // DOCK_SIZE_X
> ITEMS_PER_COLUMN = WINDOW_SIZE_Y // DOCK_SIZE_Y
> ```

Is this file still being used?
___
*[`sinks/plot/dock_widget.py` line 13 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3Aw2U0B3PIMs2M5rCK:-N3Aw2U0B3PIMs2M5rCL:b-tofjxy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/dock_widget.py#L13)):*
> ```Python
> would consist of dockable components.
> """
> ```

I thought this was a demonstration file to explain how Dock Widgets work. Do we still need it in the final PR?
___
*[`sinks/plot/items/dashboard.py` line 27 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AwYdrB2HYUZ2yP32c:-N3AwYdrB2HYUZ2yP32d:b-c8eggc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L27)):*
> ```Python
> class Dashboard:
>     """
>     Displays a grid of plots in a window
> ```

Change the comment to "... dashboard items ..." in a window
___
*[`sinks/plot/items/dashboard.py` line 31 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AwdMqAejKmx1Z_jiD:-N3AwdMqAejKmx1Z_jiE:bufae8o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L31)):*
> ```Python
>     
>     def load():
>         savefile = open("savefile.sav", 'rb') 
> ```

maybe give it an optional parameter or put the file name in the config or something
___
*[`sinks/plot/items/dashboard.py` line 34 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AwtdeDHJRa291LdU5:-N3AwtdeDHJRa291LdU6:b802u0b) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L34)):*
> ```Python
>         self.data = pickle.load(savefile)
>         for i, item in data["items"]: # { 0: {...}, 1: ..., ...}
>         if item["class"] == "PlotDashItem":
> ```

You had probably ought indent this entire if-statement
___
*[`sinks/plot/items/dashboard.py` line 45 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3Aybe-8OLhjNg0jTVx:-N3Aybe-8OLhjNg0jTVy:bmbrh1b) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L45)):*
> ```Python
>                 self.area.addDock(dock, 'right', self.anchor)
>                 self.anchor = dock
>         restoreLayout(file)
> ```

This function doesn't take an argument?
___
*[`sinks/plot/items/dashboard.py` line 48 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AwyJm9Hrf29wYq0KH:-N3AwyJn3yEoAh1xpQcL:b-yfrk5v) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L48)):*
> ```Python
>     
>     def save():
>         savefile = open("savefile.sav", 'wb')
> ```

same as above, especially important for this, cuz it'd be nice to have a bunch of pre-built dashboards ready
___
*[`sinks/plot/items/dashboard.py` line 122 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AyzdqCNbKN_0-Daso:-N3AyzdqCNbKN_0-Dasp:bhhscho) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L122)):*
> ```Python
> 
> 
> class Plot:
> ```

I think we should move this class and "PlotDashItem" to their own file called "plot_item.py" or something
___
*[`sinks/plot/items/item.py` line 18 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AyngC6VqGyfZi4fmG:-N3AyngC6VqGyfZi4fmH:b-48ljtn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/item.py#L18)):*
> ```Python
>         raise NotImplementedError
> 
>     def save(self) -> typing.Any:
> ```

Might be better to rename this to "get_properties"
___
*[`sinks/plot/items/item.py` line 26 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AyT8x3yxvZw5bNFuG:-N3AyT8x3yxvZw5bNFuH:b5j02r2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/item.py#L26)):*
> ```Python
>     def child(self) -> QWidget:
>         """
>         Return Qt Widget that encompasses this DashboardItem
> ```

Return the QT Widget that *is contained within* this DashboardItem

might be better to rename this to "get_widget"
___
*[`sinks/plot/items/item.py` line 32 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3Azklr3PFlUpUFBjKP:-N3Azklr3PFlUpUFBjKQ:bcev0on) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/item.py#L32)):*
> ```Python
> class PlotDashItem (DashboardItem):
>     def __init__(self, props = None):
>         self.serie = None
> ```

should this be "self.series"?

**Review by PCModeActivate — COMMENTED** [review]
@kavinsatheeskumar Fixed errors with and have a hardcoded demo working; removed some files so you'll have to review again, sorry abt that

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-:-N3HuieZ8lTF_TvY4lMz:bemzflu)* status: 0 of 12 files reviewed, 16 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @PCModeActivate, and @SohamP2812)

___
*[`sinks/plot/config.py` line 12 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AzD__4rJnx3sAwPrj:-N3HuHy58EuCoX_4f_-k:bo0ux1u) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/config.py#L12)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Is this file still being used?
</blockquote></details>

The constants for GRAPH_* are, otherwise no
___
*[`sinks/plot/dock_widget.py` line 13 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3Aw2U0B3PIMs2M5rCK:-N3HuP-O2MlXHuw2pYUx:b-c4xrr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/dock_widget.py#L13)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I thought this was a demonstration file to explain how Dock Widgets work. Do we still need it in the final PR?
</blockquote></details>

Not really, tbh this is a demo PR as well, so its not meant to be merged (according to Kavin?)

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56)* status: 0 of 12 files reviewed, 15 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @PCModeActivate, and @SohamP2812)

___
*[`sinks/plot/items/dashboard.py` line 31 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AwdMqAejKmx1Z_jiD:-N3Hvini7VIAlWQyy-_Z:bos348p) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L31)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

maybe give it an optional parameter or put the file name in the config or something
</blockquote></details>

could do, but that also implies that we need to provide the capability to save to a differently named file
which I will do in a later commit, probably
___
*[`sinks/plot/items/dashboard.py` line 45 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3Aybe-8OLhjNg0jTVx:-N3Hvwhf821gf0sL4Gc9:b-d0txwq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L45)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

This function doesn't take an argument?
</blockquote></details>

It does not, just because it will restore the layout from the currently loaded self.data
unless we provide more layout files for the dashboard to read it we wont need it
___
*[`sinks/plot/items/dashboard.py` line 122 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3AyzdqCNbKN_0-Daso:-N3HwWHO9prXFqQNnLvy:bilcqon) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/30f4ecb4f5cb9a1dde5f0d3e03e316fa19397541/sinks/plot/items/dashboard.py#L122)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

I think we should move this class and "PlotDashItem" to their own file called "plot_item.py" or something
</blockquote></details>

I put the Plot class under the PlotDashItem for now just because we dont use Plot anywhere else as of yet

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56)* status: 0 of 12 files reviewed, 20 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @PCModeActivate, @SohamP2812, and @Tessa-P)

___
*[`sinks/plot/dashboard.py` line 61 at r6](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3PdCRuDyyK22wuvTfn:-N3PdCRuDyyK22wuvTfo:b-6m8ifu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9cf3579320fe0d83e950845b896a58b59c124bf2/sinks/plot/dashboard.py#L61)):*
> ```Python
>         savefile.close()
> 
>     def add(self, itemtype, props):
> ```

It might be better to take a DashItem as an argument, rather than the type and properties. That way, we won't end up with a massive if statement when we have many types

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56)* status: 0 of 12 files reviewed, 13 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, @PCModeActivate, @SohamP2812, and @Tessa-P)

___
*[`sinks/plot/dashboard.py` line 61 at r6](https://reviewable.io/reviews/waterloo-rocketry/omnibus/56#-N3PdCRuDyyK22wuvTfn:-N3PktgG4O8e6gCQNcJu:b-q8g1x2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9cf3579320fe0d83e950845b896a58b59c124bf2/sinks/plot/dashboard.py#L61)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

yeah probably, but that still doesnt resolve the massive if since we still need to resolve differently upon type (i.e. I cant do the same init call for a textItem so it makes no difference)
also i thought im not in charge of the "add" function?
</blockquote></details>

Wait, actually, wouldnt itemtype here make more sense? Since dashboarditem is abstract, and we are basically calling to construct by itemtype here, it would make sense for the add menu ui to pass in an itemtype

**Comment by PCModeActivate** [comment]
Closing this PR to create a new one to the dashboard branch

**Pull request closed without merging**
