### PR TITLE
solved the issue to run one sensor

### PR DESCRIPTION
**Pull request by DhritiGabani**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking good, also tested on hardware and it works.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-:-MnbRJze92BjRgZCcaX5:bb0ju1k)* status: all files reviewed, 1 unresolved discussion (waiting on @DhritiGabani)

___
*[sources/ni/main.py, line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-MnbRU0Z0yWonXc3C59q:-MnbRU0Z0yWonXc3C59r:b-qni811) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f840f8167c9f149e3342a14170af0a51993fd122/sources/ni/main.py#L45)):*
> ```Python
>             # read data config.READ_BULK at a time
>             data = ai.read(number_of_samples_per_channel=config.READ_BULK, timeout=5)
>             if data != [] and not isinstance(data[0], list):
> ```

Would be worth adding a comment explaining why we need to do this.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
You have accidentally committed `.DS_Store` files, please remove them from git.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-:-Mokb8Lx1fMyRP2AgqyZ:b-xmqkx7)* status: all files reviewed, 3 unresolved discussions (waiting on @DhritiGabani)

___
*[sources/ni/main.py, line 44 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-MokbL0-3pue_lDPwOao:-MokbL0-3pue_lDPwOap:btlkdjl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d507e13272389124b42287bb06c52e183f70d8ce/sources/ni/main.py#L44)):*
> ```Python
> 
>             # read data config.READ_BULK at a time
>             data = ai.read(number_of_samples_per_channel=config.READ_BULK, timeout=5) # ai.read returns a single array if there is only one sensor and a nested array otherwise
> ```

Please start this comment on a new line for readability.
___
*[sources/ni/main.py, line 59 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-MokbumRETX5EJHbTNZO:-MokbumRETX5EJHbTNZP:by2v0rn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d507e13272389124b42287bb06c52e183f70d8ce/sources/ni/main.py#L59)):*
> ```Python
>             sender.send(CHANNEL, data)  # send data to omnibus
>             
>             print(f"\rRate: {config.READ_BULK*len(rates)/(time.time() - rates[0]): >6.0f}  ", end='')
> ```

Make sure to run `tools/format.sh` before committing, it does sometimes make things look weird (like the print statement you fixed) but its worth it for the consistency (removing trailing spaces like you have above the print).

**Review by DhritiGabani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH)

___
*[sources/ni/main.py, line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-MnbRU0Z0yWonXc3C59q:-MpJZmFt01kA9PgeSOnP:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f840f8167c9f149e3342a14170af0a51993fd122/sources/ni/main.py#L45)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Would be worth adding a comment explaining why we need to do this.
</blockquote></details>

Done.
___
*[sources/ni/main.py, line 44 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-MokbL0-3pue_lDPwOao:-MpJZm-r1s-nM3UuSMWU:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d507e13272389124b42287bb06c52e183f70d8ce/sources/ni/main.py#L44)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Please start this comment on a new line for readability.
</blockquote></details>

Done.
___
*[sources/ni/main.py, line 59 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-MokbumRETX5EJHbTNZO:-MpJZmt-DCp3MSUi7ma-:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d507e13272389124b42287bb06c52e183f70d8ce/sources/ni/main.py#L59)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Make sure to run `tools/format.sh` before committing, it does sometimes make things look weird (like the print statement you fixed) but its worth it for the consistency (removing trailing spaces like you have above the print).
</blockquote></details>

Done.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
:lgtm:, just one pesky `.DS_Store`.

> Reviewed 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-:-MpUPray9tSFYZJTENIY:b-fd083a)* status: all files reviewed, 1 unresolved discussion (waiting on @DhritiGabani)

___
*[sinks/.DS_Store, line 0 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-MpUPluN9tzsAa-fqTEP:-MpUPluN9tzsAa-fqTEQ:b-ybs5eg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e6676c334e2f52090efe5fcac0409b5bbfb34370/sinks/.DS_Store#L0)):*
Missed one.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/37#-:-MrSh-oy-CDHz19ncMlu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DhritiGabani)

**Pull request merged**
