### PR TITLE
Add NI log to CSV tool, make FakeNI log as well

### PR DESCRIPTION
**Pull request by BluCodeGH**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39)

### CODE REVIEW

**Review by DevinLeamy — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @addison-ch, @Artem-Sotnikov, @BluCodeGH, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sources/fakeni/main.py, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-MoH20Sn2XRAhEpHw9Ne:-MoH20Sn2XRAhEpHw9Nf:b-7r79ly) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00c5c7ac0fe38a56c759eb814e6347a49031b601/sources/fakeni/main.py#L27)):*
> ```Python
>         }
> 
>         log.write(msgpack.packb(data))
> ```

We have quite a bit of writing and (with the replay log) reading from logs, that interact with `msgpack`. I think having a Logger class would be a good idea. In addition to the IO jazz, it would also make it easier to standardize naming -  if you agree, I'll open an issue for it.
___
*[tools/ni_csv/main.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-MoH4iev0uyWgZgQoyyp:-MoH4iev0uyWgZgQoyyq:b-litviu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00c5c7ac0fe38a56c759eb814e6347a49031b601/tools/ni_csv/main.py#L13)):*
> ```Python
>     return sum(channel) / len(channel)
> 
> def writeCSV(infile, outfile):
> ```

`write_csv`?

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @addison-ch, @Artem-Sotnikov, @DevinLeamy, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sources/fakeni/main.py, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-MoH20Sn2XRAhEpHw9Ne:-MoPgNYd8_o2XM6V0Fvh:b4funvq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00c5c7ac0fe38a56c759eb814e6347a49031b601/sources/fakeni/main.py#L27)):*
<details><summary><i>Previously, DevinLeamy (Devin Leamy) wrote…</i></summary><blockquote>

We have quite a bit of writing and (with the replay log) reading from logs, that interact with `msgpack`. I think having a Logger class would be a good idea. In addition to the IO jazz, it would also make it easier to standardize naming -  if you agree, I'll open an issue for it.
</blockquote></details>

Good idea. One point here is that the format of our logs on top of msgpack varies, we have the DAQ logs which are just the raw data and the entire omnibus logs (from the logger sink) that include a "wrapping" layer with the channel and timestamp (and non-DAQ data too). That being said, exposing a thin wrapper on top of msgpack makes sense, it lets us switch out how we store logs much easier if we need to in the future.
Opening a clickup task for this sounds like a good idea.
___
*[sources/replay_log/test_replay_log.py, line 63 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-MoPhx3xA1KHMPHeDeG1:-MoPhx3xA1KHMPHeDeG2:b9x0rja) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/bc49bf39885009467a0bc973b46045fdbcd56ee2/sources/replay_log/test_replay_log.py#L63)):*
> ```Python
> 
>         # < 10% error
>         assert percent_error(t1, t2 * speed_inc) < 10
> ```

Sorry for not catching this earlier but 3% was way too tight a bound when these tests are running on a random overloaded github actions server, I'm even iffy about 10% tbh. The last thing we want are flakey tests that fail on an unrelated PR.
___
*[tools/ni_csv/main.py, line 13 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-MoH4iev0uyWgZgQoyyp:-MoPh2-zDaGNwlBuOyJX:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00c5c7ac0fe38a56c759eb814e6347a49031b601/tools/ni_csv/main.py#L13)):*
<details><summary><i>Previously, DevinLeamy (Devin Leamy) wrote…</i></summary><blockquote>

`write_csv`?
</blockquote></details>

Done.

**Review by DevinLeamy — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39)* status: all files reviewed, 3 unresolved discussions (waiting on @addison-ch, @Artem-Sotnikov, @BluCodeGH, @DevinLeamy, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[.github/workflows/test.yml, line 60 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-MoRfu696IKkxKJ8A6MK:-MoRfu696IKkxKJ8A6ML:b-c5tj54) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/bc49bf39885009467a0bc973b46045fdbcd56ee2/.github/workflows/test.yml#L60)):*
> ```YAML
>       shell: bash
>       run: |
>         autopep8 -d -r sources/ sinks/ omnibus/ tools/ --exit-code
> ```

Unrelated to this PR, but I think it makes sense to move the flake8 and autopep8 tests to before everything else. No reason to set up the testing  environment if the PR fails the basic tests
___
*[sources/fakeni/main.py, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-MoH20Sn2XRAhEpHw9Ne:-MoRgq3P1JN-Lqe9Qrin:b-p3mtjp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/00c5c7ac0fe38a56c759eb814e6347a49031b601/sources/fakeni/main.py#L27)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Good idea. One point here is that the format of our logs on top of msgpack varies, we have the DAQ logs which are just the raw data and the entire omnibus logs (from the logger sink) that include a "wrapping" layer with the channel and timestamp (and non-DAQ data too). That being said, exposing a thin wrapper on top of msgpack makes sense, it lets us switch out how we store logs much easier if we need to in the future.
Opening a clickup task for this sounds like a good idea.
</blockquote></details>

Sounds good. I'll create the ticket.

**Review by BluCodeGH — COMMENTED** [review]
@devinleamy in the future please make sure you mark reviewable discussions as 'satisfied'  when approving so it's completed.

> Dismissed @DevinLeamy from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/39#-:-MokWb651VsYSoE8kSw5:b-rc1sks)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @addison-ch, @Artem-Sotnikov, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Pull request merged**
