### PR TITLE
Add Averaging to Plots

### LINKED ISSUE #136: Add Averaging to Plot Dash Item

### PR DESCRIPTION
**Pull request by Darth-Raazi**
## Description

- Added a buffer to place plot points in
- Plotting average of buffer points instead of original points if average is selected
- Changed plot dimensions to not resize if average is selected (i.e. plot max and min are determined by original values, not averaged ones

This PR closes #136.

## Developer Testing

Here's what I did to test my changes:

- Ran plots with and without average selected
- Changed buffer size to verify different levels of averaging

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Run a plot, select the average option and verify that everything works

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Why did you want to avoid the plot bounds changing when averaging is turned on? That seems like what I'd expect to happen. Then you don't need to worry about `orig_values` at all.

If you do want that feature there are some problems with the current implementation
- you never remove points from orig_values
- orig_values is not a dictionary separated by stream like the other ones so multiple plots probably doesn't work quite right

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-:-Nnr0Nyw9MGMBE_WYfig:b-lgspvo)* status: all files reviewed, 2 unresolved discussions (waiting on @Darth-Raazi and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-Nnr-wfZ1G8GuYJVsQfZ:-Nnr-wfZ1G8GuYJVsQf_:bd2kjkz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/655c73ce6bb5deed3cb5b3706600642e06ab1220/sinks/dashboard/items/plot_dash_item.py#L44)):*
> ```Python
>         self.average = self.parameters.param('average').value()
>         # adjustable buffer size for different levels of smoothing
>         self.Buffer_size = self.parameters.param('buffer size').value()
> ```

lowercase pls
___
*[`sinks/dashboard/items/plot_dash_item.py` line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-Nnr0i4D8Eq1cHH2sAI8:-Nnr0i4D8Eq1cHH2sAI9:bjxk5g4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/655c73ce6bb5deed3cb5b3706600642e06ab1220/sinks/dashboard/items/plot_dash_item.py#L47)):*
> ```Python
> 
>         # buffer to calculate local average
>         self.pointsBuffer = []
> ```

snake_case

**Review by Darth-Raazi — COMMENTED** [review]
As per our discussion, I kept the no-resize-on-average feature but made `orig_values` a dictionary so it works for multiple plots

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-:-No0CV64363zRQtqUcbU:b-avjx3d)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 44 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-Nnr-wfZ1G8GuYJVsQfZ:-No0CPLyB827wdc9AraV:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/655c73ce6bb5deed3cb5b3706600642e06ab1220/sinks/dashboard/items/plot_dash_item.py#L44)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

lowercase pls
</blockquote></details>

Done
___
*[`sinks/dashboard/items/plot_dash_item.py` line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-Nnr0i4D8Eq1cHH2sAI8:-No0CQDuCGhCP8xguUj0:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/655c73ce6bb5deed3cb5b3706600642e06ab1220/sinks/dashboard/items/plot_dash_item.py#L47)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

snake_case
</blockquote></details>

Done

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190)* status: all files reviewed, 2 unresolved discussions (waiting on @Darth-Raazi and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 145 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-NozAAL07bJtt1dvDJcn:-NozAAL07bJtt1dvDJco:b7i8jj8) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8d5059b2df8faf9330b737298d76a7f0880a9a95/sinks/dashboard/items/plot_dash_item.py#L145)):*
> ```Python
>         self.orig_values[stream].append(point)
>         if self.average:
>             avgY = sum(self.points_buffer) / self.buffer_size
> ```

This averaging doesn't work with multiple streams? I'd recommend updating fakeni to give you different ranges for different series to better test this.
___
*[`sinks/dashboard/items/plot_dash_item.py` line 161 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/190#-NozANbQ6dvPjHKNVqkv:-NozANbQ6dvPjHKNVqkw:b-lz25tm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8d5059b2df8faf9330b737298d76a7f0880a9a95/sinks/dashboard/items/plot_dash_item.py#L161)):*
> ```Python
>         else:
>             min_point = min(self.orig_values[stream])
>             max_point = max(self.orig_values[stream])
> ```

We need to compute min and max over all streams like the old code used to.

**Comment by Darth-Raazi** [comment]
Closing stale PR

**Pull request closed without merging**
