### PR TITLE
Add ni type hints

### LINKED ISSUE #149: Type Hint Ni
See #145 

This issue is for `sources/ni`

### PR DESCRIPTION
**Pull request by patrick-gu**
## Description

Added type hints for `sources/ni`.

Added type hints where necessary to APIs and main code in ni.

Where numbers were used, I generally used `float`; however, existing code seems to supply either `float` or `int`. I am assuming this is not the intended API (if it is, I can change the hints to `float | int`).

This PR closes #149.

## Developer Testing

Here's what I did to test my changes:

- Ran `calibration_test.py`

These changes do not change any functionality, so I'm not sure what else needs to be tested.

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Look at the type hints to verify they make sense

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Good work. For the `float` vs `int` stuff, did you check which type the code was giving? If not, I recommend using some `print(type(var))` statements to see what exactly is getting passed in/returned. If it is a mix of both, then go with `float | int` for the hints

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-:-NmiES_xCA5Y953_Xf_d:b-5vpzsv)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sources/ni/config.py` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmiE1gjB5TCtRZ3_aW0:-NmiE1gjB5TCtRZ3_aW1:b-thsvc4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/edeed7c810b89177a82563d90360d179b7ea233e/sources/ni/config.py#L6)):*
> ```Python
> 
> RATE: int = 1000  # Analog data sample rate
> READ_BULK: int = 20  # Number of samples to read at once for better performance
> ```

Not needed here, these aren't functions
___
*[`sources/ni/config.py` line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmiE8DFAybUJrPzY9L7:-NmiE8DFAybUJrPzY9L8:b3ft1q1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/edeed7c810b89177a82563d90360d179b7ea233e/sources/ni/config.py#L9)):*
> ```Python
> 
> # Mapping between briefcase ports and ai channels such that you can do ports[1] through ports[12]
> ports: list[Optional[str]] = [
> ```

Is it possible to do something like `None | str`? If not, this is good

**Review by patrick-gu — COMMENTED** [review]
Changed to `float | int` as both are being used.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-:-NmlrTv_7M8e9FgXgHdN:bsyiq1k)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sources/ni/config.py` line 6 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmiE1gjB5TCtRZ3_aW0:-NmlrfI4DQuJz9dMfuSb:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/edeed7c810b89177a82563d90360d179b7ea233e/sources/ni/config.py#L6)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Not needed here, these aren't functions
</blockquote></details>

Done.
___
*[`sources/ni/config.py` line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmiE8DFAybUJrPzY9L7:-Nmlrffc7lMTaWJDE5Sd:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/edeed7c810b89177a82563d90360d179b7ea233e/sources/ni/config.py#L9)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Is it possible to do something like `None | str`? If not, this is good
</blockquote></details>

Done.

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Couple more small things

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-:-NmnGcEvEOq2HOy1V1wg:br330a6)* status: all files reviewed, 5 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sources/ni/calibration.py` line 75 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnF8RD9pqkgJnrigJM:-NmnF8RD9pqkgJnrigJN:b-cd2dtl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/calibration.py#L75)):*
> ```Python
> 
> class Sensor:
>     sensors: list['Sensor'] = []
> ```

Not needed
___
*[`sources/ni/calibration.py` line 119 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFAG2AjEWNghGAwXl:-NmnFAG2AjEWNghGAwXm:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/calibration.py#L119)):*
> ```Python
>         Apply each sensor's calibration to voltages from the NI box.
>         """
>         res: dict[str, list[float | int]] = {}
> ```

See above
___
*[`sources/ni/config.py` line 7 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFpCLCEsJo1V_M6rZ:-NmnFpCLCEsJo1V_M6r_:b-cu97im) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/config.py#L7)):*
> ```Python
> 
> # Mapping between briefcase ports and ai channels such that you can do ports[1] through ports[12]
> ports: list[None | str] = [
> ```

Sorry I realized this isn't needed either
___
*[`sources/ni/config.py` line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFrzk8DVOztiCFRPm:-NmnFrzk8DVOztiCFRPn:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/config.py#L15)):*
> ```Python
> ]
> 
> thermo_ports: list[None | str] = [
> ```

See above
___
*[`sources/ni/main.py` line 33 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFsuN7aaKazafXEJs:-NmnFsuN7aaKazafXEJt:b-34vmyd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/main.py#L33)):*
> ```Python
> 
> def read_data(ai: nidaqmx.Task):
>     rates: list[float] = []
> ```

See above

**Review by patrick-gu — COMMENTED** [review]
Removed type hints as requested

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-:-NmnJY6g8lC7mY1NZunv:b2sm5th)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sources/ni/calibration.py` line 75 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnF8RD9pqkgJnrigJM:-NmnJS_-E2NmjajSn6N1:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/calibration.py#L75)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Not needed
</blockquote></details>

Done.
___
*[`sources/ni/calibration.py` line 119 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFAG2AjEWNghGAwXl:-NmnJTUBBIuw3Yy8HcTW:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/calibration.py#L119)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`sources/ni/main.py` line 33 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFsuN7aaKazafXEJs:-NmnJU3-6N8bqbF1CX4n:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/main.py#L33)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[`sources/ni/config.py` line 7 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFpCLCEsJo1V_M6rZ:-NmnJUlj1VrJYvajrUcc:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/config.py#L7)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Sorry I realized this isn't needed either
</blockquote></details>

Done.
___
*[`sources/ni/config.py` line 15 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-NmnFrzk8DVOztiCFRPm:-NmnJVDB3ZMjzjD0ZbKs:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/489fac0f3f6aad32585bdd444cddb1ac58fae035/sources/ni/config.py#L15)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.

**Review by Darth-Raazi — APPROVED** [review]
:lgtm: Good work!

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/186#-:-NmnKIPJ9XV2DEAeFcQs:b-pv0wtg)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

**Pull request merged**
