### PR TITLE
add new widgets

### PR DESCRIPTION
**Pull request by AvKat**
add an image item and text item to dashboard

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109)

### CODE REVIEW

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-:-NVCh7Ge3qP10BQ9QKT1:bnfp4nl)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @AvKat and @BluCodeGH)

___
*[`sinks/dashboard/items/text_dash_item.py` line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCh0nd6Mr4QhqjfUVA:-NVCh0nd6Mr4QhqjfUVB:bqv8gfw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L43)):*
> ```Python
>         self.fsize = fsize
>         self.widget.setStyleSheet(
>             "font-size: {}px; color: blue; background-color: white".format(self.fsize))
> ```

Can we make the text centered?

**Review by PCModeActivate — CHANGES_REQUESTED** [review]
Eh, if it works then disregard my comments

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-:-NVCqNFY1h1xOzxRQLh0:bobrif2)* status: all files reviewed, 3 unresolved discussions (waiting on @AvKat, @BluCodeGH, and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/image_dash_item.py` line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCo7QN8w-dZIg88Kmi:-NVCo7QN8w-dZIg88Kmj:b-h97jce) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/image_dash_item.py#L35)):*
> ```Python
>         # this is a hacky way to avoid that and the value is achieved using
>         # trial and error
>         self.offset = 40
> ```

Someone should consider fixing that for the future. I did not expect my old comments to come back to haunt me like that.
___
*[`sinks/dashboard/items/image_dash_item.py` line 39 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCoQnIBgw4imonaDPN:-NVCoQnIBgw4imonaDPO:b-naq8ni) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/image_dash_item.py#L39)):*
> ```Python
>         if self.image_path:
>             width = self.parameters.child("width").value(
>             ) - self.offset  # subtracting here to account
> ```

Ideally there should be more comments to tell me how the math works because I am lost and this might even be my old code, but I am not blocking it if it works
___
*[`sinks/dashboard/items/text_dash_item.py` line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCpMEbDfHLHXE7M-BU:-NVCpMEbDfHLHXE7M-BV:by2sl15) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L15)):*
> ```Python
> 
>         self.text = self.parameters.param('text').value()
>         self.fsize = self.parameters.param('fsize').value()
> ```

Can we have a default textsize if the params do not provide one?
___
*[`sinks/dashboard/items/text_dash_item.py` line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCpCaTEfpFFjJwR8JM:-NVCpCaU9i9PGNEi6pH4:bhyu1wo) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L27)):*
> ```Python
>         self.frame = QScrollArea()
>         self.frame.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
>         self.frame.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
> ```

We do not need scrollbar, right?
___
*[`sinks/dashboard/items/text_dash_item.py` line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCh0nd6Mr4QhqjfUVA:-NVCph3-0iJ1OpLnFRr7:bs9oykr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L43)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Can we make the text centered?
</blockquote></details>

Not in setFontSize I dont think so
___
*[`sinks/dashboard/items/text_dash_item.py` line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCpvfN-O9OipGBaLbH:-NVCpvfN-O9OipGBaLbI:b-cgpfqx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L45)):*
> ```Python
>             "font-size: {}px; color: blue; background-color: white".format(self.fsize))
> 
>     def add_parameters(self):
> ```

What does this function do? I don't understand.
___
*[`sinks/dashboard/items/text_dash_item.py` line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCppzmB0FX8n8ogALC:-NVCppzmB0FX8n8ogALD:b-v33qm1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L50)):*
> ```Python
>         return [text_param, fsize_param]
> 
>     def on_text_change(self, _, value):
> ```

Why is there a _ param? Is this a hacky way to make work with Qt?
___
*[`sinks/dashboard/items/text_dash_item.py` line 58 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCq4nwBrSBViqlzNjz:-NVCq4nwBrSBViqlzNk-:bde6g91) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L58)):*
> ```Python
> 
>     @staticmethod
>     def get_name():
> ```

Why is the name just "text"?

**Review by Darth-Raazi — APPROVED** [review]
If you can address my comments, that would be great but I won't block.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-:-NVD6hYd9QmxpaCpWmj4:bhgmhi9)* status: all files reviewed, 4 unresolved discussions (waiting on @AvKat, @BluCodeGH, and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/image_dash_item.py` line 35 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVD56Hf2CZRc4u3hR_A:-NVD56Hf2CZRc4u3hR_B:brlqmbs) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/image_dash_item.py#L35)):*
> ```Python
>         # this is a hacky way to avoid that and the value is achieved using
>         # trial and error
>         self.offset = 40
> ```

Can we get the size of the widget dynamically and set the size of the image to that - 1? This might (or might not) cause problems on different displays.
___
*[`sinks/dashboard/items/text_dash_item.py` line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCppzmB0FX8n8ogALC:-NVD6WyXCQKQ7IkFVtsM:b8tf03r) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L50)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Why is there a _ param? Is this a hacky way to make work with Qt?
</blockquote></details>

Yeah I have to second this, if we're using a dummy value then it should be named appropriately to help future devs

**Review by AvKat — COMMENTED** [review]
@Darth-Raazi @PCModeActivate  since you both commented about the offset thing, here is a better explanation: say the widget is 500px wide. i set the image width to be 499px. Qt will change that to 499 + x where 30 < x <= 40. this will trigger another internal resize event because now the widget cannot handle 499 + x (it's only 500). the widget grows, it changes the value of the width parameter, and since the width param now changes, it causes image resize. we get stuck in an infinite loop. a better solution would be to just programatically get the width of the "border" area but i can't figure out where it's coming from. 
i will try to explain more in the comments. let me know if you find something and i will incorporate that.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-:-NVDI_HU-w5LPFotTADa:b4yza1z)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH and @PCModeActivate)

___
*[`sinks/dashboard/items/text_dash_item.py` line 15 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCpMEbDfHLHXE7M-BU:-NVDFYfY6jd2jyxbNZoI:b-l9n927) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L15)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Can we have a default textsize if the params do not provide one?
</blockquote></details>

default is in `add_parameters`
___
*[`sinks/dashboard/items/text_dash_item.py` line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCpCaTEfpFFjJwR8JM:-NVDFens62H1dZRl2OQZ:blnes2m) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L27)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

We do not need scrollbar, right?
</blockquote></details>

@KavinSatheeskumar said we should turn it off
___
*[`sinks/dashboard/items/text_dash_item.py` line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCh0nd6Mr4QhqjfUVA:-NVDFnZ3D9tDSmVlGblb:b2yeddn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L43)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Not in setFontSize I dont think so
</blockquote></details>

not there, but I've done it
___
*[`sinks/dashboard/items/text_dash_item.py` line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCpvfN-O9OipGBaLbH:-NVDFBqwEse_Gdb82d70:bfh3bce) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L45)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

What does this function do? I don't understand.
</blockquote></details>

this is to add widget specific parameters. this is documented in the superclass
this is also the reason we have a default font size and a default text (empty)
___
*[`sinks/dashboard/items/text_dash_item.py` line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCppzmB0FX8n8ogALC:-NVDFsS16vN7Ohz7Y4HH:bc5uzlu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L50)):*
<details><summary><i>Previously, Darth-Raazi wrote…</i></summary><blockquote>

Yeah I have to second this, if we're using a dummy value then it should be named appropriately to help future devs
</blockquote></details>

this was me just trying to shut my linter up. i'll fix this
___
*[`sinks/dashboard/items/text_dash_item.py` line 58 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCq4nwBrSBViqlzNjz:-NVDFzEt55MAhOR4wLDL:b-yznuxn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L58)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Why is the name just "text"?
</blockquote></details>

i was going for "Label" but that is taken for an in-progress item

**Review by BluCodeGH — APPROVED** [review]
Offset stuff is weird but I don't think it's worth spending a bunch of time figuring out, so :lgtm:!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-:-NVGGT539cmYhnnQln86:b-isq9q1)* status: all files reviewed, 3 unresolved discussions (waiting on @AvKat and @PCModeActivate)

___
*[`sinks/dashboard/items/image_dash_item.py` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVGG27s8NX39eoIRc5e:-NVGG27tESN0LIwCsRNF:b-azsokt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/image_dash_item.py#L26)):*
> ```Python
>         self.frame.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
>         self.frame.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
>         self.frame.setWidgetResizable(True)
> ```

Would disabling this make the offset resizing issues go away?
___
*[`sinks/dashboard/items/text_dash_item.py` line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCppzmB0FX8n8ogALC:-NVGFYM67Rug2tioiFak:bec6yda) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L50)):*
<details><summary><i>Previously, AvKat (Avish Kathpal) wrote…</i></summary><blockquote>

this was me just trying to shut my linter up. i'll fix this
</blockquote></details>

This is because this is a callback from QT that always provides two arguments, so `_` is standard practice meaning we don't care about the first argument.

**Review by PCModeActivate — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109)* status: all files reviewed, 1 unresolved discussion (waiting on @AvKat)

___
*[`sinks/dashboard/items/text_dash_item.py` line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVCpvfN-O9OipGBaLbH:-NVGN-Ce1uIVlUDgEEWi:ba55oj3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/text_dash_item.py#L45)):*
<details><summary><i>Previously, AvKat (Avish Kathpal) wrote…</i></summary><blockquote>

this is to add widget specific parameters. this is documented in the superclass
this is also the reason we have a default font size and a default text (empty)
</blockquote></details>

Im not gonna say I understand it but Ill just not block it if it works

**Review by AvKat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109)* status: all files reviewed, 1 unresolved discussion (waiting on @AvKat)

___
*[`sinks/dashboard/items/image_dash_item.py` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/109#-NVGG27s8NX39eoIRc5e:-NVGu9AzET8Iugq_xPnw:bv72508) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/62cf229e4a7db7a63d4e482e42c84092016cb5c7/sinks/dashboard/items/image_dash_item.py#L26)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Would disabling this make the offset resizing issues go away?
</blockquote></details>

no this is to tackle a different issue

**Pull request merged**
