### PR TITLE
Add thermistor and kelvin sense math to rlcs

### PR DESCRIPTION
**Pull request by Pdada1**
## Description

I changed X and Y to accomplish Z.

This PR closes #XXX.

## Developer Testing

Here's what I did to test my changes:

- Ran A
- Ran B
- Ran C

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Run D and check output

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263)

### CODE REVIEW

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:, just one formatting nit. Also please get @KavinSatheeskumar or @JasonBrave 's approval before merging since they know more about RLCS

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-:-O1e1Y5u8gJ0zJ5tbPGZ:b-vfzhoe)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @KavinSatheeskumar, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)

___
*[`sources/rlcs/rlcs.py` line 114 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1e1QbD1lASK2vrmYQL:-O1e1QbD1lASK2vrmYQM:beezec6) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7c082cd3dc33f72b2d3535f840d86b4f54997fd2/sources/rlcs/rlcs.py#L114)):*
> ```Python
>     return float(adc_value)/(2**adc_bits)*vref
> 
>     
> ```

Please delete all the blank lines at the end of the file except for one

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263)* status: all files reviewed, 6 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)

___
*[`sources/rlcs/rlcs.py` line 48 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1eRXWD-FADyGQ4o-V5:-O1eRXWD-FADyGQ4o-V6:bf9h1pw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7c082cd3dc33f72b2d3535f840d86b4f54997fd2/sources/rlcs/rlcs.py#L48)):*
> ```Python
>     Numeric("Heater Kelvin High 2 Voltage", 16, scale=1/1000, big_endian=False),
>     Numeric("Heater Resistance 1", 16, scale=1,big_endian=False),#new field declaration to send these fields over omnibus
>     Numeric("Heater Resistance 2", 16, scale=1,big_endian=False),#new field declaration to send these fields over omnibus
> ```

do you want these to be floating point values of integers? Because we have a new "Floating" field for 32 floating point numbers
___
*[`sources/rlcs/rlcs.py` line 70 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1eSNMGChCNhqHVm7Gr:-O1eSNMGChCNhqHVm7Gs:b-l88stw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7c082cd3dc33f72b2d3535f840d86b4f54997fd2/sources/rlcs/rlcs.py#L70)):*
> ```Python
>         key_list_resistance=["Heater Resistance 1","Heater Resistance 2"]
>         res=parsley.parse_fields(bit_str, MESSAGE_FORMAT)
>         for x in range(0,len(key_list_therm)):
> ```

you could just do the below. Saves you a few lines of code and makes things more readable.

Same thing for the other loops



_Code snippet:_
```Python
for key in ["Heater Current 1","Heater Current 2"]:
    res[key] = parse_thermistor(rest[key],10,4.096)
```
___
*[`sources/rlcs/rlcs.py` line 85 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1eSoY75zlbPFbMO0Ka:-O1eSoY75zlbPFbMO0Kb:bk4gsv6) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7c082cd3dc33f72b2d3535f840d86b4f54997fd2/sources/rlcs/rlcs.py#L85)):*
> ```Python
> def parse_thermistor(adc_value, adc_bits,vref):
>     #Second resistor in voltage divider
>     voltage_divider_resistor=float(5000)
> ```

5000.0
___
*[`sources/rlcs/rlcs.py` line 98 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1eTqAt9UJETNLvQ132:-O1eTqAu0nwj2qilsEqG:b-ayk39j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7c082cd3dc33f72b2d3535f840d86b4f54997fd2/sources/rlcs/rlcs.py#L98)):*
> ```Python
>     thermistor_voltage=parse_adc_to_voltage(adc_value,adc_bits,vref)
>     #resistance of the thermistor calculated using voltage divider
>     thermistor_resistance=(voltage_divider_resistor*input_voltage/thermistor_voltage)-voltage_divider_resistor
> ```

add some spaces between terms. Also maybe use shorter variables names (I am a fan of removing all vowels)
___
*[`sources/rlcs/rlcs.py` line 104 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1eTMxQ2yWQ4eqV1YZz:-O1eTMxQ2yWQ4eqV1Y_-:b-8gs2by) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7c082cd3dc33f72b2d3535f840d86b4f54997fd2/sources/rlcs/rlcs.py#L104)):*
> ```Python
>     return therm_temp_cel
> 
> def parse_kelvin_sensor(adc_value,adc_bit,vref):
> ```

This function is literally just a wrapper around parse_adc_to_voltage. I'd just use the other function and add comments in the code to describe what you are doing.

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263)* status: all files reviewed, 7 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)

___
*[`sources/rlcs/rlcs.py` line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1eUW3W5OGoJB2IIaPv:-O1eUW3W5OGoJB2IIaPw:b747ehr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7c082cd3dc33f72b2d3535f840d86b4f54997fd2/sources/rlcs/rlcs.py#L64)):*
> ```Python
>     bit_str = parsley.BitString(data=line[1:-1])
>     try:
>         key_list_current=["Heater Current 1","Heater Current 2"]
> ```

Only put code that might throw an exception inside of a try block. So you can keep the the mutating of the result for after the try block is over



_Code snippet:_
```Python
try:
    res=parsley.parse_fields(bit_str, MESSAGE_FORMAT)
except:
    print("Invalid data: " + str(e))
    return

# ... Your original code here (fixed as described below)

return res
```

**Comment by patrick-gu** [comment]
There might be a divide by zero error when current is 0 (source: @JasonBrave)

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)

___
*[`sources/rlcs/rlcs.py` line 63 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1m3myS44R8nh4iNtKd:-O1m3myT-sj9ddad5iUy:b-59m9fy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/39ef0c6ce3c0be9d1d5c5364ae83c06574ccf9b7/sources/rlcs/rlcs.py#L63)):*
> ```Python
>     '''
>     bit_str = parsley.BitString(data=line[1:-1])
>     key_list_therm=["Heater Thermistor 1","Heater Thermistor 2"]
> ```

Is this used anywhere?
___
*[`sources/rlcs/rlcs.py` line 66 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1m3olkDD4KIEFtBBOU:-O1m3olkDD4KIEFtBBOV:b-59m9fy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/39ef0c6ce3c0be9d1d5c5364ae83c06574ccf9b7/sources/rlcs/rlcs.py#L66)):*
> ```Python
>     key_list_kelvin=["Heater Kelvin Low 1 Voltage","Heater Kelvin Low 2 Voltage"
>                   "Heater Kelvin High 1 Voltage","Heater Kelvin High 2 Voltage"]
>     key_list_resistance=["Heater Resistance 1","Heater Resistance 2"]
> ```

Is this used anywhere?

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-:-O1m4DaY7LoXONabBFIb:bnfp4nl)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)

**Comment by Pdada1** [comment]
> > _[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263)_ status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @patrick-gu, @Pdada1, and @saads312)
> 
> _[`sources/rlcs/rlcs.py` line 63 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1m3myS44R8nh4iNtKd:-O1m3myT-sj9ddad5iUy:b-59m9fy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/39ef0c6ce3c0be9d1d5c5364ae83c06574ccf9b7/sources/rlcs/rlcs.py#L63)):_
> 
> > ```python
> >     '''
> >     bit_str = parsley.BitString(data=line[1:-1])
> >     key_list_therm=["Heater Thermistor 1","Heater Thermistor 2"]
> > ```
> 
> Is this used anywhere?
> 
> _[`sources/rlcs/rlcs.py` line 66 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/263#-O1m3olkDD4KIEFtBBOU:-O1m3olkDD4KIEFtBBOV:b-59m9fy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/39ef0c6ce3c0be9d1d5c5364ae83c06574ccf9b7/sources/rlcs/rlcs.py#L66)):_
> 
> > ```python
> >     key_list_kelvin=["Heater Kelvin Low 1 Voltage","Heater Kelvin Low 2 Voltage"
> >                   "Heater Kelvin High 1 Voltage","Heater Kelvin High 2 Voltage"]
> >     key_list_resistance=["Heater Resistance 1","Heater Resistance 2"]
> > ```
> 
> Is this used anywhere?

Removed key_list resistance and therm, 
key_list kelivn is used in parsing

**Pull request merged**
