### PR TITLE
Plotter reformat - Dashboard & Item Classes

### PR DESCRIPTION
**Pull request by PCModeActivate**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57)* status: all files reviewed, 7 unresolved discussions (waiting on @KavinSatheeskumar and @PCModeActivate)

___
*[`sinks/dashboard/dashboard.py` line 36 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e8IKHCHREau32PC5v:-N3e8IKHCHREau32PC5w:b-ubia49) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboard.py#L36)):*
> ```Python
> 
>     def load(self, file="savefile.sav"):
>         savefile = open(file, 'rb')
> ```

You should always use `with` statements for file I/O. Using them means you can't forget to close the file (like you have here).
___
*[`sinks/dashboard/dashboard.py` line 39 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e8x2h5Qa6fFcepvxZ:-N3e8x2h5Qa6fFcepvx_:bxqz68x) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboard.py#L39)):*
> ```Python
>         self.data = pickle.load(savefile)
>         for i, item in enumerate(self.data["items"]):  # { 0: {...}, 1: ..., ...}
>             self.add(item["class"], item["props"])
> ```

When loading we can't just add any docks that are in the file, we need to remove all existing docks first (what happens when the user loads a different save during running).
___
*[`sinks/dashboard/dashboard.py` line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e8fLo3qISKTzN6j6b:-N3e8fLo3qISKTzN6j6c:b-661yg1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboard.py#L77)):*
> ```Python
>         listen = time.time()
>         while time.time() < listen + 1:
>             callback()
> ```

This wait doesn't do anything now, right? It can be removed?
___
*[`sinks/dashboard/dashboarditem.py` line 23 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e6uVS6cCeJQ6F3v4r:-N3e6uVS6cCeJQ6F3v4s:b-7tqkai) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboarditem.py#L23)):*
> ```Python
>         raise NotImplementedError
> 
>     def get_widgets(self) -> QtWidgets:
> ```

`QtWidgets` is a module not a type. The correct type is `pyqtgraph.Qt.QtWidgets.QWidget`. This should also only return a single widget and so should be called `get_widget(self)`.
___
*[`sinks/dashboard/dockwidget_example.py` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e73u_8Vf2ZkyoMPRl:-N3e73u_8Vf2ZkyoMPRm:b-p758pf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dockwidget_example.py#L2)):*
> ```Python
> """
> This example demonstrates the use of pyqtgraph's dock widget system.
> ```

This should be removed before merging.
___
*[`sinks/dashboard/plotdashitem.py` line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e7mRK5wMid_vkfh8U:-N3e7mRK5wMid_vkfh8V:b-qbqmqn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/plotdashitem.py#L16)):*
> ```Python
> class PlotDashItem (DashboardItem):
>     def __init__(self, props=None):
>         self.serie = None
> ```

The singular of `series` is also `series`, `serie` is not a word.
___
*[`sinks/dashboard/savefile.sav` line 0 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e7GTI1l5fRpY7ZvBp:-N3e7GTI1l5fRpY7ZvBq:bpf9rgt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/savefile.sav#L0)):*
This should be .gitignored.

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57)* status: 8 of 14 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH and @KavinSatheeskumar)

___
*[`sinks/dashboard/dashboard.py` line 36 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e8IKHCHREau32PC5v:-N3gC3Ah15VgFQgShbcp:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboard.py#L36)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

You should always use `with` statements for file I/O. Using them means you can't forget to close the file (like you have here).
</blockquote></details>

Done.
___
*[`sinks/dashboard/dashboard.py` line 39 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e8x2h5Qa6fFcepvxZ:-N3gC4Uu3dSSt_zHBbXQ:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboard.py#L39)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

When loading we can't just add any docks that are in the file, we need to remove all existing docks first (what happens when the user loads a different save during running).
</blockquote></details>

Done.
___
*[`sinks/dashboard/dashboard.py` line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e8fLo3qISKTzN6j6b:-N3gDMmB-S513JkKzvXv:bt7tt92) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboard.py#L77)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This wait doesn't do anything now, right? It can be removed?
</blockquote></details>

Removed, and doesn't seem to affect anything.
___
*[`sinks/dashboard/dashboarditem.py` line 23 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e6uVS6cCeJQ6F3v4r:-N3gDLnuD7FBvVDPs3f7:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dashboarditem.py#L23)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`QtWidgets` is a module not a type. The correct type is `pyqtgraph.Qt.QtWidgets.QWidget`. This should also only return a single widget and so should be called `get_widget(self)`.
</blockquote></details>

Done.
___
*[`sinks/dashboard/plotdashitem.py` line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e7mRK5wMid_vkfh8U:-N3gCiTe513bWR9PLWAt:bmwkq0d) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/plotdashitem.py#L16)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

The singular of `series` is also `series`, `serie` is not a word.
</blockquote></details>

I should probably go ahead and take an ENGL course for next term. But yes, fixed now.
___
*[`sinks/dashboard/dockwidget_example.py` line 2 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e73u_8Vf2ZkyoMPRl:-N3gDFhe8ouUWrWDoKVr:bemywyt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/dockwidget_example.py#L2)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This should be removed before merging.
</blockquote></details>

Should be deleted by now.
___
*[`sinks/dashboard/savefile.sav` line  at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N3e7GTI1l5fRpY7ZvBp:-N3gDK-W1RrXByKRiUCH:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f44a59b622c59c28fad5b76e592574f3f58debe/sinks/dashboard/savefile.sav#L)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This should be .gitignored.
</blockquote></details>

Done.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57)* status: 11 of 14 files reviewed, 6 unresolved discussions (waiting on @BluCodeGH and @PCModeActivate)

___
*[`sinks/dashboard/dashboard.py` line 75 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N48VWdiDD9CLkkAp2co:-N4A474q1M7BReTayfTS:b-rd1tm5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/88673d32c91d38ae3a04d689cbb1814176d19b42/sinks/dashboard/dashboard.py#L75)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`dock_item_type` isn't define here and this code only barely works with one type of dockitem due to weird scoping. You should define `prompt_and_add` inside the for loop (or just pass a lambda to `.connect()`.
</blockquote></details>

Eh, I just moved the function to the right spot. Easier to read for someone who doesn't know what a lambda is
___
*[`sinks/dashboard/dashboard.py` line 201 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N48XlBfAbTWpx5vHPdQ:-N49z_xWBCID8NFzTVzm:bvdayyy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/88673d32c91d38ae3a04d689cbb1814176d19b42/sinks/dashboard/dashboard.py#L201)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

We maybe want to actually do something with `fps`? At least `print(f"\r{fps}", end='')`?
</blockquote></details>

Later, we can add a dashitem for it, for now, let's not worry about it

**Review by PCModeActivate — COMMENTED** [review]
Looks good; as long as it works I don't think I should block it. We can revisit contents in this at a later time for sure.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-:-N4AdXLR8blKxyZgf8RF:b-8dl7tj)* status: 11 of 14 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @PCModeActivate)

___
*[`sinks/dashboard/dashboard.py` line 55 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N4A0L-P61da7u31zbA7:-N4A0L-Q1KMxvgKlrGaX:b-wq54i4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/8b342227b86d27a4d240f4d42fd233a6f59bec72/sinks/dashboard/dashboard.py#L55)):*
> ```Python
>         # another file
>         ###############################################
>         self.setWindowTitle("Omnibus Dashboard")
> ```

Do you think maybe we make the window its own class (eventually)? It doesn't make much sense when the menu bar is a field inside the dashboard, which is a widget of the window.
___
*[`sinks/dashboard/dashboard.py` line 94 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N4AcUKh05lpKbThMqaN:-N4AcUKh05lpKbThMqaO:b-mtd0o0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/db1f8ec52a43d6ccf45d24ea0ec03da56164fcd9/sinks/dashboard/dashboard.py#L94)):*
> ```Python
>         self.counter = TickCounter(1)
> 
>     def load(self):
> ```

Do we also want a button that just restores a saved layout instead of loading a whole file?
___
*[`sinks/dashboard/dashboard.py` line 171 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/57#-N4AdHu51fe923Vhi_kC:-N4AdHu51fe923Vhi_kD:brfvdx9) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/db1f8ec52a43d6ccf45d24ea0ec03da56164fcd9/sinks/dashboard/dashboard.py#L171)):*
> ```Python
>         def custom_callback(dock_arg):
>             dashitem.unsubscribe_to_all()
>             self.docks = [dock for dock in self.docks if dock.widgets[0] != dashitem]
> ```

Seems like a really inefficient generator but eh, if it works it works

**Comment by BluCodeGH** [comment]
Closing as superceded by the dashboard branch.

**Pull request closed without merging**
