### PR TITLE
xhwong/199 standard display item

### LINKED ISSUE #199: Standard Display Item
For non-gauge values, we want a new standard display item as the default view instead of plots. The item should include a medium text label, a big numerical readout of the value and a [sparkline](https://en.wikipedia.org/wiki/Sparkline) that is togglable (hide/show). This entire item should be one unit (moves together, not separable, etc.)

### PR DESCRIPTION
**Pull request by xinhuey**
## Description
Completed the Standard Display Item for the dashboard. 

Added:

1. Sparkline plot
2. Numerical Readout
3. Medium text label modifiable by the user
4. Sparkline plot can be shown/hidden (togglable)

This PR closes #199 .

## Developer Testing
Here's what I did to test my changes:

1.  Run python launcher.py
2. Click on "Add Item", and select Standard Display Item from the list
3. Select a source 
4. Modify the label (optional)
5. Click on the checkbox display-sparkline to show or hide the sparkline plot

## Reviewer Testing

Here's what you should do to quickly validate my changes:

1.  Run python launcher.py
2. Click on "Add Item", and select Standard Display Item from the list
3. Select a source 
4. Modify the label (optional)
5. Click on the checkbox display-sparkline to show or hide the sparkline plot

Result: You will see a Numerical Readout at the top of the item, followed by a modifiable Medium Text Label and a Sparkline Plot that is togglable.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
Amazing work, and I'd like to see what @Darth-Raazi thinks.

I have some minor comments but I think most of them were issues that were just in the code already so you don't really need to fix those. Just the one about getting cut off by default is a little weird

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-:-O0RzFuNDeO5V0ieUtC2:b-hbhcxt)* status: all files reviewed, 7 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @xinhuey)

___
*[`sinks/dashboard/items/standard_display_item.py` line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0RyRa4C4R2tzWvFVfJ:-O0RyRa4C4R2tzWvFVfK:bae8uyn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L14)):*
> ```Python
> 
> pg.setConfigOption('background', 'w')
> pg.setConfigOption('foreground', 'k')
> ```

nit but I'm not a super huge fan of putting this here, maybe we could put in the main dashboard file?
___
*[`sinks/dashboard/items/standard_display_item.py` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0RydKoEwg0BXEc6loM:-O0RydKoEwg0BXEc6loN:bh87ov) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L26)):*
> ```Python
> 
>         # storing the series name as key, its time and points as value
>         # since each PlotDashItem can contain more than one curve
> ```

this is a different thing
___
*[`sinks/dashboard/items/standard_display_item.py` line 85 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0RzMgnE86W9USQg2Rp:-O0RzMgnE86W9USQg2Rq:bq1n8zx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L85)):*
> ```Python
>                                           limits=publisher.get_all_streams())
>         limit_param = {'name': 'limit', 'type': 'float', 'value': 0}
>         offset_param = {'name': 'offset', 'type': 'float', 'value': 0}
> ```

preexisting, but since these are floats, maybe just make the value 0.0 to be a float
___
*[`sinks/dashboard/items/standard_display_item.py` line 146 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0RzdZg6Hhz2WuO_35B:-O0RzdZg6Hhz2WuO_35C:bjiy5j1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L146)):*
> ```Python
> 
>     def on_data_update(self, stream, payload):
>         time, point = payload
> ```

minor thing but can we just check that the data is a number? because idiots like me will try to plot things that aren't numbers
___
*[`sinks/dashboard/items/standard_display_item.py` line 175 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0Rzvmy0zKhp5DWUe9K:-O0Rzvmy0zKhp5DWUe9L:b-y3re45) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L175)):*
> ```Python
> 
>         # set the displayed range of Y axis
>         self.plot.setYRange(min_point, max_point, padding=0.1)
> ```

for me by default plotting some fake parsley voltages is getting cut off at the bottom
___
*[`sinks/dashboard/items/standard_display_item.py` line 178 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0S-AYB7WjEVJs9vY9Y:-O0S-AYB7WjEVJs9vY9Z:bv3k11d) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L178)):*
> ```Python
> 
>         limit = self.parameters.param('limit').value()
>         if limit != 0:
> ```

nit but preexisting: maybe use 0.0 here to make it clear that this is in fact a floating point comparison
___
*[`sinks/dashboard/items/standard_display_item.py` line 192 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0S-bd01WY4YZ44FuUo:-O0S-bd01WY4YZ44FuUp:beqix29) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L192)):*
> ```Python
> 
>         # round the time to the nearest GRAPH_STEP
>         t = round(self.times[stream][-1] / config.GRAPH_STEP) * config.GRAPH_STEP
> ```

this is kinda weird IMO because it's like the data isn't exactly at the step? but this was preexisting

**Review by Darth-Raazi — DISMISSED** [review]
Great work @xinhuey! A couple changes I would like:
- Can you make the numerical readout bigger? It needs to be at least double if not triple in size. The value should be instantly readable on a quick glance at the dashboard
- When `display-sparkline` is unchecked, the white box should also disappear and the widget should resize to get rid of the empty space

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-:-O0_ftga-8-zYoMR74Dy:b-bhmc3a)* status: all files reviewed, 7 unresolved discussions (waiting on @BigLiban, @Lucifersan, @saads312, and @xinhuey)

**Review by patrick-gu — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Lucifersan, @saads312, and @xinhuey)

___
*[`sinks/dashboard/items/standard_display_item.py` line 146 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0RzdZg6Hhz2WuO_35B:-O14w2gn3muhtGJ0qral:b-2uh7h5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L146)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

minor thing but can we just check that the data is a number? because idiots like me will try to plot things that aren't numbers
</blockquote></details>

whatever
___
*[`sinks/dashboard/items/standard_display_item.py` line 192 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0S-bd01WY4YZ44FuUo:-O14w88U2rTT5SGJoGSG:b-2uh7h5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L192)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

this is kinda weird IMO because it's like the data isn't exactly at the step? but this was preexisting
</blockquote></details>

whatever

**Review by patrick-gu — APPROVED** [review]
My previous comments are resolved 

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-:-O150gGG7V_fneByTTxN:b-3r4ys6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/items/standard_display_item.py` line 175 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-O0Rzvmy0zKhp5DWUe9K:-O150QoT6ukSDZBm7OQO:b-x84j56) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3b332c6bca381776d11fdc0a8d9af06bb0601566/sinks/dashboard/items/standard_display_item.py#L175)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

for me by default plotting some fake parsley voltages is getting cut off at the bottom
</blockquote></details>

Ok I increased the default size which doesn't really solve the problem but I think it's good enough

**Review by patrick-gu — APPROVED** [review]
I noticed one bug which is that if you make the offset really big and set it back to 0 the graph does not go back to normal 

But I think this is good enough to be merged for WDR 

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/244#-:-O17DN2c7l8HnOLNzkdY:b-x556uk)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Pull request merged**
