### PR TITLE
[sinks/globallog] Globallog Proper Exit with Ctrl+C Key handle

### LINKED ISSUE #303: [sinks/globallog] Globallog proper exit
Current the only way to exit globallog is by ctrl+c which may crash the log file we implement, we hope to develop a hotkey detect to proper exit the globallog.

### PR DESCRIPTION
**Pull request by zangjiucheng**
## Description

Update the `sinks/globallog/main.py` to handle exit or terminal signal to proper exit the program.

- Add handler for the globallog code
- Setup timeout for receiver to avoid message block

This PR closes #303.

## Developer Testing

Here's what I did to test my changes:

- Run test on the fakeni with globallog with functional work

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Same as developer testing

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/304)

### CODE REVIEW

**Comment by ChrisYx511** [comment]
Looks good to me! Assuming it's tested, this also fixes some really questionable "while True" LMAO. Someone else chime in on the code quality though I am not exactly a python expert.

**Comment by ChrisYx511** [comment]
Updated #303 with the use case for this fix.

**Review by PCModeActivate — APPROVED** [review]
Looks mostly fine tbh. The while loop is fine if youre concerned. Added some stylistic suggestions. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/304#-:-O90esAJDk4lyTlMuIAh:b603hse)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

**Review by PCModeActivate — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/304#-:-O90lq3sCZ7_ScW-f5w4:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

**Pull request merged**
