### PR TITLE
Keyboard Shortcuts #207

### LINKED ISSUE #207: Keyboard Shortcuts
To improve useability, common actions should be bound to keyboard shortcuts:
- `CTRL/CMD-D` to duplicate an item
- Backspace or delete to delete an item
- `CTRL/CMD-S` to save
- `CTRL/CMD-O` to open
- `CTRL/CMD-L` to lock and unlock the dashboard
- Others as needed

### PR DESCRIPTION
**Pull request by baburama**
Created Keyboard shortcuts for CTRL-O CTRL-D and CTRL-L for open, lock and duplicate functions

## Description

I added keyboard shortcuts on dashboard.py for CTRL-O CTRL-D and CTRL-L. Created toggle method that toggled lock and unlock dashboard and ran it everytime CTRL-L was ran. Added signals for these 3 buttons in Util.py.

This PR closes #207.

## Developer Testing

Here's what I did to test my changes:

- Opened dashboard and click CTRL-O to check if this allowed me to bring up file explorer.
- Opened Dashboard, added item and clicked CTRL-D to see if it would duplicate item.
- Opened Dashboard and added multiple items then clicked CTRL-L to see if Dashboard would lock. Clicked it again to see if it would unlock dashboard.

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Similar to my tests you can open up dashboard and click CTRL-O CTRL-D and CTRL-L and see if they do the correct functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235)

### CODE REVIEW

**Review by patrick-gu — APPROVED** [review]
Excellent work! I have a few tiny suggestions in terms of code style but it looks great otherwise

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-:-O-SqwQsDBYOrzeuxzae:bgt3wec)* status: all files reviewed, 4 unresolved discussions (waiting on @baburama, @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 266 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-SqFkP9CDEmUiYYtFj:-O-SqFkP9CDEmUiYYtFk:bx12vfy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/dashboard.py#L266)):*
> ```Python
>         self.key_press_signals.open_file_keys_pressed.connect(self.open)
>         self.key_press_signals.CTRL_D_pressed.connect(self.on_duplicate)  # Connect the new signal for CTRL-D
>         self.key_press_signals.CTRL_L_pressed.connect(self.toggle_lock)  # Connect the new signal for CTRL-L
> ```

You don't have to add these comments here, I think the code is fairly straightforward. Mainly, I think we should avoid trying to have things that are "new", because they won't be new in the future
___
*[`sinks/dashboard/dashboard.py` line 515 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-Sqbju6IhJ40UtOZzj:-O-Sqbju6IhJ40UtOZzk:b-94cyqy) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/dashboard.py#L515)):*
> ```Python
>             rect.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIsMovable, enabled=False)
>             rect.setFlag(QGraphicsItem.GraphicsItemFlag.ItemIsSelectable, enabled=False)
>     #method to toggle lock/unlock based on if dashboard is locked or not
> ```

I would put a space after `#` and add a newline before the comment just so it's a bit more readable
___
*[`sinks/dashboard/dashboard.py` line 517 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-SqURpBmlHBhdsIKDA:-O-SqURpBmlHBhdsIKDB:b-hagtif) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/dashboard.py#L517)):*
> ```Python
>     #method to toggle lock/unlock based on if dashboard is locked or not
>     def toggle_lock(self):
>         if(self.locked == True):
> ```

This can just be `if self.locked:`
___
*[`sinks/dashboard/dashboard.py` line 696 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-SqoMdAyKjyJAbLZ0V:-O-SqoMdAyKjyJAbLZ0W:bg1aokg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/dashboard.py#L696)):*
> ```Python
>     dash.show()
>     dash.load()
>     app.exec()
> ```

Can you add this newline back

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great stuff Rupert! I have a few more shortcut requests:
- `CTRL/CMD-A` to select all widgets
- `CTRL/CMD-H` to bring up the Help menu

Can you also update the help menu with all these new shortcuts + the save ones that @BigLiban added?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-:-O-T_i9t8QMTD5T_dBQX:byjqhje)* status: all files reviewed, 7 unresolved discussions (waiting on @baburama, @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 267 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-TbPkG9BwJjuBz6HCK:-O-TbPkG9BwJjuBz6HCL:bxdyerp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/dashboard.py#L267)):*
> ```Python
>         self.key_press_signals.CTRL_D_pressed.connect(self.on_duplicate)  # Connect the new signal for CTRL-D
>         self.key_press_signals.CTRL_L_pressed.connect(self.toggle_lock)  # Connect the new signal for CTRL-L
>         self.key_press_signals.CTRL_O_pressed.connect(self.open) 
> ```

`CTRL/CMD-O` is already implemented, see above
___
*[`sinks/dashboard/dashboard.py` line 515 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-Sqbju6IhJ40UtOZzj:-O-Taj527JFNTDf5i2Ad:b76qy3w) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/dashboard.py#L515)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I would put a space after `#` and add a newline before the comment just so it's a bit more readable
</blockquote></details>

And capitalize the first letter too
```
# Method to ...
```
___
*[`sinks/dashboard/utils.py` line 29 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-Tb_pk-Ogh5HbXRVWX:-O-Tb_pk-Ogh5HbXRVWY:bv13geq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/utils.py#L29)):*
> ```Python
>     open_file_keys_pressed = Signal()
>     CTRL_D_pressed = Signal()  # Signal for Ctrl+D
>     CTRL_L_pressed = Signal()  # Signal for Ctrl+L
> ```

Can you follow the same naming format as above? E.g. `duplicate_keys_pressed`
___
*[`sinks/dashboard/utils.py` line 62 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-O-Tc-7d0or-KcNAAwm5:-O-Tc-7d0or-KcNAAwm6:brl8k0z) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/627eb93d66e596c7b5ddbe9936fbdaeb7979d9ef/sinks/dashboard/utils.py#L62)):*
> ```Python
>                     self.open_file_keys_pressed.emit()
>                 case KeyEvent(Qt.Key_D, Qt.ControlModifier):
>                     if event.modifiers() & Qt.ControlModifier:
> ```

Are these if statements needed?

**Review by Darth-Raazi — COMMENTED** [review]
Hey @baburama, looking at @patrick-gu's work on #238 and #239, can we also add shortcuts:
- `CTRL/CMD-L` for item locking/unlocking
- `CTRL/CMD-SHIFT-L` for dashboard locking/unlocking
- `CTRL/CMD-UP/DOWN` (arrow keys) for send forwards/backwards
- `CTRL/CMD-SHIFT-UP/DOWN` for send to front/back

Sorry to keep adding stuff to this ticket, after your PR is merged I'll get people to add shortcuts for new features in their own PRs. Thanks!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-:-O02JCYw81zj-_alzcGt:b-rpm5g2)* status: all files reviewed, 7 unresolved discussions (waiting on @baburama, @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

**Comment by patrick-gu** [comment]
Also I don't see the point of adding a help menu shortcut because, if you've taken the time to memorize that shortcut, you probably don't need to look at the help menu

**Review by patrick-gu — APPROVED** [review]
Obviously I approve of my own changes

Added more shortcuts and info - in the action, and in help menu - about shortcuts

> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-:-O1597oi1TmDe8fA9DtW:b-sbvu56)* status: all files reviewed, 3 unresolved discussions (waiting on @baburama, @BigLiban, @Lucifersan, and @saads312)

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/235#-:-O15n9NBE8cVMWFPBW51:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @baburama, @BigLiban, @Lucifersan, and @saads312)

**Pull request merged**
