### PR TITLE
Replay log streams

### PR DESCRIPTION
**Pull request by eugeneh1217**
Fix for [this clickup task](https://app.clickup.com/t/1pynz45)

Original behavior:
`sources.replay_log.replay` accepted string path of file of log to open and close internally.

New behavior:
`sources.replay_log.replay` accepts file-like object (buffer) of log.

Other changes:
`sources.replay_log.replay_log_test.py` contains restructuring to support above changes.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42)

### CODE REVIEW

**Review by eugeneh1217 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42)* status: all files reviewed, 4 unresolved discussions (waiting on @BluCodeGH and @eugeneh1217)

___
*[sources/replay_log/replay_log_test.py, line 79 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqRpYNW7ZmvjlLhT4ST:-MqS3Rly7z8_mRWAmAnV:b7d16b3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f9fe022a854454325241036d8fc4d7b21ade0ce8/sources/replay_log/replay_log_test.py#L79)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

If you're using the runtime at a 1x speed as a benchmark, best to do so explicitly rather than having it in the list of times to test just like the others.
</blockquote></details>

I wanted to use the first element instead of an explicit `replay_time` to communicate that it doesn't matter what `replay_time` the others are benchmarked against. Do you think explicit benchmark `replay_time` is better?

**Review by eugeneh1217 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @BluCodeGH and @eugeneh1217)

___
*[sources/replay_log/replay_log_test.py, line 79 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqRpYNW7ZmvjlLhT4ST:-MqS9wEw4IqsLn3Ukbys:b-ean14g) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f9fe022a854454325241036d8fc4d7b21ade0ce8/sources/replay_log/replay_log_test.py#L79)):*
<details><summary><i>Previously, eugeneh1217 wrote…</i></summary><blockquote>

I wanted to use the first element instead of an explicit `replay_time` to communicate that it doesn't matter what `replay_time` the others are benchmarked against. Do you think explicit benchmark `replay_time` is better?
</blockquote></details>

Actually, on second thought, I think being explicit is more important than that small communication nuance.

**Review by eugeneh1217 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @BluCodeGH)

___
*[sources/replay_log/replay_log_test.py, line 50 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqRnc037ifBBqlX3tIR:-MqSNJu-De-vfTv_22vn:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f9fe022a854454325241036d8fc4d7b21ade0ce8/sources/replay_log/replay_log_test.py#L50)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Might be cleaner to create a `MockSender` class that wraps the BytesIO and `bind_mock_send`, and monkeypatch out the entire `Sender` object.
</blockquote></details>

Done.
___
*[sources/replay_log/replay_log_test.py, line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqRoX8eDdv0g-uXc_Pm:-MqSNJa-74NEvb5e55Il:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f9fe022a854454325241036d8fc4d7b21ade0ce8/sources/replay_log/replay_log_test.py#L64)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Test at a speed < 1? Also parameterized tests, very cool.
</blockquote></details>

Done.
___
*[sources/replay_log/replay_log_test.py, line 71 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqRp9kB1x01NzlwkZ0p:-MqSNJ2v33pmdYzaS5Wu:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f9fe022a854454325241036d8fc4d7b21ade0ce8/sources/replay_log/replay_log_test.py#L71)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Why not assert right after you do the replay? Saves storing the runtimes and the second for loop.
</blockquote></details>

Done.
___
*[sources/replay_log/replay_log_test.py, line 79 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqRpYNW7ZmvjlLhT4ST:-MqSNMZs3p2yf4yUA16o:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f9fe022a854454325241036d8fc4d7b21ade0ce8/sources/replay_log/replay_log_test.py#L79)):*
<details><summary><i>Previously, eugeneh1217 wrote…</i></summary><blockquote>

Actually, on second thought, I think being explicit is more important than that small communication nuance.
</blockquote></details>

Done.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-:-MqSZgzzATg5vgSlCBrC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @eugeneh1217)

___
*[sources/replay_log/replay_log_test.py, line 77 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqSYY7E0A0xUoKoMq_N:-MqSYY7E0A0xUoKoMq_O:bk2ik9l) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9280a3f40b0fc56d481df122ebf772b267c382d4/sources/replay_log/replay_log_test.py#L77)):*
> ```Python
>         mock_input.seek(0)
>         runtime = get_runtime(replay_log.replay, mock_input, replay_speed)
>         expected_runtime = runtime * replay_speed
> ```

Tiny nit but I'd expect `expected_runtime = benchmark_runtime / replay_speed` and then comparing `runtime` and `expected_runtime`. Fix it if you like, merge otherwise.

**Review by eugeneh1217 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @BluCodeGH)

___
*[sources/replay_log/replay_log_test.py, line 77 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/42#-MqSYY7E0A0xUoKoMq_N:-MqX9Pim9BgzJZLkQ3y1:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/9280a3f40b0fc56d481df122ebf772b267c382d4/sources/replay_log/replay_log_test.py#L77)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Tiny nit but I'd expect `expected_runtime = benchmark_runtime / replay_speed` and then comparing `runtime` and `expected_runtime`. Fix it if you like, merge otherwise.
</blockquote></details>

Done.

**Pull request merged**
