### PR TITLE
Fixed Thermistor and Kelvin Sense Math (Again)

### PR DESCRIPTION
**Pull request by Pdada1**
Changed the thermistor and kelvin sense code in RLCS to include math, added extra message type for thermistor voltage
Fixed conversion for thermistor resistance and temperature conversion

Here's what I did to test my changes:

- Ran parse_themistor_kelvin (adc_value, 10, 4.096) with various voltage values and verified temp output against datasheet
- Tested standard temp parse_thermistor_kelvin(833, 10,4.096) 
Returned expected resistance of near 10000 ohms, and 25 degrees C

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
This review will be just looking at the code, haven't actually done my own tests on it yet.

I would hope to test this on RLCS for real before merging it, to avoid potential crashes during WDR

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-:-O2H0lVLAr-lsO3cndlJ:bavnrbw)* status: all files reviewed, 5 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @Pdada1, and @saads312)

___
*[`sources/rlcs/main.py` line 64 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H0xJG19jl4J7Xucb4:-O2H0xJG19jl4J7Xucb5:b-70db1d) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/main.py#L64)):*
> ```Python
> 
> ```

Nit: I don't think this newline should be here
___
*[`sources/rlcs/rlcs.py` line 41 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H1JmoAHdIA3bk0RMo:-O2H1JmoAHdIA3bk0RMp:bwm72aq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/rlcs.py#L41)):*
> ```Python
>     Numeric("Heater Thermistor Voltage 2", 16, scale=1/1000, big_endian=False),
>     Numeric("Heater Thermistor Temp 1", 16, scale=1/1000, big_endian=False),
>     Numeric("Heater Thermistor Temp 2", 16, scale=1/1000, big_endian=False),
> ```

Has this been added to RLCS? https://github.com/waterloo-rocketry/rlcs/blob/91ae3e7d06c24fd416644fa799d2eef4f8f2b76d/src/common/config.hpp#L43-L70 Otherwise we will get wrong message sizes and it will not work.
___
*[`sources/rlcs/rlcs.py` line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H1Tzp-gaIHWJH2LXB:-O2H1Tzp-gaIHWJH2LXC:bzd5xsw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/rlcs.py#L52)):*
> ```Python
> ]
> 
> EXPECTED_SIZE = 2 + parsley.calculate_msg_bit_len(MESSAGE_FORMAT) 
> ```

Why was the division by 8 removed?
___
*[`sources/rlcs/rlcs.py` line 114 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H1_gn6Lpk9J_Ujs6M:-O2H1_gn6Lpk9J_Ujs6N:brt73yw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/rlcs.py#L114)):*
> ```Python
>     #convert the adc output to voltage output
>     thrmstr_vlt = parse_adc_to_voltage(adc_value,adc_bits,vref)
>     print("This is thermistor voltage " + str(thrmstr_vlt))
> ```

Remove print statements here to avoid spamming the console
___
*[`sources/rlcs/rlcs.py` line 117 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H28ry9mME0XeZKB8a:-O2H28ry9mME0XeZKB8b:b-j34ug7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/rlcs.py#L117)):*
> ```Python
>     if 0.0 < thrmstr_vlt < inpt_vlt:
>         #resistance of the thermistor calculated using voltage divider
>         thrmstr_rstnce = (thrmstr_vlt*vlt_dvdr_rstr) / (inpt_vlt - thrmstr_vlt)
> ```

I don't know what the circuit looks like but this math seems right to me for voltage divider

**Comment by Pdada1** [comment]
> _[`sources/rlcs/rlcs.py` line 114 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H1_gn6Lpk9J_Ujs6M:-O2H1_gn6Lpk9J_Ujs6N:brt73yw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/rlcs.py#L114)):_
> 
This doesn't have to be changed, since we are not taking any extra input from rlcs, just generating new data, through computation.

**Review by patrick-gu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277)* status: all files reviewed, 5 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @Pdada1, and @saads312)

___
*[`sources/rlcs/rlcs.py` line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H1Tzp-gaIHWJH2LXB:-O2HrCsbAYM_Jm_MsaKX:b-cf6rqc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/rlcs.py#L52)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Why was the division by 8 removed?
</blockquote></details>

This should be what it was before as that was an integer division
___
*[`sources/rlcs/rlcs.py` line 114 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2H1_gn6Lpk9J_Ujs6M:-O2HrHWA9ukz4khM6Q-K:b70a7vp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f55b627419bd4ff5cae3089c96f46ea834cba5ef/sources/rlcs/rlcs.py#L114)):*
<details><summary><i>Previously, Pdada1 (Pranav Mahabal) wrote…</i></summary><blockquote>

This doesn't have to be changed, since we are not taking any extra input from rlcs, just generating new data, through computation. 
</blockquote></details>

I assume you are referring to my comment above. I think it does need to be changed because that is describing the RLCS message format, and you can only update that if you are also updating the RLCS

**Comment by Pdada1** [comment]
> I assume you are referring to my comment above. I think it does need to be changed because that is describing the RLCS message format, and you can only update that if you are also updating the RLCS

This is a me skill issue. I had it explained by Kavin earlier. 
What I am doing is taking in the same standard RLCS values and then making some new data on them through calculations before returning that data. So I don't need to change msg format, just add more fields to the dictionary res.
I have made these edits and returned msg format to how it was originally.

**Review by patrick-gu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277)* status: all files reviewed, 8 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @Pdada1, and @saads312)

___
*[`sources/rlcs/main.py` line 21 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LI5DcE_ormmwCCBsp:-O2LI5DcE_ormmwCCBsq:bjoh91l) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/main.py#L21)):*
> ```Python
>                 continue
> 
>             output = b'W' + s.read(rlcs.EXPECTED_SIZE - 1) +b'R'
> ```

This doesn't need to be here I think, as the expected size would be with 'W' and 'R', so the 'R' would be read anyways
___
*[`sources/rlcs/main.py` line 68 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LIGKQ9dvQT-lHwaDc:-O2LIGKQ9dvQT-lHwaDd:byy5x8o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/main.py#L68)):*
> ```Python
>         main()
>     except KeyboardInterrupt:
>         pass
> ```

I don't think this file needs to be changed at all in theory, could be just reverted back to the base
___
*[`sources/rlcs/rlcs.py` line 12 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LIMrb9_Z3ysRIXRJk:-O2LIMrb9_Z3ysRIXRJl:bpg4swj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/rlcs.py#L12)):*
> ```Python
> 
> MESSAGE_FORMAT = [
> Enum("OV101 Command", 8, VALVE_COMMAND),
> ```

where is the indent
___
*[`sources/rlcs/rlcs.py` line 24 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LIQi1DW1EJDMFQQm6:-O2LIQi1DW1EJDMFQQm7:b-xussy0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/rlcs.py#L24)):*
> ```Python
>     Enum("Ignition Primary Command", 8, VALVE_COMMAND),
>     Enum("Ignition Secondary Command", 8, VALVE_COMMAND),
>     #Enum("Rocket Power", 8, VALVE_COMMAND),
> ```

Why is this removed? 
___
*[`sources/rlcs/rlcs.py` line 47 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LIf353ZEf_QY2iYsg:-O2LIf353ZEf_QY2iYsh:b-rd2xli) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/rlcs.py#L47)):*
> ```Python
>     Numeric("Heater Kelvin Low 2 Voltage", 16, big_endian=False),
>     Numeric("Heater Kelvin High 1 Voltage", 16, big_endian=False),
>     Numeric("Heater Kelvin High 2 Voltage", 16, big_endian=False),
> ```

I will assume you have adjusted the voltage on RLCS to make this right
___
*[`sources/rlcs/rlcs.py` line 72 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LJwEd2wHkPD7Dgj04:-O2LJwEd2wHkPD7Dgj05:bi8xx5u) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/rlcs.py#L72)):*
> ```Python
>     for key in ["Heater Thermistor Voltage 1","Heater Thermistor Voltage 2"]:
>         if key in res:
>             res[key] = parse_adc_to_voltage(res[key],10,4.096)
> ```

Minor, but do you think that it should still be called voltage in the rlcs message if it's not actually the voltage anymore, at least not directly? Not a big deal though, I guess it's just voltage scaled?
___
*[`sources/rlcs/rlcs.py` line 108 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LKL6_4QFRT19n47zJ:-O2LKL6_4QFRT19n47zK:b-qulndk) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/rlcs.py#L108)):*
> ```Python
>     inpt_vlt=5.0
> 
>     #convert the adc output to voltage output
> ```

can get rid of this comment too
___
*[`sources/rlcs/rlcs.py` line 111 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LKvBg0mM2fultMnis:-O2LKvBg0mM2fultMnit:b-geyxym) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/rlcs.py#L111)):*
> ```Python
>     if 0.0 < divider_vlt < inpt_vlt:
>         #resistance of the thermistor calculated using voltage divider
>         thrmstr_rstnce = (vlt_dvdr_rstr*inpt_vlt/divider_vlt)-vlt_dvdr_rstr
> ```

This math checks out for me assuming we have 2 resistors in series

**Review by patrick-gu — APPROVED** [review]
This does in fact appear to actually work in practice

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-:-O2LTA_dCAkfkAnGVOa-:bwaq8vj)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @Pdada1, and @saads312)

___
*[`sources/rlcs/rlcs.py` line 24 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-O2LIQi1DW1EJDMFQQm6:-O2LT1AiCNooOUrRDvr0:b-e1exaa) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/695c615239ff4b6223812a070610c64a2bb91693/sources/rlcs/rlcs.py#L24)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

It's not actually in RLCS it turns out

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/277#-:-O2LYuX66CHD8kNzL0Ha:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @Lucifersan, @Pdada1, and @saads312)

**Pull request merged**
