### PR TITLE
Issue #35 - Creating development environment

### PR DESCRIPTION
**Pull request by DhritiGabani**
Adding the instructions to Readme.md.
- Creating a virtual environment
- Activating the virtual environment
- Upgrade pip version

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking good, just a few nitpicks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-:-MnNucddEpK1pGfSUwTR:byjmbpc)* status: all files reviewed, 3 unresolved discussions (waiting on @DhritiGabani)

___
*[README.md, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MnNu4mn-lM2AdWgwKZ_:-MnNu4moDzNEfH6XM-yu:bq622pt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7045908d2b9420dfd257491699e57eaa1337c2b0/README.md#L20)):*
> ```Markdown
> 2. Enter the newly-cloned repo with `cd omnibus`
> 3. Creating a virtual environment:
>    - For mac: `python3 -m venv devenv`
> ```

Nit, prefer `osx/linux` to `mac`.
___
*[README.md, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MnNstknEe92tTEye3zx:-MnNstknEe92tTEye3zy:bjk6c98) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7045908d2b9420dfd257491699e57eaa1337c2b0/README.md#L21)):*
> ```
>    - For mac: `python3 -m venv devenv`
>    - For windows: `python -m venv devenv`
> ```
I've generally seen `venv` used as the virtualenv folder, which also makes it ignored by our `.gitignore`. The ignoring isn't a big deal but good to stick to convention.
___
*[README.md, line 27 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MnNtO7g0ybychhi-Mx5:-MnNtO7g0ybychhi-Mx6:b-qgbryp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7045908d2b9420dfd257491699e57eaa1337c2b0/README.md#L27)):*
> ```Markdown
> 5. Upgrading pip version:
>    - For mac: `python3 -m pip3 install --upgrade pip3`
>    - For windows: `python3 -m pip install --upgrade pip` 
> ```

Earlier you used `python` as the windows python executable, best to be consistent (I think `python` is typically correct). Also why are you not upgrading pip3 on windows? Shouldn't everything "within" python be cross-platform?
Another thing to note is that the latter steps use `pip` directly (which should work when we're in the venv), might be cleaner to keep them all as directly `pip`.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Sorry for being picky, the readme is the first thing people see when they come to the repo. Almost there!

Also, when you've made changes you should open reviewable and flag the conversations as done. Feel free to DM me if you want to hop on a call and I can walk you through using it.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-:-Moka3kA7_AqOvFzV9zL:b-85jeyp)* status: all files reviewed, 4 unresolved discussions (waiting on @DhritiGabani)

___
*[README.md, line 19 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokZLb-3VdclYN5wt0Y:-MokZLb-3VdclYN5wt0Z:b-21py8g) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L19)):*
> ```Markdown
>     * If you don't have git configured with SSH (or you're not sure what that means), run `git clone https://github.com/waterloo-rocketry/omnibus.git`
> 2. Enter the newly-cloned repo with `cd omnibus`
> 3. Creating a virtual environment:
> ```

Proper tense is `Create`.
___
*[README.md, line 20 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokY5ns4DWpWkTsXQ6N:-MokY5ns4DWpWkTsXQ6O:b-ys9qid) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L20)):*
> ```Markdown
> 2. Enter the newly-cloned repo with `cd omnibus`
> 3. Creating a virtual environment:
>    - For osx/linux: `python3 -m venv venv`
> ```

Lets stick to `python` not `python3`. We can then remove this line and have the one command for all operating systems.
___
*[README.md, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokZe4A0JLHDEXDQMTN:-MokZe4A0JLHDEXDQMTO:bw1bkmf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L22)):*
> ```Markdown
>    - For osx/linux: `python3 -m venv venv`
>    - For windows: `python -m venv venv`
> 4. Activating the virtual environment:
> ```

Proper tense is `Activate`.
___
*[README.md, line 25 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokY-jw2RsgvDBFKMXO:-MokY-jw2RsgvDBFKMXP:b351plv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L25)):*
> ```Markdown
>    - For osx/linux: `source venv/bin/activate`
>    - For windows: `venv\Scripts\activate`
> 5. Upgrading pip version: `python -m pip install --upgrade pip` 
> ```

Proper tense is `Upgrade`. This can be `pip install --upgrade pip`, also you have trailing spaces.

**Review by DhritiGabani — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-:-MpJJwrw1CNNC6ldFnNi:b-896fix)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @BluCodeGH)

___
*[README.md, line 19 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokZLb-3VdclYN5wt0Y:-MpJJq0j2mSaNFJN9y6H:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L19)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Proper tense is `Create`.
</blockquote></details>

Done.
___
*[README.md, line 20 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokY5ns4DWpWkTsXQ6N:-MpJJkW06K0jIKsRYBJh:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L20)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Lets stick to `python` not `python3`. We can then remove this line and have the one command for all operating systems.
</blockquote></details>

Done.
___
*[README.md, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokZe4A0JLHDEXDQMTN:-MpJJqPCBjLWetbCY4af:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L22)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Proper tense is `Activate`.
</blockquote></details>

Done.
___
*[README.md, line 25 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-MokY-jw2RsgvDBFKMXO:-MpJJtVi7WR9Ast0INxi:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/4f78faa390810c7f053506c5b37296e8d541acd2/README.md#L25)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Proper tense is `Upgrade`. This can be `pip install --upgrade pip`, also you have trailing spaces.
</blockquote></details>

Done.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/36#-:-MpUPNdi5QrQ_dUoaQoh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DhritiGabani)

**Pull request merged**
