### PR TITLE
Dynamic Text bug fixes (WDR 2024)

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
A few small fixes from WDR, needs more testing, but testing locally seems to work

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257)

### CODE REVIEW

**Review by patrick-gu — APPROVED** [review]
one fix that should be removed (not invalid though) but otherwise 
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-:-O1UvREb5GdDONK1n9Ng:b1vexfg)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/items/dashboard_item.py` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-O1UvEcrAzWx3H_5PGgb:-O1UvEcrAzWx3H_5PGgc:b-uqzuxh) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/54baebe918ff911e140d47f933bfd9f3c588162b/sinks/dashboard/items/dashboard_item.py#L26)):*
> ```Python
>         self.corner_grabbed = False
>         self.corner_in = False
>         self.corner_size = 10
> ```

the corner size will be addressed in #256 so I think this should be removed to avoid merge conflicts

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
How can I test autocomplete?

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-:-O1UzCQJ0UVYnn_Gd-FB:bb5mn2d)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/items/dashboard_item.py` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-O1UvEcrAzWx3H_5PGgb:-O1Uy_Br0beJOnjYV6RC:bqog80t) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/54baebe918ff911e140d47f933bfd9f3c588162b/sinks/dashboard/items/dashboard_item.py#L26)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

the corner size will be addressed in #256 so I think this should be removed to avoid merge conflicts
</blockquote></details>

Agreed
___
*[`sinks/dashboard/items/dynamic_text.py` line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-O1Uz33T8P4z8j1476aS:-O1Uz33T8P4z8j1476aT:b-2aagjj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/54baebe918ff911e140d47f933bfd9f3c588162b/sinks/dashboard/items/dynamic_text.py#L123)):*
> ```Python
>         self.expired_timeout.stop()
>         self.expired_timeout.start(int(EXPIRED_TIME * 1000))
>         # self.resize(10, 10)  # trigger size update
> ```

Why was this commented out?

**Comment by zangjiucheng** [comment]
If needed I can help solving conflict :)), as that my part of code lol!

**Review by patrick-gu — COMMENTED** [review]
Thanks @zangjiucheng 

@Darth-Raazi You can test it by running fakeni and seeing if it autocompletes typing "Fake1". It works for me 

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-:-O1igAi-40WbB0mtRI4y:b-xgepas)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/items/dynamic_text.py` line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-O1Uz33T8P4z8j1476aS:-O1ig79B-czhlHpBTwLH:b-ck2yl0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/54baebe918ff911e140d47f933bfd9f3c588162b/sinks/dashboard/items/dynamic_text.py#L123)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Why was this commented out?
</blockquote></details>

Causes a massive amount of weirdness when you try to resize the item

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-:-O1jLFCF0Upu3NNtuvXx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/items/dynamic_text.py` line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/257#-O1Uz33T8P4z8j1476aS:-O1jLDCM4MtCOGIbAB8l:blxn1pq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/54baebe918ff911e140d47f933bfd9f3c588162b/sinks/dashboard/items/dynamic_text.py#L123)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Causes a massive amount of weirdness when you try to resize the item
</blockquote></details>

Please delete it then

**Pull request merged**
