### PR TITLE
J22huan/205 added doubleclick

### LINKED ISSUE #205: Fix Property Panel Opening
Currently, selecting a dashitem opens its property panel which is really annoying when trying to move stuff around. Instead, a single click should select the item and a double-click should open the property panel

### PR DESCRIPTION
**Pull request by jeffrey-huang-yz**
## Description

Changed the property panel so that it only opens after double-clicking an item, and closes when the user clicks outside the item.

Added mouse double click event under QGraphicsViewWrapper to open property panel on double click
Added reference to dashboard instance in QGraphicsViewWrapper to identify which item is being clicked
Changed on_selection_changed function to close the property panel

This PR closes #205 .

## Developer Testing

Didn't test very extensively but I did the following: 

- Tested the opening and closing of the property panel with various dashboard items (double click to open, left click off to close) 
- Opened and closed property panel while displaying data or after modifying properties 

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Try the above ^ 

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/227)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
This appears to work to me! Great job.

I get this in the console when I click on the graph:
```
QSplitter::replaceWidget: Trying to replace a widget with itself
```

Also, please let me know how you tested and how I can test just so that we can check this thoroughly. It would also be good to have some thoughts from @Darth-Raazi if possible

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/227#-:-Nz9jnbJC9oCVPxpb37B:b-61uopu)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Works for me as well, great job! I'm also getting that error so please debug that

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/227#-:-NzBAHUsDkyKay6sAQ9Y:bb1imre)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @jeffrey-huang-yz, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 310 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/227#-NzBBZqD7fmgda2OhEKR:-NzBBZqD7fmgda2OhEKS:b-p8dsd2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/164c3acfe097e5a337fd8b35bbe0130ae04ebf66/sinks/dashboard/dashboard.py#L310)):*
> ```Python
> 
>     # On selection changed, hide the parameter tree
>     def on_selection_changed(self):
> ```

What's the difference between this method and the if statement in the above method? Is there a reason we need both?

**Comment by jeffrey-huang-yz** [comment]
*[`sinks/dashboard/dashboard.py` line 310 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/227#-NzBBZqD7fmgda2OhEKR:-NzBIfAh4UhcAk7qiwDO:b-lomtwc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/164c3acfe097e5a337fd8b35bbe0130ae04ebf66/sinks/dashboard/dashboard.py#L310)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

What's the difference between this method and the if statement in the above method? Is there a reason we need both?
</blockquote></details>

The if statement was from the original code to ensure the property panel is hidden when multiple items are selected. I don't think it's necessary anymore, so I'll remove it. With the method, selecting more than one item should close the property panel anyway 👍

**Review by patrick-gu — APPROVED** [review]
Seems to be fixed! 
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/227#-:-NzY_i0K3rC69LegbGmj:bn02emn)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/227#-:-NzaKjxBDOpiDDvw1gdN:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Lucifersan, and @saads312)

**Pull request merged**
