### PR TITLE
Use UDP broadcasts to automatically detect server IP

### PR DESCRIPTION
**Pull request by BluCodeGH**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6)

### CODE REVIEW

**Comment by BluCodeGH** [comment]
This has been tested with multiple components on one machine (no port reuse conflicts) and across multiple machines and operating systems (no linux/windows incompatibilities).

**Review by wendi-yu — APPROVED** [review]
Cool looks good to me! I'm assuming you tested it and it works, in which case :shipit:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6#-:-MbsGGRD4IR40UDSBIDh:bkmkpz3)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[omnibus/omnibus.py, line 23 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6#-MbsFwdP7TvCZnWdTiQA:-MbsFwdP7TvCZnWdTiQB:b-6x4m7k) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/23b17d43a5af941d90b916d897d50f5ab632bfa7/omnibus/omnibus.py#L23)):*
> ```Python
> class OmnibusCommunicator:
>     """
>     Handles state shared between senders and receivers.
> ```

Up to you if you wanna do it in this PR or not but same old nit about docstrings in the imperative mood (ie `Handle` not `Handles`)
___
*[omnibus/omnibus.py, line 55 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6#-MbsFpeC2hUsl8TiZh5G:-MbsFpeC2hUsl8TiZh5H:b-q1cune) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/23b17d43a5af941d90b916d897d50f5ab632bfa7/omnibus/omnibus.py#L55)):*
> ```Python
>                     pass
>                 print("Could not detect server IP. Please ensure it is running.")
>                 if ip := input("Press enter to retry or manually enter the server IP: ").strip():
> ```

I didn't know this initialization syntax was a thing, very cool :0 Python looks more like pseudocode every day lol

**Review by BluCodeGH — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[omnibus/omnibus.py, line 23 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6#-MbsFwdP7TvCZnWdTiQA:-Mbsomky6Dkh-wNtLQTI:b-ll2jnv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/23b17d43a5af941d90b916d897d50f5ab632bfa7/omnibus/omnibus.py#L23)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Up to you if you wanna do it in this PR or not but same old nit about docstrings in the imperative mood (ie `Handle` not `Handles`)
</blockquote></details>

I get the imperative mood for functions but to me it's pretty awkward when it comes to classes, I'm going to leave as is also for consistency with the other classes in omnibus.
___
*[omnibus/omnibus.py, line 55 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6#-MbsFpeC2hUsl8TiZh5G:-MbspJoF-CtIh3z02cnY:b-9qoyhu) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/23b17d43a5af941d90b916d897d50f5ab632bfa7/omnibus/omnibus.py#L55)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I didn't know this initialization syntax was a thing, very cool :0 Python looks more like pseudocode every day lol
</blockquote></details>

Yes and it's even called the ***walrus operator***.

**Review by BluCodeGH — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

**Pull request merged**
