### PR TITLE
Unified parameters completed

### PR DESCRIPTION
**Pull request by AvKat**
Okay so this is basically the same things as #104. Made a new PR because rebasing the original was a worse task than this. I have (tried to) addressed everything that was discussed in the previous post. Let me know if there's any more concerns!

(also, i just resolved the conflicts and looked at the 3d plots and i have to say, they look great)

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great! One thing I noticed is that I get a `Internal C++ object (PySide6.QtWidgets.QPushButton) already deleted` error in the terminal whenever I toggle one of the series checkboxes, and it takes a good second after that for the plot to actually update. Any idea what's up with that?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-:-NTBAj4yCOH-ntD0Ws0f:b-v34865)* status: all files reviewed, 3 unresolved discussions (waiting on @AvKat, @Darth-Raazi, @KavinSatheeskumar, and @yxyyeah)

___
*[`sinks/dashboard/dashboard.py` line 334 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTBAKTh-_GMS-28pUPs:-NTBAKTh-_GMS-28pUPt:b-bsgp4b) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1c716e52b18d7a1dfd4cb929845f30d72edf8794/sinks/dashboard/dashboard.py#L334)):*
> ```Python
>                 if type(dashitem) == item_type:
>                     data["widgets"].append({"class": item_type.get_name(),
>                                             "params": dashitem.get_serialized_parameters(),
> ```

I see what you meant with the "saving all the series" issue, but that goes away if you use `dashitem.get_parameters().saveState(filter="user")`. Then you can `restoreState` later, and it handles recursive parameters which the current method doesn't.
___
*[`sinks/dashboard/items/dashboard_item.py` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTB80ch8h6kzgmEnqQP:-NTB80ch8h6kzgmEnqQQ:blzsrq0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1c716e52b18d7a1dfd4cb929845f30d72edf8794/sinks/dashboard/items/dashboard_item.py#L53)):*
> ```Python
>             self.parameters.child("height").setValue(self.size().height())
> 
>     def addParameters(self):
> ```

`snake_case`.
___
*[`sinks/dashboard/items/dashboard_item.py` line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTB87t24QTqM4XwzCr7:-NTB87t24QTqM4XwzCr8:b-ciom25) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1c716e52b18d7a1dfd4cb929845f30d72edf8794/sinks/dashboard/items/dashboard_item.py#L60)):*
> ```Python
>         return []
> 
>     def prompt_for_parameters(self):
> ```

Unused.

**Review by AvKat — COMMENTED** [review]
I could not replicate the Internal C++ error. The delay in updating is so that we can do multiple changes and it will only trigger one event. It is an inbuilt feature of the parameter tree which can be turned off but it's very efficient to keep it on.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-:-NTf-exe-F95wfA61pXE:bv6pw46)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, and @yxyyeah)

___
*[`sinks/dashboard/dashboard.py` line 334 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTBAKTh-_GMS-28pUPs:-NTf02yn07okip9hQ8Bl:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1c716e52b18d7a1dfd4cb929845f30d72edf8794/sinks/dashboard/dashboard.py#L334)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I see what you meant with the "saving all the series" issue, but that goes away if you use `dashitem.get_parameters().saveState(filter="user")`. Then you can `restoreState` later, and it handles recursive parameters which the current method doesn't.
</blockquote></details>

Done
___
*[`sinks/dashboard/items/dashboard_item.py` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTB80ch8h6kzgmEnqQP:-NTf05U86NF1BR_duoz0:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1c716e52b18d7a1dfd4cb929845f30d72edf8794/sinks/dashboard/items/dashboard_item.py#L53)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`snake_case`.
</blockquote></details>

Done
___
*[`sinks/dashboard/items/dashboard_item.py` line 60 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTB87t24QTqM4XwzCr7:-NTf0F9H3LcTL7Cwotow:bb6un1j) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1c716e52b18d7a1dfd4cb929845f30d72edf8794/sinks/dashboard/items/dashboard_item.py#L60)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unused.
</blockquote></details>

Done

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @AvKat, @BluCodeGH, @Darth-Raazi, and @yxyyeah)

___
*[`sinks/dashboard/items/plot_3D_orientation.py` line 20 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTz5R4B6q0Z93LCZ4WQ:-NTz5R4B6q0Z93LCZ4WR:b-21pliw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/16240321f136fdb9b1d8e53d0b844577d54621ed/sinks/dashboard/items/plot_3D_orientation.py#L20)):*
> ```Python
>         self.setLayout(self.layout)
> 
>         self.series = self.parameters.param('series').value()
> ```

So, if the default choice of series is wrong, this can can cause the entire widget to error its ass off. The suggested fix is below.
___
*[`sinks/dashboard/items/plot_3D_orientation.py` line 71 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTzI1d8-Krb1isMqfhM:-NTzI1d96Zai9W3iUxNl:b-1i480b) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/16240321f136fdb9b1d8e53d0b844577d54621ed/sinks/dashboard/items/plot_3D_orientation.py#L71)):*
> ```Python
>     def on_data_update_orientation(self, stream, payload):
>         time, orientation = payload
> ```

Add the following code to stop errors



_Code snippet:_
```Python
## Ensuring orientation is of the right format.
match orientation:
    case x, y, z:
        pass
    case _:
        return None
```

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-:-NUEgjK846WL4ZZy12-t:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @AvKat, @Darth-Raazi, and @yxyyeah)

**Review by AvKat — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, and @yxyyeah)

___
*[`sinks/dashboard/items/plot_3D_orientation.py` line 20 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTz5R4B6q0Z93LCZ4WQ:-NUFJg3e0GPwRsTsv9z5:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/16240321f136fdb9b1d8e53d0b844577d54621ed/sinks/dashboard/items/plot_3D_orientation.py#L20)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

So, if the default choice of series is wrong, this can can cause the entire widget to error its ass off. The suggested fix is below.
</blockquote></details>

done
___
*[`sinks/dashboard/items/plot_3D_orientation.py` line 71 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NTzI1d8-Krb1isMqfhM:-NUFJh9q1ZnJvJ0cfJ_g:b-k73z76) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/16240321f136fdb9b1d8e53d0b844577d54621ed/sinks/dashboard/items/plot_3D_orientation.py#L71)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Add the following code to stop errors
</blockquote></details>

thanks

**Review by itslinotlie — COMMENTED** [review]
I would consider adding comments for the new stuff, such as:
- what the QSplitter accomplishes
- parameter tree
- ```self.splitter.setCollapsible(0, False)``` (what this line does)


Other things:
- in this comment ```# Get the coordinates of the proxy widget on the view not the scene```, just remove the 'not the scene' part

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-:-NUHdxJw9WY1aXIDhPYW:bxr1mnr)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, and @yxyyeah)

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @AvKat, @BluCodeGH, @Darth-Raazi, and @yxyyeah)

___
*[`sinks/dashboard/dashboard.py` line 199 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NUI7jWC4rpRTXQwF162:-NUI7jWC4rpRTXQwF163:bzhpmsg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fc66a5cb69459927ee565a322fbe27f2ccf2ecba/sinks/dashboard/dashboard.py#L199)):*
> ```Python
>             return
>         # Show the tree
>         item = self.widgets[items[0]][1]
> ```

Another bug
If I
* select a dash item
* close the window

I will get a segmentation fault on exit. I believe the best way to handle this is adding `self.parameter_tree.hide()` in the close event handler.
https://doc.qt.io/qtforpython-5/PySide2/QtGui/QCloseEvent.html
___
*[`sinks/dashboard/dashboard.py` line 215 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NUI5rdZCErQiqc_9ARt:-NUI5rdZCErQiqc_9ARu:bc7heya) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fc66a5cb69459927ee565a322fbe27f2ccf2ecba/sinks/dashboard/dashboard.py#L215)):*
> ```Python
>         height = item.parameters.param('height').value() + 1
>         pos = proxy.pos()
>         proxy.parentItem().setRect(pos.x(), pos.y(), width, height)
> ```

So, I found the following bug.
If I
* resize a dash item
* save the current config
* delete the dashitem and load

the newly generated dash item does not have the correct size. This is because the above few lines are not called within the `add` method. Causing the widget to be placed at the default size.

**Review by AvKat — COMMENTED** [review]
i added some comments. let me know if that's enough

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-:-NUId0tR2YXDKljD4VGW:be6n7lu)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, and @yxyyeah)

___
*[`sinks/dashboard/dashboard.py` line 199 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NUI7jWC4rpRTXQwF162:-NUId77-ERWsuW9bTuly:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fc66a5cb69459927ee565a322fbe27f2ccf2ecba/sinks/dashboard/dashboard.py#L199)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

Another bug
If I
* select a dash item
* close the window

I will get a segmentation fault on exit. I believe the best way to handle this is adding `self.parameter_tree.hide()` in the close event handler.
https://doc.qt.io/qtforpython-5/PySide2/QtGui/QCloseEvent.html
</blockquote></details>

done
___
*[`sinks/dashboard/dashboard.py` line 215 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-NUI5rdZCErQiqc_9ARt:-NUId8EaAjqdMCvs_KH5:b-tk5vs4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fc66a5cb69459927ee565a322fbe27f2ccf2ecba/sinks/dashboard/dashboard.py#L215)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

So, I found the following bug.
If I
* resize a dash item
* save the current config
* delete the dashitem and load

the newly generated dash item does not have the correct size. This is because the above few lines are not called within the `add` method. Causing the widget to be placed at the default size.
</blockquote></details>

i thought that was being done implicitly but i forgot to change the order of some things in `dash_item.py`. it's handled now

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/105#-:-NUJlI-uBC1cydOBZsg7:bnfp4nl)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Darth-Raazi, and @yxyyeah)

**Pull request merged**
