### PR TITLE
PyQt Plot Implementation (new PR)

### PR DESCRIPTION
**Pull request by PCModeActivate**
PR #9 but with less git mess now! The changes suggested from PR #9 are implemented, responses to feedbacks are posted in PR #9 as well.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Great start! One feature I'd really like to see is a display of the FPS (averaged) and latency (difference between the current time and the most recently received `timestamp`) somewhere on the UI. Also proper horizontal axes in seconds would be great, but I'm not sure how much work that would be to implement.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-:-McwTrk23p4SxlSdKn6x:bodxky2)* status: all files reviewed, 16 unresolved discussions (waiting on @jacobdeery, @jli35, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[requirements.txt, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwDamy0npOxgDR8jnx:-McwDamy0npOxgDR8jny:b-dcz7au) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/requirements.txt#L5)):*
> ```help
> numpy==1.20.2
> PySide6==6.1.0
> pyqtgraph==0.12.1
> ```

Since these requirements are plot-specific they should go in their own `requirements.txt` in `sinks/plot/`
___
*[omnibus/omnibus.py, line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwSerO-0T5LzPYK88c:-McwSerO-0T5LzPYK88d:bs1pg8f) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/omnibus/omnibus.py#L123)):*
> ```Python
>         if self.subscriber.poll(timeout):
>             channel, timestamp, payload = self.subscriber.recv_multipart()
>             return Message(channel.decode("utf-8"), msgpack.unpackb(timestamp), msgpack.unpackb(payload, encoding = "utf-8"))
> ```

Turns out the encoding parameter was removed in version 1.0 of msgpack and now defaults to utf-8, please make sure your libraries are up to date :slightly_smiling_face:.
___
*[sinks/plot/main.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwRKow7nL4WoTQl4BU:-McwRKox0QU4X-H4F_V9:blgisdm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L1)):*
> ```Python
> import sys
> ```

Unused import
___
*[sinks/plot/main.py, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwROXKBg_az3WL_2Tw:-McwROXKBg_az3WL_2Tx:bae7vua) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L5)):*
> ```Python
> from omnibus import Receiver
> 
> from pyqtgraph.Qt import QtGui, QtCore
> ```

`QtGui` unused import
___
*[sinks/plot/main.py, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwRM2d7hNbf9LW-7IF:-McwRM2d7hNbf9LW-7IG:blgisdm) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L9)):*
> ```Python
> import numpy as np
> 
> import time
> ```

Unused import
___
*[sinks/plot/main.py, line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwEmI8-3Zwz8txTbDX:-McwEmI8-3Zwz8txTbDY:bh41fkv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L11)):*
> ```Python
> import time
> 
> demo = True  # Demo Mode
> ```

This probably shouldn't go in the final code, instead I'd suggest directly setting it up with the fake channels (manually type them out) so that it works with fakeni and acts as an example of where to put the real sensor names.
___
*[sinks/plot/main.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwEhYo8Aj2SiXLY_zK:-McwEhYo8Aj2SiXLY_zL:b-su2ccv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L14)):*
> ```Python
> 
> CHANNEL = ""
> SENSOR_COUNT = 0
> ```

Use of this should be replaced by `len(SENSORS)`.
___
*[sinks/plot/main.py, line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwRh3DAsKqsNxyKRxm:-McwRh3DAsKqsNxyKRxn:bf3xjsj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L33)):*
> ```Python
> min_col = int(np.sqrt(SENSOR_COUNT))+1
> min_row = int(SENSOR_COUNT / min_col)+1
> layout_size = (min_col, min_row)
> ```

Nit but this probably isn't worth declaring as a variable just to be used once a few lines down.
___
*[sinks/plot/main.py, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwRqEe01A4PtbG2ILR:-McwRqEe01A4PtbG2ILS:b-nigh0i) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L38)):*
> ```Python
> win = pg.GraphicsLayoutWidget(show=True, title="Random Data Example", size=layout_size)
> win.resize(1000, 600)
> win.setWindowTitle('pyqtgraph: Random Data Example')
> ```

Thankfully we've moved beyond this being just a random data example.
___
*[sinks/plot/main.py, line 47 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwFYlr0QCp9oXEgXUs:-McwFYlr0QCp9oXEgXUt:bhr5ihd) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L47)):*
> ```
> for i in range(0, min_row):
>     for j in range(min_col if i != (min_row - 1) else last_row_count):
>         plots.append(win.addPlot(row=i, col=j, title=("Sensor: " + SENSORS[i*min_col + j])))
> ```
You could consider splitting this into two for loops, one that does all but the last row and another to do the last row.
___
*[sinks/plot/main.py, line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwFhZE4mi0EG3WO_Zo:-McwFhZE4mi0EG3WO_Zp:bmhbyit) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L52)):*
> ```Python
> curves = [plots[i].plot(pen='y') for i in range(SENSOR_COUNT)]
> 
> graph_dp = 100 # 100 data points in the graph
> ```

This should be a constant at the top.
___
*[sinks/plot/main.py, line 61 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwOFNK7cQkw1MmmGPI:-McwOFNLCm_5sp7xhFCh:by4up6n) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L61)):*
> ```Python
>         for i, sensor in enumerate(SENSORS):
>             # Update Data Stream, currently only grabbing the first element in the payload obj
>             data_streams[i].append(new_data["data"][sensor][0])
> ```

Because different data sources sample at different rates there isn't actually a guarantee that every sensor is in every message.  There should be a check for if `sensor in new_data["data"]` around this (and the lines below!).
___
*[sinks/plot/main.py, line 66 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwH-eA0rsUP6P9Qn93:-McwH-eA0rsUP6P9Qn94:bhljd3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L66)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             # whereby the payload is currently parsed as dictionary of a list (of a list)
>             # the dictionary should have a key value pair where the key is the "data type", in this case "data"
>             # the value is then a list of sensors, which consist of a list of data registered from each sensor
>             # currently we are only plotting the first data point in each sensor
> ```
</details>

This explanation isn't correct, it's a dictionary containing a dictionary of lists and the data type is determined by the channel, not the key "data". An example of the data is probably a clearer explanation anyways though, for example:
```
{
  "timestamp": float,
  "data": {
    "Sensor 1": [float, float, ...],
    "Sensor 2": [float, float, ...],
    ...
  }
}
```
___
*[sinks/plot/main.py, line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwQCuZ-Bxf6fzBsDAX:-McwQCuZ-Bxf6fzBsDAY:b81wn5d) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L75)):*
> ```Python
> timer = QtCore.QTimer()
> timer.timeout.connect(update)
> timer.start(0)
> ```

We probably want to cap this at 60fps so replace the zero with 16 (`1000 ms / 16 ~= 60 fps`).
___
*[sinks/plot/main.py, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwQZEV8fKpyZABQYlB:-McwQZEV8fKpyZABQYlC:b-fde1q8) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L78)):*
> ```Python
> 
> if __name__ == '__main__':
>     pg.mkQApp().exec_()
> ```

I get a `DeprecationWarning` about `.exec_()`, replace with just `.exec()` (and make sure your library is up to date :stuck_out_tongue:).
___
*[sources/fakeni/main.py, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwSXcK2vpMEfnHK1PA:-McwSXcL7EPMeFh5q1Xv:b-fkkjul) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sources/fakeni/main.py#L17)):*
> ```Python
>     }
>     sender.send(data)
>     time.sleep(max(READ_BULK/SAMPLE_RATE - (time.time() - start), 0))
> ```

Looks like all the blank lines accidentally got removed here, would be nice to get them back.

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11)* status: 1 of 6 files reviewed, 14 unresolved discussions (waiting on @BluCodeGH, @jacobdeery, @jli35, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[requirements.txt, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwDamy0npOxgDR8jnx:-MdKrdoB-8rnGdKfzx00:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/requirements.txt#L5)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Since these requirements are plot-specific they should go in their own `requirements.txt` in `sinks/plot/`
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 1 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwRKow7nL4WoTQl4BU:-MdKreSxENBI5McKfSMN:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L1)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unused import
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwROXKBg_az3WL_2Tw:-MdKrfwHEYGPqWu4mLXm:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L5)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

`QtGui` unused import
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwRM2d7hNbf9LW-7IF:-MdKrgWoA0j0YtNNCoMT:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L9)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unused import
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwEmI8-3Zwz8txTbDX:-MdKrh-M3TeTyDO8fb5-:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L11)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This probably shouldn't go in the final code, instead I'd suggest directly setting it up with the fake channels (manually type them out) so that it works with fakeni and acts as an example of where to put the real sensor names.
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 14 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwEhYo8Aj2SiXLY_zK:-MdKrhen7PEzpzRmgnWb:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L14)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Use of this should be replaced by `len(SENSORS)`.
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 38 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwRqEe01A4PtbG2ILR:-MdKrjAZ94bFsiGXG4u_:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L38)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Thankfully we've moved beyond this being just a random data example.
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwFhZE4mi0EG3WO_Zo:-MdKrkA2CLBN0IW8a9A5:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L52)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

This should be a constant at the top.
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 61 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwOFNK7cQkw1MmmGPI:-MdKmXH47s5UZh5FAmK2:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L61)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Because different data sources sample at different rates there isn't actually a guarantee that every sensor is in every message.  There should be a check for if `sensor in new_data["data"]` around this (and the lines below!).
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 66 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwH-eA0rsUP6P9Qn93:-MdKrlX378o3cHj6E0-m:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L66)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

> ```
>             # whereby the payload is currently parsed as dictionary of a list (of a list)
>             # the dictionary should have a key value pair where the key is the "data type", in this case "data"
>             # the value is then a list of sensors, which consist of a list of data registered from each sensor
>             # currently we are only plotting the first data point in each sensor
> ```
This explanation isn't correct, it's a dictionary containing a dictionary of lists and the data type is determined by the channel, not the key "data". An example of the data is probably a clearer explanation anyways though, for example:
```
{
  "timestamp": float,
  "data": {
    "Sensor 1": [float, float, ...],
    "Sensor 2": [float, float, ...],
    ...
  }
}
```
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 75 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwQCuZ-Bxf6fzBsDAX:-MdKrmLqB07ahgcQhbl1:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L75)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

We probably want to cap this at 60fps so replace the zero with 16 (`1000 ms / 16 ~= 60 fps`).
</blockquote></details>

Done.
___
*[sinks/plot/main.py, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwQZEV8fKpyZABQYlB:-MdKrmmA8OAplmS4TLBd:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sinks/plot/main.py#L78)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I get a `DeprecationWarning` about `.exec_()`, replace with just `.exec()` (and make sure your library is up to date :stuck_out_tongue:).
</blockquote></details>

Done.
___
*[sources/fakeni/main.py, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-McwSXcK2vpMEfnHK1PA:-MdKrnk4BbiFGH6JpvLU:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d37dd165663ff2147a9346ac88ccc112401dc076/sources/fakeni/main.py#L17)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Looks like all the blank lines accidentally got removed here, would be nice to get them back.
</blockquote></details>

Done.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Great work, just a couple tiny things from me.

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-:-MdKuCRf7isKbGlQXRS4:b-b5sjqz)* status: all files reviewed, 2 unresolved discussions (waiting on @jacobdeery, @jli35, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/main.py, line 12 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-MdKsgIlAC3hWhBE_9yj:-MdKsgIlAC3hWhBE_9yk:b-4msd5u) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/540a2d17f2ed1e054aca5f522434bea0ad6b948b/sinks/plot/main.py#L12)):*
> ```Python
> SENSOR_COUNT = len(SENSORS)
> 
> graph_dp = 100  # 100 data points in the graph
> ```

Constants should be all caps, this should also come before SENSOR_COUNT since it's still something the user might want to change.
___
*[sinks/plot/main.py, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-MdKsZ5xEfYmFvYUUY0e:-MdKsZ5xEfYmFvYUUY0f:b1q9y7q) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/540a2d17f2ed1e054aca5f522434bea0ad6b948b/sinks/plot/main.py#L22)):*
> ```Python
> last_row_count = SENSOR_COUNT - min_col*(min_row - 1)
> 
> win = pg.GraphicsLayoutWidget(show=True, title="Random Data Example", size=(min_row, min_col))
> ```

Thankfully we've moved beyond this being just a random data example part 2: electric boogaloo.

**Review by PCModeActivate — COMMENTED** [review]
Timestamp and Latency are displayed on the title of the window now; x-axis now has ticks in integer second increments, updated every second.
Scroll-too-fast might still be problematic; while it may be fixed by the custom x-axis, we currently do not have other solutions to this problem if it persists.

Another note is that there may be display bugs (flashing white strips/lines occasionally). However, this might be a local (my own computer) issue.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-:-MdZYQbFDI8NglLEnRZk:brfo5vp)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @jacobdeery, @jli35, @KavinSatheeskumar, and @wendi-yu)

___
*[sinks/plot/main.py, line 12 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-MdKsgIlAC3hWhBE_9yj:-MdKwBsOAzyEnjGE-yv2:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/540a2d17f2ed1e054aca5f522434bea0ad6b948b/sinks/plot/main.py#L12)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Constants should be all caps, this should also come before SENSOR_COUNT since it's still something the user might want to change.
</blockquote></details>

Done.

**Review by wendi-yu — COMMENTED** [review]
Just some missing newlines, otherwise lgtm

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-:-Me2Y6DQ-NJ3rlwuxAob:b-e9rjue)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[sinks/plot/requirements.txt, line 3 at r6](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-Me2Y40jALCfBH7-HCWY:-Me2Y40jALCfBH7-HCWZ:bslbn0w) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fc531582926753006519406ac1aa7c2347457efe/sinks/plot/requirements.txt#L3)):*
> ```help
> numpy==1.20.2
> PySide6==6.1.0
> pyqtgraph==0.12.1
> ```

Missing newline I think
___
*[sources/fakeni/main.py, line 22 at r6](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-Me2Y1lz3ge-hybhqLAQ:-Me2Y1m-4CCeYzqMV4ep:b-cbnloc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fc531582926753006519406ac1aa7c2347457efe/sources/fakeni/main.py#L22)):*
> ```Python
>     }
>     sender.send(data)
>     time.sleep(max(READ_BULK/SAMPLE_RATE - (time.time() - start), 0))
> ```

Missing newline here?

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/11#-:-MeIT1n06cq7EXMSzib9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jacobdeery, @jli35, and @KavinSatheeskumar)

**Pull request merged**
