### PR TITLE
Change color when hits limit

### PR DESCRIPTION
**Pull request by yxyyeah**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great! A few nitpicks:

Looks like you still have some trailing whitespace on blank lines, maybe run autopep8 manually if the format script isn't working? Eg:


> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-:-NH2yapP9txS5koFUijp:b-61dq6q)* status: all files reviewed, 2 unresolved discussions (waiting on @yxyyeah)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 46 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH2xpp5EgrJXHqKhf5j:-NH2xpp5EgrJXHqKhf5k:b8k1ehj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L46)):*
> ```Python
>             )
>             if not channel_and_series:
>                 raise Exception
> ```

Under what circumstances could this not give a value? Seems like that is a bug to fix in prompt_user such that it ensures we get a valid return. 
___
*[`sinks/dashboard/items/plot_dash_item.py` line 102 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH2yL_y-U-tznV82Tw7:-NH2yL_y-U-tznV82Tw8:b-7a77tf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L102)):*
> ```Python
> 
>         # plot the warning line
>         self.warning_line.setData(times,[self.limit] * len(points))
> ```

What if we initialize the warning line with two points: (0, limit) and (verybignumber, limit)? Would it then always display and save the performance overhead of updating it every time?

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH and @yxyyeah)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 46 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH2xpp5EgrJXHqKhf5j:-NH6uT914lGevcnz9Knd:b-86zs87) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L46)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Under what circumstances could this not give a value? Seems like that is a bug to fix in prompt_user such that it ensures we get a valid return. 
</blockquote></details>

None is a sential signaling that the user quit their selection. The correct behaviour is not adding the dashitem to the screen. IE the user decides they don't wanna add the thing anymore.

The fact that we throw an exception instead of doing that is the real bug
___
*[`sinks/dashboard/items/plot_dash_item.py` line 55 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH6ukgL4Z6j-YHUCrcd:-NH6ukgM8iZCSGRgeM5-:bx9xufg) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L55)):*
> ```Python
>             )
>             if threshold_input == None:
>                 raise Exception
> ```

It should be possible for there not to be a threshold. 

Maybe we should prompt them for text instead, and if they input a non-number, then we default to having no threshold

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75)* status: all files reviewed, 4 unresolved discussions (waiting on @BluCodeGH and @yxyyeah)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 52 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH6xtLoDiXQE36YxCpw:-NH6xtLoDiXQE36YxCpx:br6h6ty) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L52)):*
> ```Python
>                 "Threshold Value",
>                 "Set an upper limit",
>                 "number"
> ```

This is a bug on my code, but it seems that it only lets me select a multiple of 0.1, this would also be resolved by the below suggestion
___
*[`sinks/dashboard/items/plot_dash_item.py` line 102 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH2yL_y-U-tznV82Tw7:-NH6ye9rDvuGTF5dMTk6:b-54kz20) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L102)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

What if we initialize the warning line with two points: (0, limit) and (verybignumber, limit)? Would it then always display and save the performance overhead of updating it every time?
</blockquote></details>

This is a bug I found whilst poking at it.

If I set the limit to below the graph limits, it doesn't show. IDK if its worth fixing, but its worth pointing out

**Comment by yxyyeah** [comment]
>

**Comment by yxyyeah** [comment]
> What if we initialize the warning line with two points: (0, limit) and (verybignumber, limit)? Would it then always display and save the performance overhead of updating it every time?
Then the plot would always display the range from 0-verybignumber. In that case I may need to update the range of the x axis each time. Which one would perform better: updating the line or the axis? Also each time I can draw a line with 2 points (starting and finishing) instead of all points in times. Does this sounds better?

**Comment by BluCodeGH** [comment]
Yeah i think two points sounds better. We should also try to fix the issue kavin mentioned with the fill disappearing when below the plot

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75)* status: all files reviewed, 4 unresolved discussions (waiting on @KavinSatheeskumar and @yxyyeah)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 46 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH2xpp5EgrJXHqKhf5j:-NHbsxyaBaz48tAeRI_B:b-q6gmpj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L46)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

None is a sential signaling that the user quit their selection. The correct behaviour is not adding the dashitem to the screen. IE the user decides they don't wanna add the thing anymore.

The fact that we throw an exception instead of doing that is the real bug
</blockquote></details>

Is this something we should resolve here?
___
*[`sinks/dashboard/items/plot_dash_item.py` line 102 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/75#-NH2yL_y-U-tznV82Tw7:-NHbt-Vu29g3faEBtEix:b9zme7g) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7ffa57bcefc3ec6c3baa6276eafcbccb5b3ce104/sinks/dashboard/items/plot_dash_item.py#L102)):*
<details><summary><i>Previously, KavinSatheeskumar (Kavin Satheeskumar) wrote…</i></summary><blockquote>

This is a bug I found whilst poking at it.

If I set the limit to below the graph limits, it doesn't show. IDK if its worth fixing, but its worth pointing out
</blockquote></details>

Any idea how we can fix this? I think it's important to always have that red tint when the data is over the limit.

**Comment by yxyyeah** [comment]
@BluCodeGH 

> Is this something we should resolve here?

New PR is on the way!

> Any idea how we can fix this? I think it's important to always have that red tint when the data is over the limit.

I think we do have the red tint when data is over the limit. So not an issue anymore

**Comment by yxyyeah** [comment]
Changes of this PR has been merged into [prompt_for_properties PR](https://github.com/waterloo-rocketry/omnibus/pull/79). Maybe we can close this one

**Comment by BluCodeGH** [comment]
Closing for tidiness, included in #79.

**Pull request closed without merging**
