### PR TITLE
Optimize mouse corner detect algorithm

### PR DESCRIPTION
**Pull request by zangjiucheng**
## Description

This is a HotFix to improve the mouse corner detection algorithm for small widgets.

I changed the `dashboard_item.py` corner_size calculate formula.
- corner_size dynamic change
- for small widgets, only the right-down corner is enabled to scale the widget.

## Reviewer Testing

Here's what you should do to quickly validate my changes:
- It's just improved for some situations (small widgets especially). Test it any way you want :)

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/256)

### CODE REVIEW

**Review by Darth-Raazi — COMMENTED** [review]
I like the changes you've made, they work well. One thing I noticed is that not all the corners resize like they're supposed to. Instead of "pulling" the corner you're currently clicking, some of the corners "pull" the opposite corner instead. See video below:
[Screen Recording 2024-07-10 at 10.18.21 PM.mov](https://files.reviewableusercontent.io/images/reviewable/67076803/BCeR5SKN4LH5-3_1E21hvO1C/Screen%20Recording%202024-07-10%20at%2010.18.21%E2%80%AFPM.mov)

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/256#-:-O1U_mbPEK7UyMXnhMfb:b-aepg2m)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

**Comment by Darth-Raazi** [comment]
See how much you can get done by Friday, then merge this

**Review by patrick-gu — APPROVED** [review]
Thank you for taking my task lol

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/256#-:-O1UulFR3l3icemV4d9K:b-grei6f)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Comment by zangjiucheng** [comment]
> Thank you for taking my task lol

Oh sorry 😢, I don't know that. But anyway we made it!

**Comment by zangjiucheng** [comment]
@Darth-Raazi Thanks for your suggestion! I tried the problem you mentioned again today and I found some way to fix it. Instead of using the `resize()` method, I'm using the `setGeometry()` method, which avoids the use of anchor positioning, but sets the position of the QWiget to make sure it works properly. If you have the time, could you check this again for me, please?

**Review by Darth-Raazi — APPROVED** [review]
Amazing job! This works perfectly
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/256#-:-O1du9kiCQGXk1rDlg0i:b76oj1k)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Pull request merged**
