### PR TITLE
Hardcode parsley fix

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
Note, I have not yet been able to test this because I don't have the setup needed to. Will probably do so tomorrow.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/265)

### CODE REVIEW

**Review by patrick-gu — APPROVED** [review]
I don't really see anything wrong with the code so if you test it and it does what you want then I think it's good

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/265#-:-O1ibj6909Fn14E3PbD0:becc01k)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @saads312)

___
*[`sources/parsley/main.py` line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/265#-O1ibeRz62jMyIcoO7AR:-O1ibeRz62jMyIcoO7AS:b-8h2wlc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/28d97e65ee690e75de044937f89080b119581b0b/sources/parsley/main.py#L40)):*
> ```Python
>         self.fake_msgs = [
>             {'board_id': 'ANY', 'msg_type': 'LEDS_ON'},
>             {'board_id': 'ANY', 'msg_type': 'LEDS_OFF'},
> ```

why are we getting rid of all the old fake messages?

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/265)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sources/parsley/main.py` line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/265#-O1ibeRz62jMyIcoO7AR:-O1tLb-T8esRqOHc9T9H:b-dd72hc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/28d97e65ee690e75de044937f89080b119581b0b/sources/parsley/main.py#L40)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

why are we getting rid of all the old fake messages?
</blockquote></details>

Please add the fake messages back, we want more than just LEDS_ON/OFF for testing

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/265)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sources/parsley/main.py` line 40 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/265#-O1ibeRz62jMyIcoO7AR:-O2l4VN4CwWPGPa0e22I:bmbficc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/28d97e65ee690e75de044937f89080b119581b0b/sources/parsley/main.py#L40)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Please add the fake messages back, we want more than just LEDS_ON/OFF for testing
</blockquote></details>

The reason I removed them is because they weren't valid messages (caused everything to crash), so I removed it so I could test. I think we should find a better way to generate random CAN messages

**Comment by zangjiucheng** [comment]
This will be hold until we write the new fake message generator for Parsley.

**Comment by zangjiucheng** [comment]
Since new parsley will implement for CAN Bus 2.0B. We will reimplement parsley class implies to close for this PR.

**Pull request closed without merging**
