### PR TITLE
Fix Menu Bar on macOS

### PR DESCRIPTION
**Pull request by Darth-Raazi**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
This has conflicts, looks like you included the changes from #62 in this PR as well. You should be able to rebase the relevant commits onto the updated `dashboard` branch and force push to fix that.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63#-:-NFqbuk-24Bt4DlDfRKx:b775os9)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @KavinSatheeskumar)

**Comment by Darth-Raazi** [comment]
Oh shoot sorry. What does rebase mean and how do I do that? Also why did the changes from the other branch get added with this? Did I do something wrong while creating branch?

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Darth-Raazi)

___
*[`sinks/dashboard/requirements.txt` line 3 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63#-NFuc8rf1eeC8zK2D7sq:-NFuc8rf1eeC8zK2D7sr:bao9we5) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f42feb7fd8bda507454faafe37bc4a8dbe550798/sinks/dashboard/requirements.txt#L3)):*
> ```help
> numpy
> PySide6
> pyqtgraph
> ```

please add this back in (sorry I broke it >.<)
___
*[`sinks/dashboard/items/dashboard_item.py` line 23 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63#-NFuc5gf0vxEdw1kOz4k:-NFuc5gf0vxEdw1kOz4l:b-97qmvv) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/f42feb7fd8bda507454faafe37bc4a8dbe550798/sinks/dashboard/items/dashboard_item.py#L23)):*
> ```Python
>         Return a nicer name for the Dash Item instead of the class name
>         '''
>         #raise NotImplementedError
> ```

fix this pls

**Review by KavinSatheeskumar — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63#-:-NFudQhe5kfTgGty6rYZ:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @Darth-Raazi)

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63)* status: all files reviewed, 1 unresolved discussion (waiting on @Darth-Raazi)

___
*[`sinks/dashboard/items/plot_dash_item.py` line 86 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63#-NFv1BzUDED75bvMf7Hd:-NFv1BzUDED75bvMf7He:b9j537n) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ad117b861b848887fb36f456239442893411590d/sinks/dashboard/items/plot_dash_item.py#L86)):*
> ```Python
> 
>     def get_props(self):
>         return self.props\
> ```

Random `\` made its way in here.

**Review by BluCodeGH — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Darth-Raazi)

**Pull request merged**
