### PR TITLE
Merge fake parsley into main parsley source

### LINKED ISSUE #184: Merge Parsley and Fake Parsley
Currently we have the actual `parsley` source for interfacing Omnibus with our CAN bus and we have `fake_parsley` to generate and send mock Parsley data. `parsley` can't be run without a physical connection to a board (it reads from a port on your computer) and `fake_parsley` doesn't have some of the features/message formats that `parsley` does. We want to update `parsley` so that when a `--fake` flag is used, it won't read from a port, but rather send the data that `fake_parsley` uses, allowing features like CAN Sender and Parsley Instance Selector to be easily testable

### PR DESCRIPTION
**Pull request by SuperZooper3**
## Description
The standalone fake-parsley source was falling out of date with the real parsley's features (ex: heartbeat messages), and it wasn't possible to test the parsley source without a debug board connected. So I've implemented a fake serial reader that emulates boards on the CAN bus sending messages about their status.

- Add FakeSerialCommunicator to simulate communication over the CAN bus, reading from a dict of pre-programmed messages and randomizing their data, encoding them in the same binary as real devices
- Add --fake flag to sources/parsley/main.py to enable fake mode, and some minor changes to make it easier to run (setting port to optional, but printing an error message if fake isn't on and a port isn't given)
- Delete old fake_parsley and add a README explaining to use the new fake mode
- Timestamps on fake messages wrap every 65 seconds to fit in 16 bits in milliseconds form

This PR closes #184.

## Developer Testing

Here's what I did to test my changes:

- Ran omnibus, and printer source, and then ran `sources/parsley/main.py --fake`, observed it printing to the parsley console that it was receiving messages, as well as seeing them being re-broadcast to omnibus and being printed in the printer source
- Tested argument formatting and checking to ensure ports are still taken when needed
- [STILL TO DO WITH KAVIN LATER THIS WEEK] Compared behavior of old version of main.py with updated to ensure 100% consistency on non-fake case
- Ensured fake source could run stably for an hour with no crashes due to time overflows

## Reviewer Testing
Here's what you should do to quickly validate my changes:

- Run omnibus, and printer source, and then run `sources/parsley/main.py --fake`, observe it printing to the parsley console that it is receiving messages, as well as seeing them being re-broadcast to omnibus and being printed in the printer source

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work, I'm not the most familiar with Parsley but the messages look good to me. Some minor things, also please fix all your comments and run `./tools/format.sh`

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-:-Nohdkjp1fKaysnGbFdZ:b-2n6k2o)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @SuperZooper3)

___
*[`sources/parsley/main.py` line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-Nohb8_j-bYa_Ojeegut:-Nohb8_j-bYa_Ojeeguu:bdqzx3o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L33)):*
> ```Python
> 
> 
> class FakeSerialCommunicator:  # acting as a fake usb debug board
> ```

Please put comments above and capitalize the first word like so:
```
# Acting as a fake usb debug board
class FakeSerialCommunicator
```
___
*[`sources/parsley/main.py` line 104 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-NohbxFv-RsCHKY742Mc:-NohbxFv-RsCHKY742Md:b-e8l6qq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L104)):*
> ```Python
>         communicator = FakeSerialCommunicator()
> 
>     parser = parsley.parse_usb_debug
> ```

Why was this taken out of the `else` condition?
___
*[`sources/parsley/main.py` line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-NohcHVa9oFBSiKfpINy:-NohcHVa9oFBSiKfpINz:bu9884u) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L123)):*
> ```Python
>         print("Parsley started in fake mode")
>         sender = Sender()
>         receiver = None  # no instructions to echo in fake mode
> ```

We still want a receiver in fake mode to allow testing omnibus -> parsley messages

**Review by SuperZooper3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sources/parsley/main.py` line 33 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-Nohb8_j-bYa_Ojeegut:-NohfSIT3BWDlnVekt4f:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L33)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Please put comments above and capitalize the first word like so:
```
# Acting as a fake usb debug board
class FakeSerialCommunicator
```
</blockquote></details>

Done.
___
*[`sources/parsley/main.py` line 104 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-NohbxFv-RsCHKY742Mc:-NohfSuV3PH7yrzqsf8W:b-m112aw) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L104)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Why was this taken out of the `else` condition?
</blockquote></details>

I took it out to make it more clear that this was the default behavior, but no important r
___
*[`sources/parsley/main.py` line 123 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-NohcHVa9oFBSiKfpINy:-Nohg-d918n3JRYGXU_9:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L123)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

We still want a receiver in fake mode to allow testing omnibus -> parsley messages
</blockquote></details>

Done.

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
One small change and also please capitalize your comments

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-:-NorJn039wbcX1W0BojV:b-v9gjv9)* status: all files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @KavinSatheeskumar, and @SuperZooper3)

___
*[`sources/parsley/main.py` line 104 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-NohbxFv-RsCHKY742Mc:-NorJfsG-ujiEZNv20iM:b-k2bwm7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L104)):*
<details><summary><i>Previously, SuperZooper3 (SuperZooper3) wrote…</i></summary><blockquote>

I took it out to make it more clear that this was the default behavior, but no important r
</blockquote></details>

I think it's better to have it in the else statement

**Review by SuperZooper3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sources/parsley/main.py` line 104 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-NohbxFv-RsCHKY742Mc:-NorUoNB4lVRjN5Ad64R:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/425e3b6fdb209efff58db2dfc2feb9a7931fc0e5/sources/parsley/main.py#L104)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

I think it's better to have it in the else statement
</blockquote></details>

Done.

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/195#-:-NpBOdQQ9Crgl_DG1hgM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

**Pull request merged**
