### PR TITLE
startup script

### PR DESCRIPTION
**Pull request by addison-ch**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking good! Mostly small things, the argument handing might be a bit more work but I think it can fit in this PR if you're up for it.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-:-MpmwVqICWfjz0fv0OEX:b-86httv)* status: all files reviewed, 6 unresolved discussions (waiting on @addison-ch, @DevinLeamy, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[launcher.py, line 5 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-MpmuNX94PbDEfK3Cmy5:-MpmuNX94PbDEfK3Cmy6:bwac1id) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1f4d8deb9b07f869a16753ccdccb3c05778cf77d/launcher.py#L5)):*
> ```Python
> 
> 
> profiles = {  # Note: enter each command as a string enclosed with double quotations
> ```

Cleaner to add in the quotations where you actually use the string to call `Popen`.
___
*[launcher.py, line 9 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-Mpmul3cDzIi0TwSZphb:-Mpmul3cDzIi0TwSZphc:b-kbqtj7) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1f4d8deb9b07f869a16753ccdccb3c05778cf77d/launcher.py#L9)):*
> ```Python
>              '"python sinks/plot/main.py"',
>              '"python sources/fakeni/main.py"'],
>     "texas": ['"python sources/parsley/main.py"',
> ```

We should add the ability to pass arguments through to the child processes, for example parsley requires the port to read from.

We could do this by making a special string in the command such as `$arg`, and when we run the commands we replace occurrences of `$arg` with the next successive command line argument (ie to support multiple commands requiring arguments the user could type `launcher.py profile arg1 arg2` and arg1 would get forwarded to the first command that asks for an argument, arg2 to the second).
___
*[launcher.py, line 17 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-MpmvXO0EmOD8WYwfAVt:-MpmvXO0EmOD8WYwfAVu:b-urgz09) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1f4d8deb9b07f869a16753ccdccb3c05778cf77d/launcher.py#L17)):*
> ```Python
> 
> try:
>     if(sys.argv[1] == "_wrap"):
> ```

Unnecessary parenthesis.
___
*[launcher.py, line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-Mpmvb7n1x1Qgjj8tjCL:-Mpmvb7n1x1Qgjj8tjCM:b-qw7dml) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1f4d8deb9b07f869a16753ccdccb3c05778cf77d/launcher.py#L19)):*
> ```Python
>     if(sys.argv[1] == "_wrap"):
>         p = Popen(sys.argv[2])
>         p.wait()
> ```

`p.wait()` returns a number that tells us whether the command was successful or not. If the number is not zero there was an error and so we should wait, and otherwise should skip the `input()`.
___
*[launcher.py, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-MpmvnU11t9LwHFbWcIz:-MpmvnU11t9LwHFbWcJ-:br4btq1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1f4d8deb9b07f869a16753ccdccb3c05778cf77d/launcher.py#L20)):*
> ```Python
>         p = Popen(sys.argv[2])
>         p.wait()
>         print('...')
> ```

Not needed when we have the message in `input()`.
___
*[sinks/plot/config.py, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-Mpmu0Px9zvP6lzAc6vp:-Mpmu0PyEmW06VbWPE9H:btg16xn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1f4d8deb9b07f869a16753ccdccb3c05778cf77d/sinks/plot/config.py#L20)):*
> ```Python
>     DAQ_SENSORS = [
>         "Fake0", "Fake1", "Fake2", "Fake3", "Fake4", "Fake5", "Fake6", "Fake7"]
> ```

Please don't commit changes made for testing.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-:-Mpt19hl4XYB2ZMekCNW:b9bkkp1)* status: all files reviewed, 2 unresolved discussions (waiting on @addison-ch, @DevinLeamy, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[launcher.py, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-Mpt-X-J3CGE7VZjGFod:-Mpt-X-J3CGE7VZjGFoe:b2xgdti) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec1c668c2601895647960d8f25acf6fb50ed4fe5/launcher.py#L22)):*
> ```Python
>         p = Popen(sys.argv[2])
>         if p.wait() != 0:
>             close = input('Press enter to quit')
> ```

Unused variable `close`?
___
*[launcher.py, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-Mpt-lCJ0Ho-1B86N9nb:-Mpt-lCJ0Ho-1B86N9nc:bbcncr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec1c668c2601895647960d8f25acf6fb50ed4fe5/launcher.py#L31)):*
> ```Python
>         for process in processes:
>             if '$arg' in process:
>                 command = process.replace('$arg', args[0])
> ```

You can actually make this handle multiple arguments super easily. First, switch from the variable `command` to updating `process` instead (which also removes the need for an else). Then, you can use the 'count' flag of the replace method (https://docs.python.org/3/library/stdtypes.html#str.replace) to only replace the first occurrence of `$arg`. Lastly, change the if to a while!

**Review by addison-ch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @DevinLeamy, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[launcher.py, line 22 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-Mpt-X-J3CGE7VZjGFod:-Mq7Ckhh5LXiy-xwe-Tt:bvoh3ao) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec1c668c2601895647960d8f25acf6fb50ed4fe5/launcher.py#L22)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unused variable `close`?
</blockquote></details>

Removed the variable
___
*[launcher.py, line 31 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-Mpt-lCJ0Ho-1B86N9nb:-Mq7Ct0B03t_UGIn-cz1:b-896fja) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec1c668c2601895647960d8f25acf6fb50ed4fe5/launcher.py#L31)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

You can actually make this handle multiple arguments super easily. First, switch from the variable `command` to updating `process` instead (which also removes the need for an else). Then, you can use the 'count' flag of the replace method (https://docs.python.org/3/library/stdtypes.html#str.replace) to only replace the first occurrence of `$arg`. Lastly, change the if to a while!
</blockquote></details>

Done!

**Review by BluCodeGH — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/40#-:-MqBLu5404qrYnZcRt77:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DevinLeamy, @DhritiGabani, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Pull request merged**
