### PR TITLE
DashItem Cleanup

### LINKED ISSUE #202: Existing Dashitem Cleanup
Remove items that aren't used anymore (orientation plot, 3D position plot, table view, etc.). For the ones that are left, we want to increase font sizes and (especially for the plots) line width, making everything just a bit easier to see at a glance

### PR DESCRIPTION
**Pull request by Darth-Raazi**
## Description

- Removed unused dash items from the dashboard. Their files have not been deleted, so they can easily be added back, but they won't show up in the `Add Items` menu bar option
- Fixed a bug that was crashing the Dynamic Text item
- Small code restructure

Please let me know if I've removed any items that we want to keep

This PR closes #202

## Developer Testing

Here's what I did to test my changes:

- Ran dashboard and made sure correct items were showing up in the menu

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Run dashboard and make sure correct items show up in the menu

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/242)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
Because the files are no longer imported, they are effectively dead code, and I would prefer to just remove them to avoid confusion. There are two cases in my mind:
- We update some dashitem API, and those items are broken. Then we can't actually add them back.
- We update some dashitem API, and we make an effort to update those items. Then we have to test them by reregistering them again. But at that point we're literally maintaining a feature that doesn't exist.

If we still might want to use them, maybe we could put them under a deprecated items list?

I can confirm that the removal of these items are backwards compatible with old save files, just deleting them.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/242#-:-O05eYsyBBfdaeR0tEIB:btdp4xc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @BluCodeGH, @Lucifersan, and @saads312)

**Review by Darth-Raazi — COMMENTED** [review]
Hmm that's a good point. @BluCodeGH can you take a quick look at the removed dashitems and lmk if you're ok with deleting the files?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/242#-:-O0_j8i3Eb3nEoULdInt:blhqqh6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @BluCodeGH, @Lucifersan, and @saads312)

**Review by BluCodeGH — COMMENTED** [review]
I think we should keep dynamic text, it is still useful for text data (board statuses). 3D views and table item are fine to delete.

**Review by patrick-gu — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/242#-:-O0djEGh4XJ7Ez1Vbp3P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Pull request merged**
