### PR TITLE
PyQt Plot Implementation

### PR DESCRIPTION
**Pull request by PCModeActivate**
Currently capable of running smoothly with 8 plots all at once on my craptop.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9)

### CODE REVIEW

**Review by wendi-yu — COMMENTED** [review]
Quick review from me, probably don't take it as the final word because I didn't go super in detail. I'm not sure to what extent this is meant as prototype code but maybe just format the demo code (that populates with fake data sources, etc) behind a single variable so it's easier to change if/when we need to? And the git stuff is looking weird lol if it's too much to actually fix you can try git cherry-picking the commits you actually need into a new branch. I generally try to rebase and never merge to update my history, which seems to generally avoid problems like this ;)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-:-McbJHW595AV1TjEeOdc:b-zfkwto)* status: 0 of 10 files reviewed, 7 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @PCModeActivate)

___
*[requirements.txt, line 3 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbGEAZ-CuodDFwvIqo:-McbGEAZ-CuodDFwvIqp:beoboll) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/requirements.txt#L3)):*
> ```help
> autopep8==1.5.7
> msgpack==0.5.6
> pyzmq==22.1.0
> ```

lol nitpick but I think it's good formatting to have these in alphabetical order?
___
*[omnibus/omnibus.py, line 23 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbGdLnAFlRX92b_yq4:-McbGdLnAFlRX92b_yq5:b92a39i) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/omnibus/omnibus.py#L23)):*
> ```Python
> class OmnibusCommunicator:
>     """
>     Handles state shared between senders and receivers.
> ```

Is this from an earlier version of #6? weird
___
*[sinks/plot/main.py, line 17 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbHQcm6Z2hEGXfACuh:-McbHQcm6Z2hEGXfACui:buq4nid) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L17)):*
> ```Python
> # Sensor names; make sure this matches the names at the source!
> SENSORS = []
> for i in range(SENSOR_COUNT):
> ```

Is this meant as like demo code? maybe hide the demo stuff under a boolean called demo (if demo populate w fake names) and then when it comes to deploy real stuff turning off te demo is only changing one variable
___
*[sinks/plot/main.py, line 35 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbI-2A39LiLguneHHB:-McbI-2A39LiLguneHHC:b-eltr0g) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L35)):*
> ```Python
> 
> min_col = int(np.ceil(np.sqrt(SENSOR_COUNT)))
> min_row = int(np.ceil(SENSOR_COUNT / min_col))
> ```

fwiw I think  / does integer division in python so you should be able to just do +1 for the ceil and don't need to cast
___
*[sinks/plot/main.py, line 40 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbI_i3-ZeoHHKKVUpD:-McbI_i3-ZeoHHKKVUpE:bw9q6ab) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L40)):*
> ```Python
>         plots.append(win.addPlot(title=("Sensor: " + SENSORS[j])))
>     if(i != min_row - 1):
>         win.nextRow()
> ```

I feel like you might be able to iterate through the rows of `win` directly? and grab the `i` value from an `enumerate`? Up to you if you wanna look into it but might make this for loop a bit cleaner and more pythonic
___
*[sinks/plot/main.py, line 45 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbIxVI5XrCLe3UGkG-:-McbIxVI5XrCLe3UGkG0:b-dg6htr) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L45)):*
> ```Python
> curves = [plots[i].plot(pen='y') for i in range(SENSOR_COUNT)]
> 
> data_streams = [[0 for _ in range(100)] for _ in range(SENSOR_COUNT)]  # 100 data points
> ```

hardcoded or should we pull out into config variable?
___
*[sinks/plot/main.py, line 53 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbJ96m54rchVwQuSCF:-McbJ96m54rchVwQuSCG:b-i9xy9q) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L53)):*
> ```Python
>             data_streams[i].pop(0)
>             # Update Data Stream, currently only grabbing the first element in the payload obj
>             data_streams[i].append(new_data["data"][sensor][0])
> ```

Just a question but is a record of how the payload object is formatted recorded anywhere?

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @wendi-yu)

___
*[sinks/plot/main.py, line 40 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbI_i3-ZeoHHKKVUpD:-McvmAOL2ohHqRAF3lEw:b25z8vi) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L40)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

I feel like you might be able to iterate through the rows of `win` directly? and grab the `i` value from an `enumerate`? Up to you if you wanna look into it but might make this for loop a bit cleaner and more pythonic
</blockquote></details>

I'm testing out another method for the layout that does not involve `nextRow`, but since this version works as is, I think we can keep it as is for this PR.
___
*[sinks/plot/main.py, line 53 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbJ96m54rchVwQuSCF:-McvsqbA9wKByD5R7338:b-epllba) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L53)):*
<details><summary><i>Previously, wendi-yu (Wendi Yu) wrote…</i></summary><blockquote>

Just a question but is a record of how the payload object is formatted recorded anywhere?
</blockquote></details>

Well I believe that is how it works, but I should probably ask Jack to confirm it

**Review by PCModeActivate — COMMENTED** [review]
This PR is now abandoned because of the git mess. Please see the PR from plot-new branch.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-:-McwBYgn9CaEbdGhXpYu:b-fkjmxt)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @BluCodeGH, @Huan-YiShen, @jacobdeery, @jli35, @KavinSatheeskumar, and @wendi-yu)

___
*[sinks/plot/main.py, line 40 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/9#-McbI_i3-ZeoHHKKVUpD:-McwBTgp6YDSX2Ys6ghw:b-rb19qc) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/fd02e1af13b2dc07c58da4ef2faf235e2ccc7c1d/sinks/plot/main.py#L40)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

I'm testing out another method for the layout that does not involve `nextRow`, but since this version works as is, I think we can keep it as is for this PR.
</blockquote></details>

Actually I updated this in the new branch in the new PR.

**Comment by PCModeActivate** [comment]
Migrated to PR #11 to avoid the messy git stuff.

**Pull request closed without merging**
