### PR TITLE
Dashboard gauge item

### LINKED ISSUE #198: Gauge Item
For data coming from sensors such as a pressure transducer, we want a gauge item to easily see the value. It should be similar to a YAMCS gauge (see image below) with a needle going from one end to the other as the value increases, a numerical readout of the value below the gauge and a text label for the name of the sensor below that. This should all be one unit (move together, not be separable, etc.)

Image

### PR DESCRIPTION
**Pull request by patrick-gu**
## Description

This implements a simple gauge using PyQt. Custom QPainter code is used to render the gauge. The value, ticks, and bounds on the gauge are configurable. Data is fetched similar to in the plot item.

This PR closes #198.

## Developer Testing

Here's what I did to test my changes:

- Ran dashboard and added a gauge item
  - `python -m omnibus`, `python ./sources/parsley/main.py --fake`, ` python ./sinks/dashboard/main.py`
- Tested with the series `ACTUATOR_INJ/SENSOR_ANALOG/SENSOR_BATTERY_VOLT/value`
- Compared with a plot of the same data to ensure it makes sense
- Changed the configuration to make sure it produces a reasonable result in each case
  - Including changing the width and height
- Not sure if there is a way to do automated testing

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Run the dashboard and add a gauge, check visually that it works

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215)

### CODE REVIEW

**Comment by patrick-gu** [comment]
This is what I have so far:

image

**Comment by patrick-gu** [comment]
image
What it looks like now

**Comment by patrick-gu** [comment]
image
Update

**Comment by patrick-gu** [comment]
Larger text
image

**Comment by patrick-gu** [comment]
Label updates
image

**Comment by patrick-gu** [comment]
image
Size comparison

**Review by Darth-Raazi — COMMENTED** [review]
Haven't reviewed the code yet, but I'm not seeing the same thing as you. Here's what I see after resizing: 



Not sure what's going on but maybe you can take a look?

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-:-NwWoXxo26ZzGXknPiFr:b-jqklky)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

**Comment by patrick-gu** [comment]
image
I hate to say it, but works on my machine. I am using fakeni with seemingly the same settings. Are you seeing any logs in the console? Also, can you just check that you are on the latest commit, since I think I disabled rendering in certain cases in previous commits?

**Comment by patrick-gu** [comment]
I just realized I think the problem is with the stroke colour - since you are on dark mode, it is drawing everything in white. I will update it to draw in black, but I don't know how to actually use dark mode to test it - my system settings don't seem to affect it

**Review by Darth-Raazi — COMMENTED** [review]
That fixed it!



Couple things:
- I think the text label should be a bit bigger
- Same with the tick numbers
- The big numeric readout should be rounded to about 6 digits total so the actual value can be seen and not 30 decimals flying by lol
- The default also seems a bit too small, maybe 250x250 or 300x300?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-:-Nwaiqbs8uzGj15AQCT1:bhwobtn)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

**Comment by patrick-gu** [comment]
- The text was designed to be readable at 150x150, as Jack suggested. I'll try to make the text scale dynamically with the size of the circle.
- Will round the number if it is a float and not an int (which I was working with before), plus make the box bigger
- I think Jack thought 400x400 was way too big so I'll take 250x250 as a medium default

**Comment by patrick-gu** [comment]
image
Now at 250x250

**Comment by patrick-gu** [comment]
@BluCodeGH or @KavinSatheeskumar if you have time, would appreciate a review since you're the code owners

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Nice! Can we move the label down a bit for better spacing? 

Also, I think I crashed it by entering a decimal max value, can support for that be added?

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-:-NxfG3hz6bu8nG9vGyQF:b-pfq6po)* status: all files reviewed, 6 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sinks/dashboard/items/gauge_item.py` line 35 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfGRNn7usvjsimCTXg:-NxfGRNn7usvjsimCTXh:btq9n9e) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L35)):*
> ```Python
> 
>         self.min_value: int = 0
>         self.max_value: int = 10
> ```

Decimal support please! E.g. if the data is only between 0 and 0.5
___
*[`sinks/dashboard/items/gauge_item.py` line 68 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfGrqB2jjex3zRW8RU:-NxfGrqC9oWR5AXiBXjk:b-kf3hfe) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L68)):*
> ```Python
>         self.widget.update()
> 
>     def on_label_change(self, param, value):
> ```

Would it be easier to have all these `..._change` methods just be one thing that grab the new value for every field?
___
*[`sinks/dashboard/items/gauge_item.py` line 85 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfH78e5W0Brxq5hl1G:-NxfH78e5W0Brxq5hl1H:b-j2u3eb) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L85)):*
> ```Python
>         width = self.width()
>         height = self.height()
>         if width < 100 or height < 100:
> ```

Why these restrictions on the size?
___
*[`sinks/dashboard/items/gauge_item.py` line 96 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHBLq4B4Fw_-q6JfY:-NxfHBLq4B4Fw_-q6JfZ:buqs6jx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L96)):*
> ```Python
> 
>             # Tick marks and text
> ```

Extra blank line not needed
___
*[`sinks/dashboard/items/gauge_item.py` line 111 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHMRgD-EzvhezJQGM:-NxfHMRgD-EzvhezJQGN:b-icxlr4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L111)):*
> ```Python
> 
>             # Invalid conditions
>             if max_value < min_value:
> ```

This check should be in the `..._change` method and it should reject the invalid value (replace it with whatever the previous value was)
___
*[`sinks/dashboard/items/gauge_item.py` line 189 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHagr-zy_TylPOqmP:-NxfHagr-zy_TylPOqmQ:bnsapnf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L189)):*
> ```Python
>             painter.setFont(font)
>             painter.drawText(0, height - side / 8, width, side / 8, Qt.AlignmentFlag.AlignHCenter | Qt.AlignmentFlag.AlignTop, label)
>             
> ```

Newline please

**Review by patrick-gu — COMMENTED** [review]
For the label, I believe there's some padding around the box which will cut off text if it's too low, especially if you have something like a "y". So having more space would come at the cost of making the circle smaller.

Decimal support has been added.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-:-NxhsxGnBkWog_fjK7ko:b-j8y7jw)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/gauge_item.py` line 35 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfGRNn7usvjsimCTXg:-Nxhh1nP0EM_cdbFPD57:b79k32k) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L35)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Decimal support please! E.g. if the data is only between 0 and 0.5
</blockquote></details>

Added. It was only integers before because floating point error is weird, but it should work OK now.
___
*[`sinks/dashboard/items/gauge_item.py` line 68 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfGrqB2jjex3zRW8RU:-Nxhtj3471iFQtip6xxv:b-cpwspn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L68)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Would it be easier to have all these `..._change` methods just be one thing that grab the new value for every field?
</blockquote></details>

This is what is done in `plot_dash_item.py`. Don't want to have too much abstraction
___
*[`sinks/dashboard/items/gauge_item.py` line 85 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfH78e5W0Brxq5hl1G:-NxhcO3j3HbLNJBFmPle:b9qjggk) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L85)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Why these restrictions on the size?
</blockquote></details>

The thickness of the lines and needle don't scale with the size, which makes it look really goofy when you make it small. I could make them also dynamically scale like the text, which I think would allow it to scale arbitrarily and look the same at any size. If this is important, I can change it. Just didn't account for too many cases to begin with because I was thinking about our typical use cases.
___
*[`sinks/dashboard/items/gauge_item.py` line 96 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHBLq4B4Fw_-q6JfY:-NxhbyDB10NXhiuHa1d_:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L96)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Extra blank line not needed
</blockquote></details>

Done.
___
*[`sinks/dashboard/items/gauge_item.py` line 111 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHMRgD-EzvhezJQGM:-Nxhtxu9C8G4DJTvp5wu:br7a3aj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L111)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

This check should be in the `..._change` method and it should reject the invalid value (replace it with whatever the previous value was)
</blockquote></details>

I'm not sure how I could go about doing this. `pyqtgraph` does have `setLimits` but I can't find any documentation on where this is applicable to a simple parameter, if at all.

https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/parameter.html#pyqtgraph.parametertree.Parameter.setLimits
https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/parametertypes.html#pyqtgraph.parametertree.parameterTypes.SimpleParameter
___
*[`sinks/dashboard/items/gauge_item.py` line 189 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHagr-zy_TylPOqmP:-NxhbbfU8V96eO1LPpMq:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L189)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Newline please
</blockquote></details>

Done.

**Comment by patrick-gu** [comment]
I had to do a bit of rounding because numbers like 0.1 cannot be represented exactly in floats. I round them and convert to Python's exact decimals before working with them

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Decimals are working great. For the label, can we make the widget not square then? Default size could be 200x250 or 250x300. 
Also, deleting the widget causes this error:


> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-:-Nxi-uGtCb_ppnQMb2ty:baco0fc)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @KavinSatheeskumar, and @patrick-gu)

___
*[`sinks/dashboard/items/gauge_item.py` line 68 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfGrqB2jjex3zRW8RU:-Nxi-Co22LpvluuTxoe_:b-8w8bup) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L68)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

This is what is done in `plot_dash_item.py`. Don't want to have too much abstraction
</blockquote></details>

Ah makes sense
___
*[`sinks/dashboard/items/gauge_item.py` line 85 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfH78e5W0Brxq5hl1G:-Nxi-IG_-ubOGIHC3fof:b-5fjil4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L85)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

The thickness of the lines and needle don't scale with the size, which makes it look really goofy when you make it small. I could make them also dynamically scale like the text, which I think would allow it to scale arbitrarily and look the same at any size. If this is important, I can change it. Just didn't account for too many cases to begin with because I was thinking about our typical use cases.
</blockquote></details>

This is fine for now, but let's create an issue to address this in the future
___
*[`sinks/dashboard/items/gauge_item.py` line 111 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHMRgD-EzvhezJQGM:-Nxi-XG_AiyhlqIxQ66n:b-77rh8) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L111)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

I'm not sure how I could go about doing this. `pyqtgraph` does have `setLimits` but I can't find any documentation on where this is applicable to a simple parameter, if at all.

https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/parameter.html#pyqtgraph.parametertree.Parameter.setLimits
https://pyqtgraph.readthedocs.io/en/latest/api_reference/parametertree/parametertypes.html#pyqtgraph.parametertree.parameterTypes.SimpleParameter
</blockquote></details>

What about just checking `self.max_value < self.min_value` in the change method and not updating the widget if that's true? Could also save the previous value and then restore it

**Review by patrick-gu — COMMENTED** [review]
Updated default size and fixed the error (good catch, I didn't even notice it)

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-:-NxzYv88AOOu0G4Ooo7G:b-jm6cpb)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, and @KavinSatheeskumar)

___
*[`sinks/dashboard/items/gauge_item.py` line 68 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfGrqB2jjex3zRW8RU:-NxzZIEH6MVUbMEmie79:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L68)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

Ah makes sense
</blockquote></details>

Done.
___
*[`sinks/dashboard/items/gauge_item.py` line 85 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfH78e5W0Brxq5hl1G:-NxzZ1_r0rTXMtsh_b7e:b-zegp6m) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L85)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

This is fine for now, but let's create an issue to address this in the future
</blockquote></details>

Done, see #218 
___
*[`sinks/dashboard/items/gauge_item.py` line 111 at r8](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-NxfHMRgD-EzvhezJQGM:-NxzZ4oEAu86Ion9Np2_:b8bro6b) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/369445716e6b9d6f993e3ab086bdbb7897a397ba/sinks/dashboard/items/gauge_item.py#L111)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

What about just checking `self.max_value < self.min_value` in the change method and not updating the widget if that's true? Could also save the previous value and then restore it
</blockquote></details>

Done. It now goes back to whatever value it was before. Implementation was indeed quite straightforward.

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

Great work!

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/215#-:-NyCZiTG4z9OU-ps95EM:bd3g9jg)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

**Pull request merged**
