### PR TITLE
Add USB debug as source

### PR DESCRIPTION
**Pull request by BenLevy7**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks great! You should probably give the auto format script a run though (`tools/format.sh`).

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-McLxPCZ-P6T46t7H0_Z:bftb2cr)* status: all files reviewed, 2 unresolved discussions (waiting on @BenLevy7, @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sources/parsley/main.py, line 282 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-McLxJMw-tLmR_FvxGx0:-McLxJMw-tLmR_FvxGx1:bdo1zq9) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ba6486be9a7ea0e9f35545dfeb0795374a5bcfdc/sources/parsley/main.py#L282)):*
> ```Python
>         output = output + '{:<20}'.format(data)
>     
>     sender.send(output)
> ```

It wouldn't hurt to still print the output too.
___
*[sources/parsley/main.py, line 291 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-McLx-zA6pEw6xUqknwi:-McLx-zA6pEw6xUqknwj:b-bju5o3) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ba6486be9a7ea0e9f35545dfeb0795374a5bcfdc/sources/parsley/main.py#L291)):*
> ```Python
>     args = parser.parse_args()
>     disp = serial.Serial('COM5',9600)
>     sender = Sender("CAN/Parsley")
> ```

Since `sender` is used by `parse_line` it should be declared outside of the if statement, generally the top of the file makes sense for global stuff like this.

**Review by jacobdeery — CHANGES_REQUESTED** [review]
It looks like a significant portion of this code was copied from `cansw_usb`. This will require proper attribution and licensing. Since `cansw_usb` is GPL, everything with a dependency on this code needs to be GPL as well. At a minimum, you will need to add a `LICENSE` file to `sources/parsley` and correctly attribute the copied code. Since this is a standalone executable and the rest of omnibus doesn't have any dependencies on it, the rest of the code can be kept as MIT if you want, but you'll want to clarify this in the README. @blucodegh @wendi-yu it's up to you guys if you want to deal with split licensing or just license the whole thing as GPL to save the trouble.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-McLyMc-C_jOKZobwcil:b-wjz4us)* status: all files reviewed, 3 unresolved discussions (waiting on @BenLevy7, @BluCodeGH, @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sources/parsley/main.py, line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-McLz37_5BolMDVjJKhU:-McLz37_5BolMDVjJKhV:b-j0bdv0) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ba6486be9a7ea0e9f35545dfeb0795374a5bcfdc/sources/parsley/main.py#L11)):*
> ```Python
> 
> 
> def parse_gen_cmd(msg_data):
> ```

All of the functions in this file could benefit from unit tests. I would suggest moving them to a separate file (maybe `parsley.py`) and separating them from the omnibus-specific logic.
___
*[sources/parsley/main.py, line 291 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-McLx-zA6pEw6xUqknwi:-McLzEojDj4d1ui3J1WP:b-956b0o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ba6486be9a7ea0e9f35545dfeb0795374a5bcfdc/sources/parsley/main.py#L291)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Since `sender` is used by `parse_line` it should be declared outside of the if statement, generally the top of the file makes sense for global stuff like this.
</blockquote></details>

An alternative approach: change `parse_line` so that it returns the output rather than sending it over the bus. That way, all of the parsing stuff has no dependencies on omnibus and can be moved into a separate file for unit testing.

**Review by jacobdeery — COMMENTED** [review]
Just to be clear - there's nothing wrong with copying the code, it would be silly to just rewrite everything from scratch for no reason. We just need to make sure we do the licensing correctly.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-McM-ROX5M_zOMzAelpA:b-kztbl3)* status: all files reviewed, 3 unresolved discussions (waiting on @BenLevy7, @BluCodeGH, @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Review by BluCodeGH — COMMENTED** [review]
Yeah I think a separate `LICENSE` file makes sense here, I'm not particularly against relicensing the rest of the code but I don't think there's much reason to here.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-McM-zeWAKK4ZtXEB8LL:b-tgbvar)* status: all files reviewed, 3 unresolved discussions (waiting on @BenLevy7, @BluCodeGH, @jacobdeery, @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sources/parsley/main.py, line 11 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-McLz37_5BolMDVjJKhU:-McM0gQj18v4J1i_uGux:bneunjz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ba6486be9a7ea0e9f35545dfeb0795374a5bcfdc/sources/parsley/main.py#L11)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

All of the functions in this file could benefit from unit tests. I would suggest moving them to a separate file (maybe `parsley.py`) and separating them from the omnibus-specific logic.
</blockquote></details>

Note that you don't necessarily need to implement the unit tests, this would just make them easier to implement in the future. You're welcome to implement them too but we haven't started on adding them to the rest of the codebase either.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Why was remote arming support removed from `message_types.py`? We still have all the functions to support it in `main.py` and I don't see a reason not to?

> Reviewed 1 of 2 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-MeIQADwBOUGtNj0oVAr:b-60gg0c)* status: all files reviewed, 3 unresolved discussions (waiting on @BenLevy7, @jacobdeery, @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Review by BenLevy7 — COMMENTED** [review]
> Dismissed @jacobdeery from a discussion.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10)* status: all files reviewed, 1 unresolved discussion (waiting on @BenLevy7, @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Review by BenLevy7 — COMMENTED** [review]
not sure, I didn't remove the remote arming support. Should I re-add it from parsley?

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-MeWt-5s9fl_BEIskxIE:b-r1u25t)* status: all files reviewed, 1 unresolved discussion (waiting on @BenLevy7, @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Huh weird, yeah you should be fine to go ahead and re-add it.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-MeWtdP33W25kLLYZuQX:bk3nvpg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Review by BluCodeGH — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Review by jacobdeery — APPROVED** [review]
I'm approving this now so that we have it in for static fire, but I would still like to see my comments addressed later; please open a GitHub issue/Clickup task for the necessary changes.

Please also run the `format.sh` script before merging to clean up whitespace/formatting issues.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/10#-:-Me_iGX2DryxBF6qFGQg:bax29l2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @James020118, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

**Pull request merged**
