### PR TITLE
add missing message types

### PR DESCRIPTION
**Pull request by MrPicklePinosaur**
add support in parsley for all message types defined in [message_types.h](https://github.com/waterloo-rocketry/canlib/blob/master/message_types.h)

specifically, these message types were added:
- RESET_CMD
- DEBUG_RADIO_CMD
- SENSOR_GYRO
- SENSOR_MAG
- RADI_VALUE
- LEDS_ON
- LEDS_OFF

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looking good!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-:-N2Nz4ZEApFsxeki8_-S:br2sbr6)* status: all files reviewed, 4 unresolved discussions (waiting on @MrPicklePinosaur and @PCModeActivate)

___
*[`sources/parsley/parsley.py` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2NwBrCCHp2V7MNJY5c:-N2NwBrCCHp2V7MNJY5d:b6zvsyf) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley.py#L53)):*
> ```Python
> def parse_reset_cmd(msg_data):
>     timestamp = _parse_timestamp(msg_data[:3])
>     board_id = msg_data[3]
> ```

We have `board_id_str` in `message_types.py` to map this to a human-readable value. Also note that if this is 0 all boards are reset so we should add a case for that.
___
*[`sources/parsley/parsley.py` line 149 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2Nvq0FCKJs9yjXyonT:-N2Nvq0G5MhFq7UgN0cd:bmrs864) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2e29d4e31542010e11801ea68d088e24348a000d/sources/parsley/parsley.py#L149)):*
> ```Python
> 
> @register("SENSOR_TEMP")
> def parse_sensor_temp(msg_data):
> ```

I realized we should actually keep this around. https://github.com/waterloo-rocketry/canlib/pull/36 is still an open PR.
___
*[`sources/parsley/parsley_test.py` line 212 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2Nyb0k9yTD1b6SBpkG:-N2Nyb0k9yTD1b6SBpkH:bjtstbt) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley_test.py#L212)):*
> ```Python
> 
>     def test_sensor_acc(self):
>         # TODO signed? unsigned?
> ```

Data here is signed (see `signed=True` in the parse function), we should test that.
___
*[`sources/parsley/parsley_test.py` line 221 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2Nyrho0ZGoUHYyZ2pq:-N2Nyrho0ZGoUHYyZ2pr:bvi7tid) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley_test.py#L221)):*
> ```Python
> 
>     def test_sensor_gyro(self, timestamp):
>         pass
> ```

Please add a comment saying why these two tests are just `pass`. Likewise for the led tests.

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55)* status: all files reviewed, 7 unresolved discussions (waiting on @MrPicklePinosaur and @PCModeActivate)

___
*[`sources/parsley/parsley.py` line 155 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2OeWCO138vRVbuFBhH:-N2PBFyhCwtVKRJJ3DFJ:b-jrv3hx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley.py#L155)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Unrelated to the PR but what is this gyro for? I can't but ask when gyro is mentioned lol
Also, not sure what the mag is but it looks like an imu; do we want to return accelerometer data too?
</blockquote></details>

SENSOR_ACC is the accelerometer. All 3 of these message types are from the sensors on mini sensor.
___
*[`sources/parsley/parsley.py` line 246 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2OeyLj8rEGGWcPhlML:-N2PBTOC8QAvaY5uTSph:b-kqys7e) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley.py#L246)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Maybe return a status string here?
</blockquote></details>

The message type itself is already handled and shown elsewhere, no need to imply there is data coming from somewhere there isn't any.

**Review by MrPicklePinosaur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @BluCodeGH and @PCModeActivate)

___
*[`sources/parsley/parsley.py` line 53 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2NwBrCCHp2V7MNJY5c:-N2UIhm47QPOrf7ldRZu:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley.py#L53)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

We have `board_id_str` in `message_types.py` to map this to a human-readable value. Also note that if this is 0 all boards are reset so we should add a case for that.
</blockquote></details>

Done.
___
*[`sources/parsley/parsley.py` line 149 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2Nvq0FCKJs9yjXyonT:-N2UIlMvD7QaaRg_T48C:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2e29d4e31542010e11801ea68d088e24348a000d/sources/parsley/parsley.py#L149)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I realized we should actually keep this around. https://github.com/waterloo-rocketry/canlib/pull/36 is still an open PR.
</blockquote></details>

Done.
___
*[`sources/parsley/parsley.py` line 155 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2OeWCO138vRVbuFBhH:-N2UIsOdA_1_DrRLXGjc:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley.py#L155)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

SENSOR_ACC is the accelerometer. All 3 of these message types are from the sensors on mini sensor.
</blockquote></details>

Done.
___
*[`sources/parsley/parsley.py` line 246 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2OeyLj8rEGGWcPhlML:-N2UIrrN1M_v4AfLQW48:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley.py#L246)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

The message type itself is already handled and shown elsewhere, no need to imply there is data coming from somewhere there isn't any.
</blockquote></details>

Done.
___
*[`sources/parsley/parsley_test.py` line 135 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2OduHy42J1mWyFWGc2:-N2UItH58DV8NTVtSR8L:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2e29d4e31542010e11801ea68d088e24348a000d/sources/parsley/parsley_test.py#L135)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Keep this around if we are keeping the temperature sensor
</blockquote></details>

Done.
___
*[`sources/parsley/parsley_test.py` line 212 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55#-N2Nyb0k9yTD1b6SBpkG:-N2UIu9z1S7oEC5qPbZm:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/423015f376b347bba12cae8f469bf73fe7b091d7/sources/parsley/parsley_test.py#L212)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Data here is signed (see `signed=True` in the parse function), we should test that.
</blockquote></details>

Done.

**Review by BluCodeGH — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/55)* status: all files reviewed, 3 unresolved discussions (waiting on @PCModeActivate)

**Review by PCModeActivate — APPROVED** [review]

**Pull request merged**
