### PR TITLE
Add dynamic_text background colour change

### PR DESCRIPTION
**Pull request by fayzull0h**
Updated dynamic_text.py to have functionality that sets conditions for the data. Based on the conditions, the background colour will change.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks good, just a couple nits and merge conflicts to fix.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113#-:-NXBaYwD0ojC_E8rqGwX:bqbx2mv)* status: all files reviewed, 3 unresolved discussions (waiting on @fayzull0h)

___
*[`sinks/dashboard/items/dynamic_text.py` line 19 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113#-NXB_rqtA5PM7jpyGzt8:-NXB_rqtA5PM7jpyGzt9:b2rldfl) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d21a06f5e8758b03223fc200209650c7d16c1a17/sinks/dashboard/items/dynamic_text.py#L19)):*
> ```Python
>         
>         self.condition_count = 0
>         self.default_color = '#008000'
> ```

Default background color should be a light grey like it currently is.
___
*[`sinks/dashboard/items/dynamic_text.py` line 73 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113#-NXB_JPQ5GnsxfDekHEl:-NXB_JPQ5GnsxfDekHEm:b-dux3at) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d21a06f5e8758b03223fc200209650c7d16c1a17/sinks/dashboard/items/dynamic_text.py#L73)):*
> ```Python
>         # If there are conditions, change colour based on them
>         #   else, set background to the default color
>         if self.condition_count > 0:
> ```

You can get rid of this if statement with `for/else`: https://book.pythontips.com/en/latest/for_-_else.html
___
*[`sinks/dashboard/items/dynamic_text.py` line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113#-NXBa2dd7LeWbyN6B6x7:-NXBa2dd7LeWbyN6B6x8:bvtqhpb) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d21a06f5e8758b03223fc200209650c7d16c1a17/sinks/dashboard/items/dynamic_text.py#L78)):*
> ```Python
>                 if self.condition_true(condition_reference):
>                     background_color = condition_reference.childs[2].value().name()
>                     self.setStyleSheet('background: ' + background_color)
> ```

Does this interfere with the timeout logic that sets the stylesheet to control the text color? Or will it just go back to the default background color on timeout?

**Review by itslinotlie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113)* status: all files reviewed, 4 unresolved discussions (waiting on @fayzull0h)

___
*[`sinks/dashboard/items/dynamic_text.py` line 3 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113#-NXGUAyK5KXDV23_VAvk:-NXGUAyK5KXDV23_VAvl:b-w6zybj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/d21a06f5e8758b03223fc200209650c7d16c1a17/sinks/dashboard/items/dynamic_text.py#L3)):*
> ```Python
> from pyqtgraph.Qt.QtWidgets import QHBoxLayout, QLabel
> from pyqtgraph.Qt.QtCore import QTimer
> import pyqtgraph.Qt.QtCore as qtcore
> ```

For the sake of consistency, the standard that's been used throughout the repo has been
```
from pyqtgraph.Qt.QtCore import Qt
...
self.setAttribute(Qt.WidgetAttribute.WA_StyledBackground, True)
```

**Comment by fayzull0h** [comment]
> Does this interfere with the timeout logic that sets the stylesheet to control the text color? Or will it just go back to the default background color on timeout?

I've fixed all the other issues you mentioned. However, I'm not sure what you mean by this one. Could we go over it in more detail on a call or on Slack?

**Review by KavinSatheeskumar — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @BluCodeGH and @fayzull0h)

___
*[`sinks/dashboard/items/dynamic_text.py` line 87 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/113#-NXld2Ep4OBe0XjZ4eO7:-NXld2Eq0yVCZz0QkM0F:bdor1h4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2a7bb29378bd33c990b573ef83300e756f9983ca/sinks/dashboard/items/dynamic_text.py#L87)):*
> ```Python
>         comparison = condition.childs[0].value()
>         condition_value = condition.childs[1].value()
>         data = float(self.widget.text())
> ```

If the text is a CAN message or something, this causes a stream of errors.

However, all of these comparisons work on strings, so just don't case to float :+1:

The only one that really matters for strings is ==, which works the way it should for strings so I say just not casting is the best solution.

**Pull request merged**
