### PR TITLE
improve save load from file, closes #206

### LINKED ISSUE #206: Improve Save/Load from File
Currently, there are 3 options relating to this (save, load and open) as 3 separate menubar items. Instead, we should have one `File` menubar item with the actions `Save`, `Save As`, and `Open`. `Save` should save with the default filename, `Save As` should prompt for a name and `Open` should prompt for a file upload. There should also be a  folder where all the savefiles are stored rather than just being in the root directory

### PR DESCRIPTION
**Pull request by BigLiban**
## Description
Replaced the Save, Open and Load tabs with a single file tab containing Save, Save As, and Open. In addition, all saves now go into a directory called saved-files, rather than the root directory.

Save defaults to saving to a savefile.json. Save As gives a prompt box where the user types in a custom file name. Open allows the user to open a saved configuration.

This PR closes #206.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219)

### CODE REVIEW

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Good stuff Mohamed! The `save` button isn't working properly for me, see the error:


Also like you mentioned before, clicking `Open` then `Cancel` then `Open` again produces this error. Can you investigate this and add a fix?


> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-:-NyCctN07nI-2x8ZB6oK:b-aiarnc)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @BigLiban, @BluCodeGH, and @KavinSatheeskumar)

___
*[`sinks/dashboard/dashboard.py` line 425 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NyCf6mY0K2syqQMw531:-NyCf6mY0K2syqQMw532:br44r5l) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5a14c4d14bbb968c92b9ed5df8d20fe08c48c1d5/sinks/dashboard/dashboard.py#L425)):*
> ```Python
>     # Method to save current layout to file
>     def save(self, filename: str = None):
>         save_directory = "saved-files"
> ```

Ok so the dashboard can be run from different places. For example, `launcher.py` will run it from the root omnibus directory. However when running manually, someone might `cd sinks/dashboard` and then run it. Can we add some logic to ensure the `saved-files` directory is under `sinks/dashboard` and files will always be saved there regardless of where the dashboard is run from?
___
*[`sinks/dashboard/dashboard.py` line 474 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NyCfscrC-bkR1sSeh4F:-NyCfscrC-bkR1sSeh4G:b-sclam1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5a14c4d14bbb968c92b9ed5df8d20fe08c48c1d5/sinks/dashboard/dashboard.py#L474)):*
> ```Python
>     def show_save_as_prompt(self) -> str:
>         # Show a prompt box using QInputDialog
>         text, ok = QInputDialog.getText(self, 'Input Dialog', 'Enter file name:')
> ```

Add "without extension" so people enter `savefile2` rather than `savefile2.json`
___
*[`sinks/dashboard/dashboard.py` line 483 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NyCg4gKD6LJpHdW8Igb:-NyCg4gKD6LJpHdW8Igc:b2hzqna) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/5a14c4d14bbb968c92b9ed5df8d20fe08c48c1d5/sinks/dashboard/dashboard.py#L483)):*
> ```Python
> 
>     # Method to switch to a layout in a different file
>     def switch(self):
> ```

Can we rename this to `open` instead of `switch` and remove the `self.save()` call? IMO the open command shouldn't overwrite the savefile, it should just clear the dashboard and open the file chosen by the user. Thoughts?

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work! Couple things:
- At the bottom of the file, you'll see a `dash.load()` call. This is used so that when you start up the dashboard, it'll auto-load `savefile.json`. Since your changes, this isn't working, I think it's just a matter of updating the filepath
- Since you added a shortcut for save, I think it would be good to add ones for save as and open as well (Shift-Cmd-S and Cmd-O?). However we do have an issue open for keyboard shortcuts (#207) so it's up to you if you wanna implement those now or add them to that issue
- This is a nitpick, but when the file picker comes up for the open method, is there any way to have it already at the `saved-files` folder? Not necessary though

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-:-NycHQ6722rvi0xPe9lW:bob2lo7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

**Review by Darth-Raazi — COMMENTED** [review]
One more thing, if I open a custom savefile (let's say `savefile2.json`), move things around and hit the save button, it saves to `savefile2.json` not the default `savefile.json`. Currently, pressing save should always save to the default file and the user should use save as to save somewhere else

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-:-NycPJYs4HknP3gIYSyO:b-sf6y1g)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH and @KavinSatheeskumar)

**Comment by BigLiban** [comment]
Completed all the changes requested

**Comment by BigLiban** [comment]
:lgtm:

**Review by BigLiban — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-:-NzPCl_35vIur93FKdxR:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

**Review by patrick-gu — CHANGES_REQUESTED** [review]
Works very well so far! Just a few small details

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-:-NzYZrgp6Qm2A2Hk6Bh-:b-ojovit)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 39 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYYyZN3nYswOCT6QQQ:-NzYYyZN3nYswOCT6QQR:b-k0g67a) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L39)):*
> ```Python
> from publisher import publisher
> from typing import Union
> from typing import Union
> ```

dupe import
___
*[`sinks/dashboard/dashboard.py` line 435 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYZ7Uj7ld36i9YcVfH:-NzYZ7Uj7ld36i9YcVfI:be3rdn9) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L435)):*
> ```Python
> 
>     # Method to save current layout to file
>     def save(self, filename: Union[str, bool] = False):
> ```

Use `Optional[str]` here
___
*[`sinks/dashboard/dashboard.py` line 503 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYZYYC3kIPJu1h91yE:-NzYZYYC3kIPJu1h91yF:b-xaj0mi) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L503)):*
> ```Python
>         
>         self.default_file_location = filename
>         self.load()
> ```

Would be good to have some graceful error handling here if the file isn't valid

**Review by Darth-Raazi — APPROVED** [review]
:lgtm: just cleanup those last few comments. Well done!

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-:-NzaK8syC98A7eTQcUTW:bqo4pw1)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @BluCodeGH, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 39 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYYyZN3nYswOCT6QQQ:-NzaIxoj10cTjC_VZuzW:b3ks9) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L39)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

dupe import
</blockquote></details>

^
___
*[`sinks/dashboard/dashboard.py` line 503 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYZYYC3kIPJu1h91yE:-NzaJjNZ5L1SeXM5sFm1:b-eci2dj) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L503)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Would be good to have some graceful error handling here if the file isn't valid
</blockquote></details>

It opens a file picker that only lets you select JSON files so I'm not too worried

**Comment by BigLiban** [comment]
*[`sinks/dashboard/dashboard.py` line 503 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYZYYC3kIPJu1h91yE:-NzoHhM5DI2CGhU6fCpa:bo0v354) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L503)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

It opens a file picker that only lets you select JSON files so I'm not too worried
</blockquote></details>

I'll skip on implementing this then as it only lets you select JSON files

**Review by BigLiban — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @BluCodeGH, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, @patrick-gu, and @saads312)

___
*[`sinks/dashboard/dashboard.py` line 39 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYYyZN3nYswOCT6QQQ:-NzoHxCx1QY5QN09veRl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L39)):*
<details><summary><i>Previously, Darth-Raazi (Ozayr Raazi) wrote…</i></summary><blockquote>

^
</blockquote></details>

Done.
___
*[`sinks/dashboard/dashboard.py` line 435 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-NzYZ7Uj7ld36i9YcVfH:-NzoHwuv32waoStc2LXT:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/a2917dcbcefcdf7f074a268ef071937b30a30cbe/sinks/dashboard/dashboard.py#L435)):*
<details><summary><i>Previously, patrick-gu (Patrick Gu) wrote…</i></summary><blockquote>

Use `Optional[str]` here
</blockquote></details>

Done.

**Review by patrick-gu — APPROVED** [review]
:lgtm: deleted an unused import

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/219#-:-NzpEPE-4Lfir-aAcq_K:b-39ck4u)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BluCodeGH, @KavinSatheeskumar, @Lucifersan, and @saads312)

**Pull request merged**
