### PR TITLE
Implement #174, Save the current config (selected source and sink) an…

### LINKED ISSUE #174: Add Config Saving to Launcher
Add functionality to launcher to save the current config (selected source and sink) and then automatically launch it next time using `python launcher.py --last`

### PR DESCRIPTION
**Pull request by zangjiucheng**
## Description

This PR adds a new feature to omnibus that saves all selected sources and sinks from the last time at  `config.ini` for the next load. To utilize this feature, you must run the command with the parameter `python launcher.py --last`. 

I changed `launcher.py` for the following point:
- implement `load_config` and `save_selected_to_config` in the Launcher class.
- add another run argument `--last` 
- detect if `config.ini` exists when call with the `--last` argument
- delete double initial with `sink_selected` and `src_selected` which is useless.

This PR closes #174.

## Developer Testing

Here's what I did to test my changes:

- Ran without parameters, select the list, then exit and check to see if it was saved to `config.ini`.
- Ran with `--last` to check that the GUI and selection lists are automatically updated
- Ran with `--text --last` to check with No-Gui if selection lists are automatically updated
- Ran with `--last` without `config.ini` existing to check if it detected and require you to select again.

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Run it any way you like to check that this new feature works in all cases.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
I think this is designed in a way that makes a lot of sense.

Right now, the text version doesn't seem to be working for me. I picked sinks 1 and sources 1, then tried again by leaving it empty, and it didn't seem to work

Thanks!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-:-O-1ElLXDFwiA0nx1y9z:b-wjg8px)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @zangjiucheng)

___
*[`launcher.py` line 55 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-O-1Qm-vCq1cB4yJAQTn:-O-1Qm-wCxYSTKuZH9sZ:bxu166o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7274584e7d16ef120057e7c955caa67c636aa895/launcher.py#L55)):*
> ```Python
>             self.load_last = False
>             return
>         with open("config.ini", "r") as f:
> ```

I would recommend using a JSON file here instead, as it's consistent with everything else, more reliable, and easier to work with.

Also, not sure if it should be called "config"
___
*[`launcher.py` line 82 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-O-1Qz304PuqkrsWZQew:-O-1Qz304PuqkrsWZQex:bx1fcku) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/7274584e7d16ef120057e7c955caa67c636aa895/launcher.py#L82)):*
> ```Python
>         print(*self.src_selected, sep=", ")
>         print("Last selected sinks: ", end="")
>         print(*self.sink_selected, sep=", ")
> ```

A thought I have is that maybe it'll be easier if you hide this if there was nothing run before

**Comment by zangjiucheng** [comment]
Hello :) Thanks for reviewing, this is an updated version based on your review suggestion.

I did not get your meaning to 

> A thought I have is that maybe it'll be easier if you hide this if there was nothing run before

Feel free to let me know if you have any other suggestions for it!

**Comment by patrick-gu** [comment]
Hi, thanks for clarifying, and sorry for the confusion - very poor wording on my part. What I meant is that, if we haven't run the launcher before (or at least, we can't find a file corresponding to a previous launch), it is probably not necessary to actually print that information out.

**Comment by zangjiucheng** [comment]
It's not your fault, my English is a bit bad too. I guess it was caused by a bug in the old text mode, after fixing it should work fine :))

**Review by patrick-gu — CHANGES_REQUESTED** [review]
Good changes!
- I still don't think the text mode is working for me
- Ignore the last comment about not printing. The behaviour makes sense.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-:-O-4Duj16TKvAk2yhkTl:bn65ua)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Great work on this! One thing I will say is that the point of the `--last` argument is to reduce user intervention. Meaning if I run launcher with `--last`, Omnibus should run with my last sources/sinks without me having to do anything else. In GUI mode, the GUI shouldn't even come up, so no mouse click needed. In text mode, it shouldn't prompt me, so no need to type. It's not enough to just preload the choices, this special last mode should skip prompts altogether

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-:-O-4noq97NM_itNWw0bF:btmwqnj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Review by patrick-gu — APPROVED** [review]
Everything works fine to me now!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-:-O-8uhpU4Z1_ZKf13edY:b6eijn2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Review by Darth-Raazi — CHANGES_REQUESTED** [review]
Works for me too!

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-:-O-K7P3z5UwE4PxkCQ28:brtq3f)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Lucifersan, @saads312, and @zangjiucheng)

___
*[`launcher.py` line 333 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-O-K6pDNCMCHTRGOUSFw:-O-K6pDO7KO2DzYWdvpd:b-62vzwz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3457f30a119d1228f1e7fa542d1ba1701bca4d4b/launcher.py#L333)):*
> ```Python
>     app = QApplication(sys.argv)
> 
>     # If 'python launcher.py --text' is run this block of code will execute
> ```

Update comment
___
*[`launcher.py` line 339 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-O-K72eZ9xbql5PtR3Ze:-O-K72eZ9xbql5PtR3Zf:bv2yqwh) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/3457f30a119d1228f1e7fa542d1ba1701bca4d4b/launcher.py#L339)):*
> ```Python
>         launcher.load_last = True
>         launcher.load_config()
>         launcher.input()
> ```

Since both the if and elif branches run `.input(), .subprocess(), .logging(), .terminate()` is there a way to combine these calls and not have them duplicated? Might be a bit tricky cause of the else branch

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/230#-:-O-Nz2dj99vLd1X_jJWD:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Lucifersan, @saads312, and @zangjiucheng)

**Pull request merged**
