### PR TITLE
208-right-click-menu Added right click menu to Omnibus dashboard

### LINKED ISSUE #208: Right-Click Menu
Right-clicking an item should bring up a small menu with useful actions. Pretty much action with a keyboard shortcut (see #207) should be included in this menu

### PR DESCRIPTION
**Pull request by Tintinnit**
## Description
Right click menu was added to Omnibus dashboard for ease of use. 

Added context_menu to dashboard.py for a right click menu.

This PR closes #208 .

## Developer Testing

Here's what I did to test my changes:

- Ran Omnibus with a dashboard, and tested if the right click menu shows up
- Tested if the different options in the right click menu work as intended
- Ran edge cases such as widget overlapping (currently buggy)

## Reviewer Testing

Here's what you should do to quickly validate my changes:

- Run Omnibus with dashboard and test right click menu features similar to how I did above.

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/275)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
This works fine for me, and the code generally seems good. However, a few concerns with the features:
- I know @Darth-Raazi suggested this but I don't think it's particularly helpful to have save, save as, open in the menu
- In order for any of the actions to take effect, you have to actually have selected something, which I feel is not really what you would expect from a menu. Maybe it could auto select what you're hovering over? Or hide some options if you haven't clicked on anything? But I certainly know it's probably not the easiest to implement this.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/275#-:-O28IYFmBDfIIkESxkE7:b-i0uw5e)* status: all files reviewed, 3 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, @saads312, and @Tintinnit)

___
*[`sinks/dashboard/dashboard.py` line 7 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/275#-O28JciXAvWdeMQc0om6:-O28JciXAvWdeMQc0om7:bg6zlk2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cfc4933920e869d34019661ccd6ce6bd03a258d4/sinks/dashboard/dashboard.py#L7)):*
> ```Python
> import signal
> 
> from PySide6.QtGui import QContextMenuEvent
> ```

Can this be imported from the same place as below?
___
*[`sinks/dashboard/dashboard.py` line 326 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/275#-O28IaNeCEtm-oBjHEXL:-O28IaNeCEtm-oBjHEXM:b-ae6two) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cfc4933920e869d34019661ccd6ce6bd03a258d4/sinks/dashboard/dashboard.py#L326)):*
> ```Python
>         save = self.context_menu.addAction("Save")
>         saveAs = self.context_menu.addAction("Save As")
>         open = self.context_menu.addAction("Open")
> ```

This conflicts with the builtin `open` function
___
*[`sinks/dashboard/dashboard.py` line 345 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/275#-O28JDChChgVX7grlHFv:-O28JDChChgVX7grlHFw:b-qqc4a) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/cfc4933920e869d34019661ccd6ce6bd03a258d4/sinks/dashboard/dashboard.py#L345)):*
> ```Python
>         sendBackward.triggered.connect(self.send_backward)
> 
>         self.show()
> ```

Why is this here?

**Review by zangjiucheng — APPROVED** [review]
LGTM

**Review by patrick-gu — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/275)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

**Review by patrick-gu — APPROVED** [review]
I haven't tested the changes but my code suggestions have been addressed

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/275#-:-O80CZSL99tfil82b1ij:b-wrcdt6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

**Pull request merged**
