### PR TITLE
Fix issue of newline byte error causing data to be missed

### PR DESCRIPTION
**Pull request by KavinSatheeskumar**
There was an issue where, if the data being sent happened to contain a new line, it would be missed due to parse errors. This is a quick fix to recover if that is the issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251)

### CODE REVIEW

**Review by patrick-gu — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251)* status: all files reviewed, 2 unresolved discussions (waiting on @BigLiban, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @saads312)

___
*[`sources/rlcs/main.py` line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-O17ppbI6512sXYI55qe:-O17ppbI6512sXYI55qf:b-uefduh) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/57abc9a47150b3ccfd9eb7d480dc85f594f5987f/sources/rlcs/main.py#L45)):*
> ```Python
> 
>         if not parsed_data:
>             if int(line[-1]) == ord('R'):
> ```

might make it more clear to write



_Code snippet:_
```Python
if line[-1] == b'R':
```
___
*[`sources/rlcs/main.py` line 48 at r1](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-O17pb7sB3arDV4Zx7w6:-O17pb7sB3arDV4Zx7w7:bfoo8rn) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/57abc9a47150b3ccfd9eb7d480dc85f594f5987f/sources/rlcs/main.py#L48)):*
> ```Python
>                 line = b''
>             else:
>                 line += b'\n'
> ```

There is potentially a problem here: `readline` will strip any occurrences of `\r\n`

**Comment by patrick-gu** [comment]
The data format will likely need to be updated, but this reduces the potential for error a bit. As it's not critical, we can use this branch for WDR

**Review by patrick-gu — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

___
*[`sources/rlcs/main.py` line 22 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-O17zlTDANMH4G0yvvvJ:-O17zlTDANMH4G0yvvvK:b5ig0s2) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/2e05c23c727386bfbd05b2218d9ca117a4bc99b0/sources/rlcs/main.py#L22)):*
> ```Python
> 
>         if output[-1] != ord('R'):
>             return None
> ```

Made it block until we read a valid message

I think this should be a generator but whatever
___
*[`sources/rlcs/main.py` line 46 at r4](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-O18-jukDUJT2zsK4pkj:-O18-jukDUJT2zsK4pkk:b9mo9ym) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/e916f96a154e421005eae6d3a1ce641b855d7d8a/sources/rlcs/main.py#L46)):*
> ```Python
>         line = readline()
> 
>         if not len(line):
> ```

not sure if this is even necessary anymore but no harm in leaving it

**Review by patrick-gu — CHANGES_REQUESTED** [review]
I noticed a potential issue.

Also, if we have dropped or extra bytes, the data may be invalid, without any way of knowing. But I don't think that's a new issue

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-:-O181Xcz7ulFmkcW6AHQ:bnkjzf8)* status: all files reviewed, 1 unresolved discussion (waiting on @BigLiban, @Darth-Raazi, @KavinSatheeskumar, @Lucifersan, and @saads312)

___
*[`sources/rlcs/main.py` line 22 at r5](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-O181MpGB7m6XTQn55CX:-O181MpH3wwZSRs_p32L:bmqb14g) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/1f8fc5617624273a08e45945ae592787b79dc1f2/sources/rlcs/main.py#L22)):*
> ```Python
>                 continue
> 
>             output = b'W' + s.read(rlcs.EXPECTED_SIZE - 1)
> ```

Actually, I think this doesn't work correctly, because we need to include a newline. So I think it should be just EXPECTED_SIZE?

**Review by patrick-gu — APPROVED** [review]
updated the newline thing

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-:-O1831DS-WyAAJe64ss0:b-kkn1jr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Darth-Raazi, @Lucifersan, and @saads312)

**Review by Darth-Raazi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/251#-:-O189gEn0XyKR98cay04:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BigLiban, @Lucifersan, and @saads312)

**Comment by patrick-gu** [comment]
Tested with RLCS switches and voltage, will merge. We should keep in mind error handling for the future

**Pull request merged**
