### PR TITLE
Export to KMZ

### LINKED ISSUE #299: Export stream data present to KMZ file
- After the rocket landing to the ground, we wanna export all our gps data point plot on the graph to a single KMZ file. 
- Should be able load with `Avenza App` (which used by the recover group people) 
- Data point from different board should have distance colour. 

Required: #317

### PR DESCRIPTION
**Pull request by vincentjguo**
## Description
Added export to kmz option

Modified kmz_parser to test with exported kmz file (mainly a parsing issue)

This PR closes #299.

image
image

kml snippet:
```xml
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Points</name>
    <Placemark>
      <name>GPS Point</name>
      <description>Board ID: GPS</description>
      <TimeStamp>
        <when>2024-11-21T18:43:47</when>
      </TimeStamp>
      <Point>
        <coordinates>-82.56016666666666,49.49333333333334,423.2</coordinates>
      </Point>
    </Placemark>
  </Document>
```

## Developer Testing

Here's what I did to test my changes:

- Ran map with test points from log replay
- Exported points to kmz and kml files
- Verified kml file format
- Imported to google earth
- Imported to interamap

## Reviewer Testing

Here's what you should do to quickly validate my changes:
- Try exporting points and importing

For consideration: 
- Name of exported file, should user select save location?
- Name of GPS_points, do we need a UID?

- - -
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332)

### CODE REVIEW

**Review by vincentjguo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @zangjiucheng)

___
*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCJllJQ1qYiBQ64Dmlu:-OCL96Vk8Uhk_hAdipNo:bjrnfeh) (no related file):*
<details><summary><i>Previously, zangjiucheng (Jiucheng(Oliver)) wrote…</i></summary><blockquote>

Excellent implement! I did a test following your instructions, and it is working as expected. 

Just a few things need to be addressed:
1. Can you pull out export_point to a separate export kmz file.  
2. Is that possible to clean the <kml:...>, not a big deal just make it looks messy.

3. Can you try to support exporting different board_id to different layers? This can be supported to select layers to view. 
4. I did try with the Avenza map, but for some reason, it does not support it... I will discuss with Rio maybe we can just use the omnibus or some way to cover it to Avenza map support type (Unfortunately, they don't have a clear document). So don't worry about this too much. 
5. If possible, can you try to support the Timestamp plot when we load the kmz file? 
6. Can you leave a schema of your structure in the folder? 

That's all the part that needs to be addressed, but you did excellent. Some points I may not address enough, sorry about that.
</blockquote></details>

1. I moved the function to GPS_cache, lemme know if that works for you
2. Not sure why your ending tags are cut off like that... but this is formatted by FastKML and prettyprint is already on - not sure how to make it even more pretty
3. Not entirely sure how to create layers with FastKML... I put them into folders instead which google earth lets you hide the entire folder. The only thing i found about layers was [this](https://developers.google.com/maps/documentation/javascript/kmllayer#overview) doc for JS. LMK if you find anything else
4. Hmm, i just tried it and yea it's unsupported for some reason? Can't get any logs either...
5. I did actually include a timestamp tag on each placemark. Google earth just doesn't do anything with it for some reason. I added it to the description for now, but i'll keep looking into that
6. Done!

**Review by zangjiucheng — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332)* status: all files reviewed, 4 unresolved discussions (waiting on @vincentjguo)

___
*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCJllJQ1qYiBQ64Dmlu:-OCi6gQl8ztI1tzBvAhP:b-efxqyx) (no related file):*
<details><summary><i>Previously, vincentjguo (Vincent) wrote…</i></summary><blockquote>

1. I moved the function to GPS_cache, lemme know if that works for you
2. Not sure why your ending tags are cut off like that... but this is formatted by FastKML and prettyprint is already on - not sure how to make it even more pretty
3. Not entirely sure how to create layers with FastKML... I put them into folders instead which google earth lets you hide the entire folder. The only thing i found about layers was [this](https://developers.google.com/maps/documentation/javascript/kmllayer#overview) doc for JS. LMK if you find anything else
4. Hmm, i just tried it and yea it's unsupported for some reason? Can't get any logs either...
5. I did actually include a timestamp tag on each placemark. Google earth just doesn't do anything with it for some reason. I added it to the description for now, but i'll keep looking into that
6. Done!


</blockquote></details>

Nice shoot, lol, all issues will be addressed. Just two tiny points need to be addressed; please check the comment below :) 

Thanks for your contribution.
___
*[`sinks/interamap/src/gps_cache.py` line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCi61ifCofqMAbPe08r:-OCi61ifCofqMAbPe08s:bai65cz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec2378822051c6dcba4aa66723f34486c0499fd1/sinks/interamap/src/gps_cache.py#L8)):*
> ```Python
> from PySide6.QtCore import QThread, Signal
> from fastkml import kml, geometry, times
> ```

For use prettyprint I believe it needs `import lxml`
___
*[`sinks/interamap/src/gps_cache.py` line 75 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCi6PcoDccghsUs1-ad:-OCi6PcoDccghsUs1-ae:bwuv9up) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec2378822051c6dcba4aa66723f34486c0499fd1/sinks/interamap/src/gps_cache.py#L75)):*
> ```Python
>             raise "Error: Unstored info to be removed" + str(info)
> 
>     def export_points(self):
> ```

Nice! 
___
*[`sinks/interamap/sample.kml` line 0 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCi5miI6Fk_bekAJ7Nx:-OCi5miI6Fk_bekAJ7Ny:b1b3b4e) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec2378822051c6dcba4aa66723f34486c0499fd1/sinks/interamap/sample.kml#L0)):*
Can you change this name to `schema.kml`? I think it would be clearer.

**Review by vincentjguo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @zangjiucheng)

___
*[`sinks/interamap/src/gps_cache.py` line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCi61ifCofqMAbPe08r:-OCoA-Q13xviLaYkGQ2V:b-2s7zej) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec2378822051c6dcba4aa66723f34486c0499fd1/sinks/interamap/src/gps_cache.py#L8)):*
<details><summary><i>Previously, zangjiucheng (Jiucheng(Oliver)) wrote…</i></summary><blockquote>

For use prettyprint I believe it needs `import lxml`
</blockquote></details>

I can't seem to find a mention of this in the docs, then again they are not very comprehensive. Can you show me where this is needed? 
___
*[`sinks/interamap/sample.kml` line  at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCi5miI6Fk_bekAJ7Nx:-OCo9zBmE3GPjr7Ssujk:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec2378822051c6dcba4aa66723f34486c0499fd1/sinks/interamap/sample.kml#L)):*
<details><summary><i>Previously, zangjiucheng (Jiucheng(Oliver)) wrote…</i></summary><blockquote>

Can you change this name to `schema.kml`? I think it would be clearer.
</blockquote></details>

Done.

**Review by zangjiucheng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @vincentjguo)

___
*[`sinks/interamap/src/gps_cache.py` line 8 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/332#-OCi61ifCofqMAbPe08r:-OCtdmNu0YZPKKCGjkXD:b5o13un) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/ec2378822051c6dcba4aa66723f34486c0499fd1/sinks/interamap/src/gps_cache.py#L8)):*
<details><summary><i>Previously, vincentjguo (Vincent) wrote…</i></summary><blockquote>

I can't seem to find a mention of this in the docs, then again they are not very comprehensive. Can you show me where this is needed?
</blockquote></details>

Sorry to be unclear, but I think it should be added to requirement.txt, not here. 

Reference: (Not in documents, but in their repo) 
https://github.com/cleder/fastkml/blob/main/fastkml/config.py?#L39

**Pull request merged**
