### PR TITLE
Plot graphics

### PR DESCRIPTION
**Pull request by PCModeActivate**
Adding running average and an experimental label to the graph window

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Looks like you need to run the formatter. Lookng good though.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-:-MoBxVRy6MLpZkNZ9zQd:b-dpkcs)* status: all files reviewed, 6 unresolved discussions (waiting on @DevinLeamy, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/plot.py, line 36 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC6O3nDPInICIjVpwM:-MoC6O3nDPInICIjVpwN:b-n87vwz) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L36)):*
> ```Python
> 
>         # adding a label masquerading as a graph
>         self.labelText = ""
> ```

Why are you storing this? Python strings are immutable, you need to manually call `label.setText` with a new string to update. Better to explicitly put the string in the `setText` call.
___
*[sinks/plot/plot.py, line 52 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC6qMo1_gWjF8Y3TVp:-MoC6qMo1_gWjF8Y3TVq:beifk01) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L52)):*
> ```Python
>             print(f"\rFPS: {self.fps: >4.2f}  ", end='')
>         #for s in self.series:
>         #    self.labelText += ("\navg of " + s.name + f": {s.getRunningAvg(): <4.4f}")
> ```

Remove old code please.
___
*[sinks/plot/plot.py, line 75 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC715u9nz6okEg3lOM:-MoC715u9nz6okEg3lON:b-ciom1o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L75)):*
> ```Python
>     def __init__(self, series):
>         self.series = series
>         self.avg = 0
> ```

Unused?
___
*[sinks/plot/plot.py, line 87 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC7BKT99FN9nbXR0cg:-MoC7BKT99FN9nbXR0ch:b-fzrdvh) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L87)):*
> ```Python
> 
>         # current value readout in the title
>         self.plot.setTitle(f"{self.series.name} ({self.series.points[-1]:.1f}) [{self.series.getRunningAvg(): <4.4f}]")
> ```

We don't need to display the most recent datapoint if we have the running average.
___
*[sinks/plot/series.py, line 55 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC4nId6uN8emIMmGga:-MoC4nId6uN8emIMmGgb:b-gvmx9n) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L55)):*
> ```Python
>             self.times.fill(time)
>             self.points.fill(point)
>             self.sum += point
> ```

Take a look at the average values you get when running with FakeNI. The data should be uniformly distributed between 0 and 1 so you would expect the average to be quite close to 0.5 but it's often not, which implies a bug in your algorithm. I'd encourage you to think about what the issue could be, if you're stuck DM me.
___
*[sinks/plot/series.py, line 68 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC57vV3B6tr9pEIeHE:-MoC57vV3B6tr9pEIeHF:bn2wkb1) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L68)):*
> ```Python
> 
>     def getRunningAvg(self):
>         return (self.sum / self.size)
> ```

Extraneous brackets. Also, the goal with having the running average is to be able to easily read off the roughly current value of any sensor during ops (and not have to mentally remove noise). That means it needs to respond quickly to changes, so should only average over perhaps the last second rather than the entire graph duration.

**Review by BluCodeGH — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)* status: all files reviewed, 9 unresolved discussions (waiting on @DevinLeamy, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/plot.py, line 46 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoGy0-K6Emp7tOVCVb1:-MoPin3g7meG5oWNZm-s:byixehk) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L46)):*
<details><summary><i>Previously, DevinLeamy (Devin Leamy) wrote…</i></summary><blockquote>

Given that we're always popping from the front of `self.rates`, it's worth switching it to a deque.
</blockquote></details>

Definitely worth a performance investigation between the current solution, `numpy.roll` and a deque. I wouldn't be so certain to jump to a deque since numpy can be crazy fast in some cases. That being said, I'm not sure that within scope for this PR, up to @pcmodeactivate.
___
*[sinks/plot/series.py, line 68 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoH-YrX1MmPYTNygA5x:-MoPjEMSC7LzzVBNkWZr:b-dfpxyi) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L68)):*
<details><summary><i>Previously, DevinLeamy (Devin Leamy) wrote…</i></summary><blockquote>

If you calculate the average with `self.points.mean()`, you can get rid of `self.sum` and all the adding and subtracting.
</blockquote></details>

Using a separate rolling sum is significantly more efficient than re-summing every time. We're talking maybe 25k data points across all the plots.

**Review by DevinLeamy — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)* status: all files reviewed, 9 unresolved discussions (waiting on @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/series.py, line 68 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoH-YrX1MmPYTNygA5x:-MoRepFt7sl7w6jtCjdt:b-8xgsa4) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L68)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Using a separate rolling sum is significantly more efficient than re-summing every time. We're talking maybe 25k data points across all the plots.
</blockquote></details>

Point taken. 👍

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @BluCodeGH, @DevinLeamy, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/plot.py, line 36 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC6O3nDPInICIjVpwM:-MoiMLSS1joe3dVaZiFs:b5eczsx) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L36)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Why are you storing this? Python strings are immutable, you need to manually call `label.setText` with a new string to update. Better to explicitly put the string in the `setText` call.
</blockquote></details>

Yeah I forgot about that
Was planning to use it for if there are other info to be collected but there isnt any at the moment
___
*[sinks/plot/plot.py, line 46 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoGy0-K6Emp7tOVCVb1:-MoiMeNRD_jsY7UOXjA0:bbtoazk) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L46)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Definitely worth a performance investigation between the current solution, `numpy.roll` and a deque. I wouldn't be so certain to jump to a deque since numpy can be crazy fast in some cases. That being said, I'm not sure that within scope for this PR, up to @pcmodeactivate.
</blockquote></details>

Thats something we can look into in another PR for sure, @blucodegh we could do a test run with all three solutions? Also if we are always popping from front wouldn't a queue also fit? Not sure if its better than deque implementation though.
___
*[sinks/plot/plot.py, line 52 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC6qMo1_gWjF8Y3TVp:-MpYyjlE90jUA8WzHmQO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L52)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Remove old code please.
</blockquote></details>

Done.
___
*[sinks/plot/plot.py, line 75 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC715u9nz6okEg3lOM:-MpZ0LW5DR2s0FeSOM8Q:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L75)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unused?
</blockquote></details>

Done.
___
*[sinks/plot/plot.py, line 87 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC7BKT99FN9nbXR0cg:-MpZ0PI92dEJkvOEXK5Y:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L87)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

We don't need to display the most recent datapoint if we have the running average.
</blockquote></details>

Done.
___
*[sinks/plot/series.py, line 55 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC4nId6uN8emIMmGga:-MpYXXukEfiM1e4QBz57:b99n832) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L55)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Take a look at the average values you get when running with FakeNI. The data should be uniformly distributed between 0 and 1 so you would expect the average to be quite close to 0.5 but it's often not, which implies a bug in your algorithm. I'd encourage you to think about what the issue could be, if you're stuck DM me.
</blockquote></details>

Yep, fixed :)
___
*[sinks/plot/series.py, line 68 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoC57vV3B6tr9pEIeHE:-MoiNzyL07p2ex07c3-G:b758x4n) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L68)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Extraneous brackets. Also, the goal with having the running average is to be able to easily read off the roughly current value of any sensor during ops (and not have to mentally remove noise). That means it needs to respond quickly to changes, so should only average over perhaps the last second rather than the entire graph duration.
</blockquote></details>

Implemented the "how long for running average" for the user to configurate for this.
___
*[sinks/plot/series.py, line 68 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoH-YrX1MmPYTNygA5x:-MpZ0c0z4hdvqRwEtJ6W:bk2alp) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L68)):*
<details><summary><i>Previously, DevinLeamy (Devin Leamy) wrote…</i></summary><blockquote>

Point taken. 👍
</blockquote></details>

Yep, pretty much exactly why we don't want to don't need to sum up the entire thing when we can just track it like a queue. It's more efficient anyhow, even without 25k points.

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @BluCodeGH, @DevinLeamy, @KavinSatheeskumar, and @wendi-yu)

___
*[sinks/plot/series.py, line 67 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoH0hMN1eb9RC5wI5NK:-MpZ0wNi8wLZFAs3Iwkl:b-896fix) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/series.py#L67)):*
<details><summary><i>Previously, DevinLeamy (Devin Leamy) wrote…</i></summary><blockquote>

snake_case
</blockquote></details>

Done.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
CI is still complaining about autopep8. You can click into the test 'details' in github to see what's wrong.

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-:-MpZ6YaAAhwdr1-Yzwhx:b-c11w8i)* status: all files reviewed, 5 unresolved discussions (waiting on @DevinLeamy, @KavinSatheeskumar, @PCModeActivate, and @wendi-yu)

___
*[sinks/plot/plot.py, line 46 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoGy0-K6Emp7tOVCVb1:-MpZ5YmnDtM9Lppe8Rkp:b4ggras) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L46)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Thats something we can look into in another PR for sure, @blucodegh we could do a test run with all three solutions? Also if we are always popping from front wouldn't a queue also fit? Not sure if its better than deque implementation though.
</blockquote></details>

Sounds like a plan.
___
*[sinks/plot/plot.py, line 44 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MpZ5eajBmRMYHCSw0Iv:-MpZ5eajBmRMYHCSw0Iw:b-ciom25) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/0f506918f4712ecd21a0cc536cb1e8be2ac450ae/sinks/plot/plot.py#L44)):*
> ```Python
>     # called every frame
>     def update(self):
>         self.labelText = ""
> ```

Unused.
___
*[sinks/plot/series.py, line 2 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MpZ68JeB2maRRNPdDdK:-MpZ68JeB2maRRNPdDdL:b-ciom1o) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/0f506918f4712ecd21a0cc536cb1e8be2ac450ae/sinks/plot/series.py#L2)):*
> ```Python
> import numpy as np
> from numpy.core.fromnumeric import size
> ```

Unused?

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @BluCodeGH, @DevinLeamy, @KavinSatheeskumar, and @wendi-yu)

___
*[sinks/plot/plot.py, line 46 at r2](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MoGy0-K6Emp7tOVCVb1:-MpZVDadCKB0IPlgqHoN:b6tylwq) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/6ff769a4594b8692f8ab1b60fb26e3dcd765e6a0/sinks/plot/plot.py#L46)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Sounds like a plan.
</blockquote></details>

Yeah, new PR (or a new branch/issue for testing it it is)
___
*[sinks/plot/series.py, line 2 at r3](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38#-MpZ68JeB2maRRNPdDdK:-MpZV_8I7ugiI_kTi3f6:bblkb0p) ([raw file](https://github.com/waterloo-rocketry/omnibus/blob/0f506918f4712ecd21a0cc536cb1e8be2ac450ae/sinks/plot/series.py#L2)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

Unused?
</blockquote></details>

That wasnt newly added I think? But I will remove it regardless.

**Review by BluCodeGH — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)* status: all files reviewed, 3 unresolved discussions (waiting on @DevinLeamy, @KavinSatheeskumar, and @wendi-yu)

**Review by DevinLeamy — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/omnibus/38)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KavinSatheeskumar and @wendi-yu)

**Pull request merged**
